import type { Exercise } from "@/lib/types";

/** Commercial exotic / amateur-night vocabulary plus class-capacity work. */
export const EXOTIC_EXERCISES: Exercise[] = [
  {
    id: "hip-figure-8",
    name: "Standing hip figure-8",
    pattern: "mobility",
    primaryMuscles: ["glutes", "obliques"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Draw an 8 with the belt line, not a dumped lumbar hinge. Soft knees. Ribs stacked. Slow enough to reverse direction cleanly.",
    substitutes: ["body-wave", "seated-hip-isolation"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "seated-hip-isolation",
    name: "Seated hip isolation",
    pattern: "isolation",
    primaryMuscles: ["glutes", "hip_flexors"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Sit tall on a chair or the floor. Move the pelvis in a small circle while the ribs stay quiet. This is the lap-set engine without a partner.",
    substitutes: ["hip-figure-8", "body-wave"],
    restSeconds: 30,
    priority: 2,
  },
  {
    id: "hip-pulse",
    name: "Hip pulse / booty pop",
    pattern: "isolation",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Tiny posterior pulse from the glutes. Do not crank the lumbar spine into a backbend. Stand, kneel, or sit. Quality over bounce.",
    substitutes: ["hip-figure-8", "glute-bridge"],
    restSeconds: 30,
    priority: 3,
    avoidIf: ["low_back"],
  },
  {
    id: "chest-isolation",
    name: "Rib / chest isolation",
    pattern: "mobility",
    primaryMuscles: ["abs", "obliques"],
    secondaryMuscles: ["upper_back"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Slide the ribcage over a quiet pelvis. Small range. This is musicality, not a neck roll. Stop if the neck or low back joins in.",
    substitutes: ["body-wave", "port-de-bras"],
    restSeconds: 20,
    priority: 3,
    avoidIf: ["low_back"],
  },
  {
    id: "floor-descent",
    name: "Controlled floor descent",
    pattern: "mobility",
    primaryMuscles: ["quads", "abs"],
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "From standing, lower to the knees with a hand on the floor or chair if you need it. No dropping. Pad the knees. Reverse to stand with the same control.",
    substitutes: ["tabletop-pose", "bodyweight-squat"],
    restSeconds: 45,
    priority: 1,
    avoidIf: ["knee"],
  },
  {
    id: "tabletop-pose",
    name: "Tabletop / all-fours hold",
    pattern: "core",
    primaryMuscles: ["abs", "glutes"],
    secondaryMuscles: ["front_delts"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Hands under shoulders, knees under hips, or drop to forearms. Long spine. This is the home base for floor phrases. Fists if wrists complain.",
    substitutes: ["floor-body-roll", "bird-dog"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["wrist", "knee"],
  },
  {
    id: "knee-walk-circle",
    name: "Knee walk and circle",
    pattern: "cardio",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Thick pads. Walk on the knees in a slow circle both ways. Hips stay over the knees — do not sit back into a painful hinge. Skip if the knees bark.",
    substitutes: ["floor-descent", "performance-walk"],
    restSeconds: 45,
    priority: 2,
    isCardio: true,
    avoidIf: ["knee"],
  },
  {
    id: "hair-toss-eyeline",
    name: "Hair toss and eye-line",
    pattern: "mobility",
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Turn the head with the torso, then let the hair follow. Do not whip the neck. Pick a still spot in the room and return to it. This is how a set reads as a show.",
    substitutes: ["port-de-bras", "performance-walk"],
    restSeconds: 20,
    priority: 3,
  },
  {
    id: "chair-approach-straddle",
    name: "Chair approach and straddle sit",
    pattern: "cardio",
    primaryMuscles: ["glutes", "quads"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "A sturdy chair, not a person. Walk in, turn, sit to the edge, open the knees only as far as the hips stay stacked. Hands on the seat or thighs. Stand without using momentum that yanks the knees.",
    substitutes: ["seated-hip-isolation", "performance-walk"],
    restSeconds: 45,
    priority: 1,
    isCardio: true,
    avoidIf: ["knee", "hip"],
  },
  {
    id: "chair-body-roll",
    name: "Chair body roll",
    pattern: "mobility",
    primaryMuscles: ["abs", "glutes"],
    secondaryMuscles: ["hip_flexors"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "From the chair edge, roll the spine through a wave and return tall. Keep the sit bones on the seat. No neck-loaded drop off the back of the chair.",
    substitutes: ["body-wave", "seated-hip-isolation"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "back-to-pole-pose",
    name: "Back-to-pole pose",
    pattern: "core",
    primaryMuscles: ["abs", "glutes"],
    secondaryMuscles: ["lats"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Spine along the pole, feet staggered, one or both hands on the pole at chest height. This is a hold you can breathe in — not a backbend contest. Both sides if you offset the feet.",
    substitutes: ["pole-walk", "performance-walk"],
    restSeconds: 45,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "controlled-descent",
    name: "Controlled pole descent",
    pattern: "vertical_pull",
    primaryMuscles: ["lats", "grip", "abs"],
    secondaryMuscles: ["adductors"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "From a sit or a low climb, lower hand-over-hand or thigh-slide with a crash mat. Sliding a full pole without control is how you burn skin and dump the shoulder. Both sides.",
    substitutes: ["basic-climb", "pole-sit"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "eight-count-phrase",
    name: "8-count show phrase",
    pattern: "cardio",
    primaryMuscles: ["glutes", "abs"],
    secondaryMuscles: ["calves"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "One 8-count you already own: walk 2, wave 2, pose 2, turn 2. Count out loud. No new tricks inside the phrase. Rest a full 8 after.",
    substitutes: ["performance-walk", "show-set-run"],
    restSeconds: 40,
    priority: 1,
    isCardio: true,
  },
  {
    id: "class-capacity-circuit",
    name: "Intermediate class capacity circuit",
    pattern: "cardio",
    primaryMuscles: ["grip", "abs", "glutes"],
    secondaryMuscles: ["lats", "quads"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "4–6 rounds of 40s on / 20s change: squat, push-up or incline push-up, hollow or dead bug, farmer or suitcase carry. This is 45-minute class lungs — not invert-day smash intervals.",
    substitutes: ["stage-circuit", "zone2-walk"],
    restSeconds: 60,
    priority: 1,
    isCardio: true,
  },
  {
    id: "active-hang-repeat",
    name: "Repeat active hangs (class grip)",
    pattern: "carry",
    primaryMuscles: ["grip", "lats"],
    secondaryMuscles: ["forearms"],
    equipment: ["pullup_bar"],
    safety: "recommended",
    safetyNote:
      "Several short active hangs with full rest. Intermediate class often asks you to hang, spin, hang again. Shoulders packed. Stop if the elbow tendon is angry.",
    substitutes: ["dead-hang", "farmer-carry"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["shoulder", "elbow"],
  },
];
