import type { Exercise } from "@/lib/types";

/** Commercial exotic / amateur-night vocabulary plus class-capacity work. */
export const EXOTIC_EXERCISES: Exercise[] = [
  {
    id: "hip-figure-8",
    name: "Standing hip figure-8",
    pattern: "mobility",
    primaryMuscles: ["glutes", "obliques"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Draw an 8 with the belt line, not a dumped lumbar hinge. Soft knees. Ribs stacked. Slow enough to reverse direction cleanly.",
    substitutes: ["body-wave", "seated-hip-isolation"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "seated-hip-isolation",
    name: "Seated hip isolation",
    pattern: "isolation",
    primaryMuscles: ["glutes", "hip_flexors"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Sit tall on a chair or the floor. Move the pelvis in a small circle while the ribs stay quiet. This is the lap-set engine without a partner.",
    substitutes: ["hip-figure-8", "body-wave"],
    restSeconds: 30,
    priority: 2,
  },
  {
    id: "hip-pulse",
    name: "Hip pulse / booty pop",
    pattern: "isolation",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Tiny posterior pulse from the glutes. Do not crank the lumbar spine into a backbend. Stand, kneel, or sit. Quality over bounce.",
    substitutes: ["hip-figure-8", "glute-bridge"],
    restSeconds: 30,
    priority: 3,
    avoidIf: ["low_back"],
  },
  {
    id: "chest-isolation",
    name: "Rib / chest isolation",
    pattern: "mobility",
    primaryMuscles: ["abs", "obliques"],
    secondaryMuscles: ["upper_back"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Slide the ribcage over a quiet pelvis. Small range. This is musicality, not a neck roll. Stop if the neck or low back joins in.",
    substitutes: ["body-wave", "port-de-bras"],
    restSeconds: 20,
    priority: 3,
    avoidIf: ["low_back"],
  },
  {
    id: "floor-descent",
    name: "Controlled floor descent",
    pattern: "mobility",
    primaryMuscles: ["quads", "abs"],
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "From standing, lower to the knees with a hand on the floor or chair if you need it. No dropping. Pad the knees. Reverse to stand with the same control.",
    substitutes: ["tabletop-pose", "bodyweight-squat"],
    restSeconds: 45,
    priority: 1,
    avoidIf: ["knee"],
  },
  {
    id: "tabletop-pose",
    name: "Tabletop / all-fours hold",
    pattern: "core",
    primaryMuscles: ["abs", "glutes"],
    secondaryMuscles: ["front_delts"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Hands under shoulders, knees under hips, or drop to forearms. Long spine. This is the home base for floor phrases. Fists if wrists complain.",
    substitutes: ["floor-body-roll", "bird-dog"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["wrist", "knee"],
  },
  {
    id: "knee-walk-circle",
    name: "Knee walk and circle",
    pattern: "cardio",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Thick pads. Walk on the knees in a slow circle both ways. Hips stay over the knees — do not sit back into a painful hinge. Skip if the knees bark.",
    substitutes: ["floor-descent", "performance-walk"],
    restSeconds: 45,
    priority: 2,
    isCardio: true,
    avoidIf: ["knee"],
  },
  {
    id: "hair-toss-eyeline",
    name: "Hair toss and eye-line",
    pattern: "mobility",
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Turn the head with the torso, then let the hair follow. Do not whip the neck. Pick a still spot in the room and return to it. This is how a set reads as a show.",
    substitutes: ["port-de-bras", "performance-walk"],
    restSeconds: 20,
    priority: 3,
  },
  {
    id: "chair-approach-straddle",
    name: "Chair approach and straddle sit",
    pattern: "cardio",
    primaryMuscles: ["glutes", "quads"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "A sturdy chair, not a person. Walk in, turn, sit to the edge, open the knees only as far as the hips stay stacked. Hands on the seat or thighs. Stand without using momentum that yanks the knees.",
    substitutes: ["seated-hip-isolation", "performance-walk"],
    restSeconds: 45,
    priority: 1,
    isCardio: true,
    avoidIf: ["knee", "hip"],
  },
  {
    id: "chair-body-roll",
    name: "Chair body roll",
    pattern: "mobility",
    primaryMuscles: ["abs", "glutes"],
    secondaryMuscles: ["hip_flexors"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "From the chair edge, roll the spine through a wave and return tall. Keep the sit bones on the seat. No neck-loaded drop off the back of the chair.",
    substitutes: ["body-wave", "seated-hip-isolation"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "back-to-pole-pose",
    name: "Back-to-pole pose",
    pattern: "core",
    primaryMuscles: ["abs", "glutes"],
    secondaryMuscles: ["lats"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Spine along the pole, feet staggered, one or both hands on the pole at chest height. This is a hold you can breathe in — not a backbend contest. Both sides if you offset the feet.",
    substitutes: ["pole-walk", "performance-walk"],
    restSeconds: 45,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "controlled-descent",
    name: "Controlled pole descent",
    pattern: "vertical_pull",
    primaryMuscles: ["lats", "grip", "abs"],
    secondaryMuscles: ["adductors"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "From a sit or a low climb, lower hand-over-hand or thigh-slide with a crash mat. Sliding a full pole without control is how you burn skin and dump the shoulder. Both sides.",
    substitutes: ["basic-climb", "pole-sit"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "eight-count-phrase",
    name: "8-count show phrase",
    pattern: "cardio",
    primaryMuscles: ["glutes", "abs"],
    secondaryMuscles: ["calves"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "One 8-count you already own: walk 2, wave 2, pose 2, turn 2. Count out loud. No new tricks inside the phrase. Rest a full 8 after.",
    substitutes: ["performance-walk", "show-set-run"],
    restSeconds: 40,
    priority: 1,
    isCardio: true,
  },
  {
    id: "class-capacity-circuit",
    name: "Intermediate class capacity circuit",
    pattern: "cardio",
    primaryMuscles: ["grip", "abs", "glutes"],
    secondaryMuscles: ["lats", "quads"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "4–6 rounds of 40s on / 20s change: squat, push-up or incline push-up, hollow or dead bug, farmer or suitcase carry. This is 45-minute class lungs — not invert-day smash intervals.",
    substitutes: ["stage-circuit", "zone2-walk"],
    restSeconds: 60,
    priority: 1,
    isCardio: true,
  },
  {
    id: "active-hang-repeat",
    name: "Repeat active hangs (class grip)",
    pattern: "carry",
    primaryMuscles: ["grip", "lats"],
    secondaryMuscles: ["forearms"],
    equipment: ["pullup_bar"],
    safety: "recommended",
    safetyNote:
      "Several short active hangs with full rest. Intermediate class often asks you to hang, spin, hang again. Shoulders packed. Stop if the elbow tendon is angry.",
    substitutes: ["dead-hang", "farmer-carry"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["shoulder", "elbow"],
  },
  {
    id: "heel-walk",
    name: "Heel walk",
    pattern: "cardio",
    primaryMuscles: ["calves", "glutes"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Only after the trainer walk is quiet. Shorter steps. Soft knees. Ankle roll, pinching, or numbness is a stop. No new tricks in heels.",
    substitutes: ["performance-walk", "short-foot"],
    restSeconds: 40,
    priority: 1,
    isCardio: true,
    avoidIf: ["ankle"],
  },
  {
    id: "money-hands",
    name: "Hand styling / open palm",
    pattern: "mobility",
    primaryMuscles: ["forearms"],
    secondaryMuscles: ["upper_back"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Soft hands, shoulders down. Trace the body, then an open palm at a wall mark. No behind-the-head ports. This is framing and receiving — not grabbing.",
    substitutes: ["port-de-bras", "hair-toss-eyeline"],
    restSeconds: 20,
    priority: 3,
  },
  {
    id: "stage-map",
    name: "Stage map (rail and corners)",
    pattern: "cardio",
    primaryMuscles: ["glutes", "calves"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Tape a rectangle. Walk downstage (rail), both corners, then home to a pole or chair. Same slow walk. No running.",
    substitutes: ["performance-walk", "pole-walk"],
    restSeconds: 40,
    priority: 1,
    isCardio: true,
  },
  {
    id: "shoulder-shimmy",
    name: "Shoulder shimmy",
    pattern: "isolation",
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Shoulders, not the neck. Small range. Stop if you get dizzy. Jaw unclenched. This is a chorus on your feet.",
    substitutes: ["chest-isolation", "port-de-bras"],
    restSeconds: 20,
    priority: 3,
  },
  {
    id: "standing-grind",
    name: "Standing grind (chair back)",
    pattern: "mobility",
    primaryMuscles: ["glutes", "obliques"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Hands light on a sturdy chair back or pole. Hips circle or figure-8 with air between you and the furniture. Not a lumbar crank. Chair is a stand-in, not a person.",
    substitutes: ["hip-figure-8", "seated-hip-isolation"],
    restSeconds: 30,
    priority: 1,
    avoidIf: ["low_back"],
  },
  {
    id: "cat-crawl",
    name: "Cat crawl",
    pattern: "cardio",
    primaryMuscles: ["abs", "glutes", "front_delts"],
    secondaryMuscles: ["quads"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Pads. Opposite hand and knee. Fists or forearms if wrists complain. Eyes on a rail mark. Slow.",
    substitutes: ["tabletop-pose", "knee-walk-circle"],
    restSeconds: 40,
    priority: 2,
    isCardio: true,
    avoidIf: ["wrist", "knee"],
  },
  {
    id: "mermaid-sit",
    name: "Mermaid / hip sit",
    pattern: "mobility",
    primaryMuscles: ["glutes", "hip_flexors"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "From kneeling, sit the hips beside the heels. Both sides, equal time. Skip if the knee or hip barks. Not a pancake contest.",
    substitutes: ["tabletop-pose", "hip-90-90"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["knee", "hip"],
  },
  {
    id: "level-ladder",
    name: "Level ladder (stand–kneel–sit–up)",
    pattern: "mobility",
    primaryMuscles: ["quads", "abs", "glutes"],
    secondaryMuscles: ["calves"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Pad the knees. Use a hand. No dropping. Reverse is as slow as the descent. Optional back-lying with no neck bridge.",
    substitutes: ["floor-descent", "tabletop-pose"],
    restSeconds: 45,
    priority: 1,
    avoidIf: ["knee"],
  },
  {
    id: "floor-grind",
    name: "Floor hip work",
    pattern: "mobility",
    primaryMuscles: ["glutes", "abs"],
    secondaryMuscles: ["hip_flexors"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Tabletop or forearms on pads. Circle or pulse the hips. Neck stays free — no bridges. Contact-free; the floor is the partner.",
    substitutes: ["floor-body-roll", "hip-pulse"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["wrist", "knee", "low_back"],
  },
  {
    id: "reverse-chair-sit",
    name: "Reverse chair sit",
    pattern: "mobility",
    primaryMuscles: ["glutes", "abs"],
    secondaryMuscles: ["quads"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Sturdy chair. Sit facing away, tall back, small hip circle. Stand without yanking the knees. Furniture, not a person.",
    substitutes: ["chair-approach-straddle", "seated-hip-isolation"],
    restSeconds: 40,
    priority: 1,
    avoidIf: ["knee"],
  },
  {
    id: "lap-phrase",
    name: "Three-part chair set",
    pattern: "cardio",
    primaryMuscles: ["glutes", "abs"],
    secondaryMuscles: ["quads"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Approach, seated body, close — on a sturdy chair at home. Not on a person. House rules and consent apply in a club. No new tricks in the middle.",
    substitutes: ["chair-approach-straddle", "eight-count-phrase"],
    restSeconds: 50,
    priority: 1,
    isCardio: true,
  },
  {
    id: "skirt-work",
    name: "Skirt / dress work",
    pattern: "mobility",
    primaryMuscles: ["glutes", "obliques"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Practice in the real garment. Hips move the cloth. If the hem trips you, simplify it. No neck-loaded floor tricks while dressing.",
    substitutes: ["hip-figure-8", "layer-change-flow"],
    restSeconds: 30,
    priority: 2,
  },
  {
    id: "top-peel",
    name: "Top layer peel",
    pattern: "mobility",
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "One layer on a counted 8. Stay on your feet or kneeling. Place the garment on purpose. Adult, unhurried. No new tricks during the peel.",
    substitutes: ["layer-change-flow", "port-de-bras"],
    restSeconds: 30,
    priority: 2,
  },
  {
    id: "heel-floor",
    name: "Heels on the floor (keep or counted take-off)",
    pattern: "mobility",
    primaryMuscles: ["quads", "calves"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Decide before you descend: keep the heels on pads, or take them off on an 8 and park them upstage. Ankle twist is a stop.",
    substitutes: ["floor-descent", "heel-walk"],
    restSeconds: 40,
    priority: 2,
    avoidIf: ["ankle", "knee"],
  },
  {
    id: "rail-approach",
    name: "Rail approach",
    pattern: "cardio",
    primaryMuscles: ["glutes", "calves"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Walk to a tape line, pause, open palm, leave. Wall is the audience. Do not grab a person. House rules override this in a club.",
    substitutes: ["performance-walk", "money-hands"],
    restSeconds: 30,
    priority: 1,
    isCardio: true,
  },
  {
    id: "two-song-map",
    name: "Two-song club map",
    pattern: "cardio",
    primaryMuscles: ["glutes", "abs", "calves"],
    secondaryMuscles: ["grip"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Song one: arrive, box, optional layer. Rest. Song two: chair or floor, one owned pole skill, close. No new inverts. Only skills you already own.",
    substitutes: ["show-set-run", "eight-count-phrase"],
    restSeconds: 90,
    priority: 1,
    isCardio: true,
  },
  {
    id: "closing-exit",
    name: "Closing walk-off",
    pattern: "cardio",
    primaryMuscles: ["glutes", "calves"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Still, look, pose, walk off on the same slow tempo. No new tricks because the song has bars left. Do not jog.",
    substitutes: ["performance-walk", "eight-count-phrase"],
    restSeconds: 30,
    priority: 1,
    isCardio: true,
  },
  {
    id: "slip-recovery",
    name: "Slip recovery",
    pattern: "mobility",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Practice a fake miss — freeze, two counts, walk, continue the map. If you actually slip, check the ankle and wrist. Pain is a stop.",
    substitutes: ["performance-walk", "closing-exit"],
    restSeconds: 30,
    priority: 3,
  },
];
