import type { Exercise } from "@/lib/types";
import { EXOTIC_EXERCISES } from "./exotic";

/** Pole, yoga, stretch, barre, ballet, and rucking movements. */
export const MOVEMENT_EXERCISES: Exercise[] = [
  {
    id: "performance-walk",
    name: "Performance walk and pose",
    pattern: "cardio",
    primaryMuscles: ["glutes", "calves"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Slow, even steps. Ribs stacked over pelvis. Pause in a pose you can hold without collapsing the low back. Trainers first; heels are optional later and skip them if the ankle rolls.",
    substitutes: ["waltz-walk", "zone2-walk"],
    restSeconds: 30,
    priority: 1,
    isCardio: true,
  },
  {
    id: "body-wave",
    name: "Standing body wave",
    pattern: "mobility",
    primaryMuscles: ["abs", "spinal_erectors"],
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Move the wave through knees, hips, and thoracic spine — not a dumped lumbar hinge. Small range if the back is cranky.",
    substitutes: ["cat-cow-flow", "thoracic-opener"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "floor-body-roll",
    name: "Floor body roll / hip circle",
    pattern: "mobility",
    primaryMuscles: ["glutes", "hip_flexors"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Pad the knees. Keep wrists stacked under shoulders or drop to forearms. No neck-loaded bridges.",
    substitutes: ["body-wave", "hip-90-90"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["wrist", "knee"],
  },
  {
    id: "pole-walk",
    name: "Around-the-pole walk",
    pattern: "cardio",
    primaryMuscles: ["grip", "lats"],
    secondaryMuscles: ["obliques"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Inside hand high, outside hand at chest. Walk a full circle both directions. Shoulders active, not shrugged into the ears. Studio or home pole required.",
    substitutes: ["performance-walk", "dead-hang"],
    restSeconds: 45,
    priority: 1,
    isCardio: true,
  },
  {
    id: "pole-squat-hold",
    name: "Pole squat hold (active hang from standing)",
    pattern: "vertical_pull",
    primaryMuscles: ["lats", "grip"],
    secondaryMuscles: ["abs", "quads"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Sit the hips back, keep the pole in front, pull the elbows down. This is invert-prep without leaving the floor. Stop if the shoulder pinches.",
    substitutes: ["inverted-row", "dead-hang"],
    restSeconds: 60,
    priority: 1,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "fireman-spin",
    name: "Fireman spin",
    pattern: "core",
    primaryMuscles: ["grip", "obliques", "adductors"],
    secondaryMuscles: ["lats", "abs"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Inside arm high, outside arm at chest. Contact the pole at the knees, not the ankle. Equal sets both sides — one-sided volume is an injury pattern in pole research. Spot the landing.",
    substitutes: ["chair-spin", "pole-walk"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["wrist", "knee"],
  },
  {
    id: "chair-spin",
    name: "Chair / hook spin",
    pattern: "core",
    primaryMuscles: ["grip", "adductors", "abs"],
    secondaryMuscles: ["obliques"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Front-hook and back-hook both count. Keep the hooked knee at mid-thigh, not jammed in the joint. Both sides. Static pole first; spin pole only after the static version is quiet.",
    substitutes: ["fireman-spin", "pole-sit"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["knee", "wrist"],
  },
  {
    id: "pole-sit",
    name: "Basic pole sit",
    pattern: "core",
    primaryMuscles: ["adductors", "abs", "grip"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Squeeze the pole with the thighs, lean back slightly, hands can hover when you own it. Learn from a climb or from the floor with a crash mat. Do not drop from height to 'find' the sit.",
    substitutes: ["pole-squat-hold", "hollow-hold"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["wrist"],
  },
  {
    id: "basic-climb",
    name: "Basic climb",
    pattern: "vertical_pull",
    primaryMuscles: ["lats", "grip", "abs"],
    secondaryMuscles: ["adductors", "biceps"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Knee clamp, then stand, then reach. Three climbs off the floor is a common class milestone — quality over height. Climb down; do not slide. Crash mat. Both sides if your studio uses a dominant-side climb.",
    substitutes: ["pole-squat-hold", "pullup"],
    restSeconds: 90,
    priority: 1,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "outside-leg-hang",
    name: "Outside-leg hang (low)",
    pattern: "core",
    primaryMuscles: ["grip", "adductors", "obliques"],
    secondaryMuscles: ["abs", "lats"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Low. Crash mat. Outside thigh on the pole, hips stacked. Both sides. This is not a full invert. Climb down. Skip if the shoulder pinches.",
    substitutes: ["pole-sit", "dead-hang"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "carousel-spin",
    name: "Carousel / crucifix-prep spin",
    pattern: "core",
    primaryMuscles: ["grip", "lats", "abs"],
    secondaryMuscles: ["obliques"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Static pole first. Hands at chest and hip, hips around the pole, both sides. Crash mat. Not a handspring. No kip.",
    substitutes: ["fireman-spin", "pole-walk"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "climb-to-sit",
    name: "Climb to sit",
    pattern: "vertical_pull",
    primaryMuscles: ["lats", "adductors", "grip"],
    secondaryMuscles: ["abs"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "One climb, then a sit you already own, then a controlled down. Mat. Both sides if your studio uses a dominant sit. Do not drop into the sit from height.",
    substitutes: ["basic-climb", "pole-sit"],
    restSeconds: 90,
    priority: 1,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "back-hook-spin",
    name: "Back-hook spin",
    pattern: "core",
    primaryMuscles: ["grip", "adductors", "abs"],
    secondaryMuscles: ["obliques", "hamstrings"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Hooked knee at mid-thigh behind you, not jammed in the joint. Both sides. Static pole first. Distinct from the front hook / chair spin.",
    substitutes: ["chair-spin", "fireman-spin"],
    restSeconds: 75,
    priority: 1,
    avoidIf: ["knee", "wrist"],
  },
  {
    id: "pole-tuck-prep",
    name: "On-pole tuck / invert prep",
    pattern: "core",
    primaryMuscles: ["abs", "lats", "grip"],
    secondaryMuscles: ["hip_flexors"],
    equipment: ["pole", "bodyweight"],
    safety: "caution",
    safetyNote:
      "Knees to chest, posterior tilt, hips stay behind the pole. This is invert-readiness, not a handspring. No kip. Studio spotting until you can hold a hanging tuck on a bar for 10s. Skip if the shoulder or neck complains.",
    substitutes: ["hanging-tuck", "hollow-hold"],
    restSeconds: 90,
    priority: 2,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "show-set-run",
    name: "2–3 minute show run-through",
    pattern: "cardio",
    primaryMuscles: ["grip", "abs", "glutes"],
    secondaryMuscles: ["lats", "calves"],
    equipment: ["pole", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "One song-length set of skills you already own: walk, one spin, sit or climb, floor phrase, walk off. No new tricks in the run-through. Rest a full song between attempts.",
    substitutes: ["stage-circuit", "performance-walk"],
    restSeconds: 120,
    priority: 1,
    isCardio: true,
  },
  {
    id: "layer-change-flow",
    name: "Layer-change transition",
    pattern: "mobility",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Practice taking one easy layer off between phrases without rushing or rounding the spine. This is set craft, not a costume tutorial. Stay on your feet or kneeling — no neck-loaded floor tricks.",
    substitutes: ["performance-walk", "body-wave"],
    restSeconds: 30,
    priority: 3,
  },

  {
    id: "cat-cow-flow",
    name: "Cat-cow + thread-the-needle",
    pattern: "mobility",
    primaryMuscles: ["upper_back"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Move segment by segment. If wrists bark, make fists or drop to forearms. Do not crank the neck.",
    substitutes: ["thoracic-opener"],
    restSeconds: 20,
    priority: 5,
    avoidIf: ["wrist"],
  },
  {
    id: "down-dog",
    name: "Downward dog (or wall dog)",
    pattern: "mobility",
    primaryMuscles: ["hamstrings", "calves"],
    secondaryMuscles: ["front_delts"],
    equipment: ["bodyweight"],
    safety: "caution",
    safetyNote:
      "Bend the knees so the spine stays long. Palms root; no dumped shoulders. Wall dog (hands on a wall, hips back) if the wrists or shoulders complain.",
    substitutes: ["half-kneeling-hamstring", "cat-cow-flow"],
    restSeconds: 30,
    priority: 3,
    avoidIf: ["wrist", "shoulder"],
  },
  {
    id: "chair-pose",
    name: "Chair pose (utkatasana)",
    pattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Knees track toes. Sit the hips back. Arms reach without shrugging.",
    substitutes: ["goblet-squat", "bodyweight-squat"],
    restSeconds: 45,
    priority: 2,
    avoidIf: ["knee"],
  },
  {
    id: "warrior-2",
    name: "Warrior II + reverse warrior",
    pattern: "lunge",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["adductors"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Front knee tracks the second toe. Shorten the stance if the hip or knee collapses. Both sides.",
    substitutes: ["walking-lunge", "bulgarian-split-squat"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["knee"],
  },
  {
    id: "bird-dog",
    name: "Bird dog",
    pattern: "core",
    primaryMuscles: ["abs", "glutes"],
    secondaryMuscles: ["spinal_erectors"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Reach long, do not arch. Pause. Switch sides. A safer 'core line' drill than sit-up spam.",
    substitutes: ["dead-bug", "plank"],
    restSeconds: 30,
    priority: 3,
  },
  {
    id: "legs-up-wall",
    name: "Legs-up-the-wall",
    pattern: "mobility",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Hips close to the wall, knees soft if the hamstrings yell. This is restore, not a split PR. Get up slowly.",
    substitutes: ["supported-child", "half-kneeling-hamstring"],
    restSeconds: 20,
    priority: 5,
  },
  {
    id: "supported-child",
    name: "Supported child's pose",
    pattern: "mobility",
    primaryMuscles: ["hip_flexors"],
    secondaryMuscles: ["lats"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Knees wide, big toes together, hips toward heels. Rest the torso on a pillow if the knees or back complain. No forcing.",
    substitutes: ["legs-up-wall", "cat-cow-flow"],
    restSeconds: 20,
    priority: 5,
    avoidIf: ["knee"],
  },

  {
    id: "half-kneeling-hamstring",
    name: "Half-kneeling hinge hamstring stretch",
    pattern: "mobility",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Hinge at the hip with a long spine. The stretch is in the back of the thigh, not a rounded lumbar 'reach for the toes.' 30–45s, 2–4 rounds. No bounce.",
    substitutes: ["legs-up-wall", "rdl"],
    restSeconds: 20,
    priority: 3,
    avoidIf: ["low_back"],
  },
  {
    id: "couch-stretch",
    name: "Couch / hip-flexor stretch",
    pattern: "mobility",
    primaryMuscles: ["hip_flexors"],
    secondaryMuscles: ["quads"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Posterior tilt so you stretch the hip, not crank the lumbar spine into extension. Pad the back knee. Both sides.",
    substitutes: ["hip-90-90", "lunge-hip-flexor"],
    restSeconds: 20,
    priority: 3,
    avoidIf: ["knee"],
  },
  {
    id: "lunge-hip-flexor",
    name: "Half-kneeling hip-flexor with glute squeeze",
    pattern: "mobility",
    primaryMuscles: ["hip_flexors", "glutes"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Squeeze the rear glute, tuck slightly, stay tall. If the front of the hip is pinchy, shorten the stance.",
    substitutes: ["couch-stretch", "hip-90-90"],
    restSeconds: 20,
    priority: 3,
  },
  {
    id: "adductor-rock",
    name: "Adductor rock-back (kneeling)",
    pattern: "mobility",
    primaryMuscles: ["adductors"],
    secondaryMuscles: ["hip_flexors"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "One leg out to the side, knee of the other on a pad. Rock back with a flat back. Do not dump into a painful groin. Useful split-prep without forcing a pancake.",
    substitutes: ["hip-90-90"],
    restSeconds: 20,
    priority: 3,
    avoidIf: ["knee", "hip"],
  },
  {
    id: "pancake-block",
    name: "Seated pancake with blocks",
    pattern: "mobility",
    primaryMuscles: ["adductors", "hamstrings"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "caution",
    safetyNote:
      "Sit on a folded towel. Hinge from the hips. Hands on blocks. Sharp inner-thigh or nerve zings = back off. This is not a middle-split contest.",
    substitutes: ["adductor-rock", "hip-90-90"],
    restSeconds: 20,
    priority: 4,
    avoidIf: ["low_back", "hip"],
  },
  {
    id: "doorway-pec",
    name: "Doorway pec + gentle sleeper",
    pattern: "mobility",
    primaryMuscles: ["chest", "rear_delts"],
    secondaryMuscles: ["rotator_cuff"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Elbow at or below shoulder height in the doorway. No behind-the-neck stretches. Sleeper stretch stays gentle — pole shoulders already live in internal rotation.",
    substitutes: ["shoulder-cares", "face-pull"],
    restSeconds: 20,
    priority: 4,
    avoidIf: ["shoulder"],
  },
  {
    id: "calf-wall",
    name: "Wall calf stretch (knee bent and straight)",
    pattern: "mobility",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Straight-knee for gastroc, bent-knee for soleus. Heel stays down. 30–45s. Needed for relevé, heels, and rucking.",
    substitutes: ["short-foot"],
    restSeconds: 20,
    priority: 4,
  },
  {
    id: "short-foot",
    name: "Short foot + toe-spread",
    pattern: "mobility",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Shorten the arch without curling the toes into a claw. Then spread the toes. Quiet feet before heels, ballet, or a ruck.",
    substitutes: ["calf-wall"],
    restSeconds: 15,
    priority: 5,
  },

  {
    id: "plie-first",
    name: "Plié in parallel and small turnout",
    pattern: "squat",
    primaryMuscles: ["quads", "glutes", "adductors"],
    secondaryMuscles: ["calves"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Turnout comes from the hip, not the feet. Knees track toes. Start near 45°, not 180°. Heels stay down as long as you control them. IADMS: do not force the feet and pronate to fake turnout.",
    substitutes: ["goblet-squat", "chair-pose"],
    restSeconds: 45,
    priority: 1,
    avoidIf: ["knee"],
  },
  {
    id: "barre-pulse",
    name: "Barre pulse (small range)",
    pattern: "isolation",
    primaryMuscles: ["glutes", "quads"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Tiny range you can keep aligned. If the knee caves or the low back grips, stand taller and pulse less. A chair back is a barre.",
    substitutes: ["plie-first", "glute-bridge"],
    restSeconds: 30,
    priority: 2,
    avoidIf: ["knee"],
  },
  {
    id: "releve-calf",
    name: "Relevé / calf raise at the barre",
    pattern: "isolation",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Rise through the first and second toes, not sickling to the pinky. Soften the knees slightly at the top if you lock and wobble.",
    substitutes: ["calf-wall", "short-foot"],
    restSeconds: 45,
    priority: 2,
  },
  {
    id: "attitude-lift",
    name: "Standing attitude / arabesque tap",
    pattern: "isolation",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Square the pelvis. Lift the back leg only as high as the hips stay level. This is balance and line, not a circus arabesque.",
    substitutes: ["single-leg-rdl", "bird-dog"],
    restSeconds: 45,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "port-de-bras",
    name: "Port de bras (arm pathways)",
    pattern: "mobility",
    primaryMuscles: ["side_delts", "upper_back"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Move the arms without shrugging or flaring the ribs. Soft elbows. Useful for stage and amateur-night posing.",
    substitutes: ["shoulder-cares"],
    restSeconds: 20,
    priority: 4,
  },
  {
    id: "tendu-box",
    name: "Tendu front, side, back",
    pattern: "mobility",
    primaryMuscles: ["adductors", "calves"],
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Slide to a pointed foot, hip stays over the standing leg. No rolling the standing arch. Both sides. Chair for balance.",
    substitutes: ["plie-first", "short-foot"],
    restSeconds: 20,
    priority: 2,
  },
  {
    id: "passe-balance",
    name: "Passé balance",
    pattern: "core",
    primaryMuscles: ["abs", "glutes", "calves"],
    secondaryMuscles: ["adductors"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Toe at the standing knee, not jammed into the joint. Eyes on a still spot. Hold, then switch. Wall nearby.",
    substitutes: ["attitude-lift", "single-leg-rdl"],
    restSeconds: 30,
    priority: 2,
  },
  {
    id: "waltz-walk",
    name: "Slow waltz / weight-transfer walk",
    pattern: "cardio",
    primaryMuscles: ["glutes", "calves"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote:
      "Roll through the foot, pick up the pelvis as one piece. This is the 'smooth movement' transfer to stage walking. No rushing.",
    substitutes: ["performance-walk", "zone2-walk"],
    restSeconds: 20,
    priority: 2,
    isCardio: true,
  },

  {
    id: "ruck-walk",
    name: "Ruck walk",
    pattern: "cardio",
    primaryMuscles: ["glutes", "quads", "calves"],
    secondaryMuscles: ["spinal_erectors", "abs"],
    equipment: ["backpack", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Start ~10–15% bodyweight (or 10–20 lb if you have no scale). Pack high and close to the back. Tall posture, not a forward crumple. Conversational pace. Do not add load and distance in the same week. Stay under ~30% bodyweight for general fitness (Knapik load-carriage injury data).",
    substitutes: ["zone2-walk", "easy-incline-walk"],
    restSeconds: 0,
    priority: 1,
    isCardio: true,
  },
  {
    id: "ruck-hills",
    name: "Easy hill or stair ruck",
    pattern: "cardio",
    primaryMuscles: ["glutes", "calves", "quads"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["backpack", "bodyweight"],
    safety: "recommended",
    safetyNote:
      "Same or lighter pack than your flat ruck. Shorten the stride uphill. Walk down — do not pound. Skip if the knees or Achilles are angry.",
    substitutes: ["ruck-walk", "easy-incline-walk"],
    restSeconds: 0,
    priority: 1,
    isCardio: true,
    avoidIf: ["knee"],
  },
  {
    id: "bodyweight-squat",
    name: "Bodyweight squat",
    pattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Sit back, knees track toes. Use a chair to tap if depth is noisy.",
    substitutes: ["goblet-squat", "chair-pose"],
    restSeconds: 60,
    priority: 2,
    avoidIf: ["knee"],
  },
  ...EXOTIC_EXERCISES,
];
