import type { Exercise } from "@/lib/types";
import { MOVEMENT_EXERCISES } from "./movement";

const CORE_EXERCISES: Exercise[] = [
  // --- Banned (kept so the app can explain why they never appear) ---
  {
    id: "bench-dip",
    name: "Bench / chair triceps dip",
    pattern: "isolation",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["front_delts", "chest"],
    equipment: ["bench", "bodyweight"],
    safety: "banned",
    safetyNote:
      "Forces the shoulder into loaded end-range extension and internal rotation. McKenzie et al. 2022 found bench dips take the humerus past self-selected max extension and should not be used in regular training or rehab. Use cable pushdowns, close-grip bench, or narrow push-ups instead.",
    substitutes: ["cable-pushdown", "close-grip-bench", "narrow-pushup", "overhead-cable-extension"],
    restSeconds: 60,
    priority: 5,
    avoidIf: ["shoulder"],
  },
  {
    id: "parallel-bar-dip",
    name: "Parallel-bar dip",
    pattern: "horizontal_push",
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_delts"],
    equipment: ["bodyweight"],
    safety: "banned",
    safetyNote:
      "Even on bars, a deep dip loads the shoulder in extension. This household app does not prescribe bar dips. Use cable pushdowns, close-grip bench, or narrow push-ups instead.",
    substitutes: ["cable-pushdown", "close-grip-bench", "narrow-pushup", "overhead-cable-extension"],
    restSeconds: 90,
    priority: 5,
    avoidIf: ["shoulder"],
  },
  {
    id: "behind-neck-press",
    name: "Behind-the-neck press",
    pattern: "vertical_push",
    primaryMuscles: ["front_delts", "side_delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["barbell"],
    safety: "banned",
    safetyNote:
      "Requires extreme abduction plus external rotation (the high-five position). Compresses the rotator cuff against the acromion for most lifters. Press in front of the face instead.",
    substitutes: ["ohp", "db-shoulder-press", "landmine-press"],
    restSeconds: 120,
    priority: 5,
    avoidIf: ["shoulder"],
  },
  {
    id: "behind-neck-pulldown",
    name: "Behind-the-neck pulldown",
    pattern: "vertical_pull",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
    safety: "banned",
    safetyNote: "Same high-five shoulder position as behind-the-neck pressing. Pull to the upper chest instead.",
    substitutes: ["lat-pulldown", "pullup", "chest-supported-row"],
    restSeconds: 90,
    priority: 5,
    avoidIf: ["shoulder"],
  },
  {
    id: "upright-row-chin",
    name: "Upright row to the chin",
    pattern: "isolation",
    primaryMuscles: ["side_delts", "traps"],
    secondaryMuscles: ["biceps"],
    equipment: ["barbell"],
    safety: "banned",
    safetyNote:
      "Internal rotation plus elevation is the Hawkins-Kennedy impingement position. Stop below 90° of elbow height or use cable laterals and face pulls.",
    substitutes: ["cable-lateral-raise", "db-lateral-raise", "face-pull"],
    restSeconds: 60,
    priority: 5,
    avoidIf: ["shoulder"],
  },
  {
    id: "kipping-pullup",
    name: "Kipping pull-up",
    pattern: "vertical_pull",
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["abs"],
    equipment: ["pullup_bar"],
    safety: "banned",
    safetyNote:
      "High-speed traction on the shoulder labrum without a strict pulling base. Pole and stage prep uses strict or assisted pulling only.",
    substitutes: ["pullup", "assisted-pullup", "lat-pulldown"],
    restSeconds: 90,
    priority: 5,
    avoidIf: ["shoulder"],
  },

  // --- Lower body ---
  {
    id: "back-squat",
    name: "Back squat",
    pattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["adductors", "spinal_erectors"],
    equipment: ["barbell"],
    safety: "recommended",
    safetyNote: "Brace the trunk. Depth to a comfortable, repeatable position. High-bar or low-bar both grow glutes similarly to hip thrusts (Plotkin 2023).",
    substitutes: ["goblet-squat", "leg-press", "front-squat", "belt-squat"],
    restSeconds: 180,
    priority: 1,
    avoidIf: ["knee", "low_back"],
  },
  {
    id: "front-squat",
    name: "Front squat",
    pattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["abs", "upper_back"],
    equipment: ["barbell"],
    safety: "recommended",
    safetyNote: "More upright torso, often kinder to the low back than a heavy low-bar squat.",
    substitutes: ["goblet-squat", "back-squat", "leg-press"],
    restSeconds: 180,
    priority: 1,
    avoidIf: ["wrist", "knee"],
  },
  {
    id: "pause-squat",
    name: "Pause squat (2-count)",
    pattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["adductors"],
    equipment: ["barbell"],
    safety: "recommended",
    safetyNote: "Pause just above parallel. Builds positional strength without extra spinal load from good mornings.",
    substitutes: ["box-squat", "back-squat"],
    restSeconds: 180,
    priority: 1,
    avoidIf: ["knee", "low_back"],
  },
  {
    id: "box-squat",
    name: "Box squat",
    pattern: "squat",
    primaryMuscles: ["glutes", "quads"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "bench"],
    safety: "recommended",
    safetyNote: "Sit back to a box at or slightly above parallel. Control the descent; do not crash.",
    substitutes: ["pause-squat", "back-squat"],
    restSeconds: 180,
    priority: 1,
    avoidIf: ["low_back"],
  },
  {
    id: "goblet-squat",
    name: "Goblet squat",
    pattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["abs"],
    equipment: ["dumbbell", "kettlebell"],
    safety: "recommended",
    safetyNote: "Excellent teaching squat and home-gym main lift.",
    substitutes: ["back-squat", "leg-press"],
    restSeconds: 120,
    priority: 1,
  },
  {
    id: "leg-press",
    name: "Leg press (45°)",
    pattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["adductors"],
    equipment: ["machine"],
    safety: "recommended",
    safetyNote: "Do not let the pelvis tuck at the bottom. High glute and quad stimulus without axial loading.",
    substitutes: ["goblet-squat", "back-squat"],
    restSeconds: 150,
    priority: 2,
    avoidIf: ["knee"],
  },
  {
    id: "belt-squat",
    name: "Belt squat",
    pattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["adductors"],
    equipment: ["machine"],
    safety: "recommended",
    safetyNote: "Useful when the low back needs a break from barbell squats.",
    substitutes: ["leg-press", "goblet-squat"],
    restSeconds: 150,
    priority: 2,
    avoidIf: ["hip"],
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian split squat",
    pattern: "lunge",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["adductors"],
    equipment: ["dumbbell", "bench"],
    safety: "recommended",
    safetyNote: "Long stride biases glutes; shorter stride biases quads. Use a pad under the back knee if needed.",
    substitutes: ["walking-lunge", "step-up", "leg-press"],
    restSeconds: 120,
    priority: 2,
    avoidIf: ["knee"],
  },
  {
    id: "walking-lunge",
    name: "Walking lunge",
    pattern: "lunge",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["adductors"],
    equipment: ["dumbbell"],
    safety: "recommended",
    safetyNote: "Control the knee over the mid-foot. Step long enough to feel the glute.",
    substitutes: ["bulgarian-split-squat", "step-up"],
    restSeconds: 90,
    priority: 3,
    avoidIf: ["knee"],
  },
  {
    id: "step-up",
    name: "Weighted step-up",
    pattern: "lunge",
    primaryMuscles: ["glutes", "quads"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbell", "bench"],
    safety: "recommended",
    safetyNote: "Drive through the whole foot on the box. Do not push off the trailing leg.",
    substitutes: ["bulgarian-split-squat", "walking-lunge"],
    restSeconds: 90,
    priority: 3,
    avoidIf: ["knee"],
  },
  {
    id: "rdl",
    name: "Romanian deadlift",
    pattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["spinal_erectors"],
    equipment: ["barbell"],
    safety: "recommended",
    safetyNote: "Soft knees, hip hinge, bar close to legs. Stop when the hamstrings run out of range — do not chase the floor.",
    substitutes: ["db-rdl", "single-leg-rdl", "leg-curl"],
    restSeconds: 150,
    priority: 1,
    avoidIf: ["low_back"],
  },
  {
    id: "db-rdl",
    name: "Dumbbell Romanian deadlift",
    pattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["spinal_erectors"],
    equipment: ["dumbbell"],
    safety: "recommended",
    safetyNote: "Same hinge pattern with easier load jumps.",
    substitutes: ["rdl", "single-leg-rdl"],
    restSeconds: 120,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "single-leg-rdl",
    name: "Single-leg RDL",
    pattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["spinal_erectors"],
    equipment: ["dumbbell"],
    safety: "recommended",
    safetyNote: "Hold a wall for balance if needed. Hip square to the floor.",
    substitutes: ["db-rdl", "rdl"],
    restSeconds: 90,
    priority: 3,
    avoidIf: ["low_back"],
  },
  {
    id: "conventional-deadlift",
    name: "Conventional deadlift",
    pattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes", "spinal_erectors"],
    secondaryMuscles: ["upper_back", "forearms", "traps"],
    equipment: ["barbell"],
    safety: "caution",
    safetyNote:
      "Highly specific for powerlifting. High axial load — use a trap bar or RDL if the low back is irritable. Neutral spine, lats on, no bounce.",
    substitutes: ["trap-bar-deadlift", "rdl", "block-pull"],
    restSeconds: 210,
    priority: 1,
    avoidIf: ["low_back"],
  },
  {
    id: "trap-bar-deadlift",
    name: "Trap-bar deadlift",
    pattern: "hinge",
    primaryMuscles: ["glutes", "quads", "hamstrings"],
    secondaryMuscles: ["upper_back", "traps"],
    equipment: ["trap_bar"],
    safety: "recommended",
    safetyNote: "More knee flexion than a conventional pull and usually easier on the spine. High handles if mobility is limited.",
    substitutes: ["rdl", "conventional-deadlift", "leg-press"],
    restSeconds: 180,
    priority: 1,
    avoidIf: ["low_back"],
  },
  {
    id: "block-pull",
    name: "Block pull / rack pull (knee height)",
    pattern: "hinge",
    primaryMuscles: ["glutes", "spinal_erectors"],
    secondaryMuscles: ["hamstrings", "upper_back"],
    equipment: ["barbell"],
    safety: "caution",
    safetyNote: "Use as a max-effort variation, not a weekly ego lift. Keep the bar over mid-foot.",
    substitutes: ["trap-bar-deadlift", "rdl"],
    restSeconds: 180,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "paused-deadlift",
    name: "Paused deadlift (just off floor)",
    pattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes", "spinal_erectors"],
    secondaryMuscles: ["upper_back"],
    equipment: ["barbell"],
    safety: "caution",
    safetyNote: "Pause 1–2 seconds below the knee. Teaches tightness without max-effort good mornings.",
    substitutes: ["conventional-deadlift", "rdl"],
    restSeconds: 180,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "hip-thrust",
    name: "Barbell hip thrust",
    pattern: "thrust",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "hip_thrust_bench"],
    safety: "recommended",
    safetyNote:
      "Chin tucked, ribs down, drive through the heels. Pause at lockout. Similar glute growth to squats (Plotkin 2023); adding thrusts on top of hinges and presses grew glutes more in untrained women (Kassiano 2024).",
    substitutes: ["db-hip-thrust", "glute-bridge", "45-back-extension"],
    restSeconds: 150,
    priority: 1,
    avoidIf: ["hip"],
  },
  {
    id: "db-hip-thrust",
    name: "Dumbbell hip thrust / glute bridge",
    pattern: "thrust",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["dumbbell", "bench"],
    safety: "recommended",
    safetyNote: "Same pattern with a dumbbell or plate on the hips.",
    substitutes: ["hip-thrust", "glute-bridge"],
    restSeconds: 90,
    priority: 2,
  },
  {
    id: "glute-bridge",
    name: "Single-leg glute bridge",
    pattern: "thrust",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Great warm-up and home-gym finisher. Posterior pelvic tilt at the top.",
    substitutes: ["db-hip-thrust", "hip-thrust"],
    restSeconds: 60,
    priority: 4,
  },
  {
    id: "cable-kickback",
    name: "Cable glute kickback",
    pattern: "isolation",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: ["cable"],
    safety: "recommended",
    safetyNote: "Keep the pelvis square. Isolation, not a main lift.",
    substitutes: ["glute-bridge", "hip-abduction"],
    restSeconds: 60,
    priority: 5,
  },
  {
    id: "hip-abduction",
    name: "Seated or standing hip abduction",
    pattern: "isolation",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: ["machine", "bands"],
    safety: "recommended",
    safetyNote: "Upper glute (medius/minimus) work. Lean slightly forward on the seated machine to bias glute max upper fibers.",
    substitutes: ["cable-kickback", "lateral-band-walk"],
    restSeconds: 60,
    priority: 4,
  },
  {
    id: "lateral-band-walk",
    name: "Lateral band walk",
    pattern: "isolation",
    primaryMuscles: ["glutes"],
    secondaryMuscles: [],
    equipment: ["bands"],
    safety: "recommended",
    safetyNote: "Soft knees, toes forward, stay in a quarter squat.",
    substitutes: ["hip-abduction"],
    restSeconds: 45,
    priority: 5,
  },
  {
    id: "45-back-extension",
    name: "45° back extension (glute bias)",
    pattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["spinal_erectors"],
    equipment: ["machine"],
    safety: "recommended",
    safetyNote: "Round the upper back slightly and think 'squeeze the glutes' rather than hyperextending the lumbar spine.",
    substitutes: ["rdl", "glute-bridge"],
    restSeconds: 75,
    priority: 3,
    avoidIf: ["low_back"],
  },
  {
    id: "leg-curl",
    name: "Lying or seated leg curl",
    pattern: "isolation",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    equipment: ["machine"],
    safety: "recommended",
    safetyNote: "Full knee flexion. Control the eccentric.",
    substitutes: ["rdl", "single-leg-rdl"],
    restSeconds: 75,
    priority: 3,
  },
  {
    id: "leg-extension",
    name: "Leg extension",
    pattern: "isolation",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: ["machine"],
    safety: "recommended",
    safetyNote: "Stop if the front of the knee complains. Useful for quad volume without more axial load.",
    substitutes: ["goblet-squat", "bulgarian-split-squat"],
    restSeconds: 75,
    priority: 4,
    avoidIf: ["knee"],
  },
  {
    id: "calf-raise",
    name: "Standing calf raise",
    pattern: "isolation",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    equipment: ["machine", "dumbbell"],
    safety: "recommended",
    safetyNote: "Full stretch and pause at the top.",
    substitutes: [],
    restSeconds: 60,
    priority: 5,
  },

  // --- Upper push ---
  {
    id: "bench-press",
    name: "Barbell bench press",
    pattern: "horizontal_push",
    primaryMuscles: ["chest", "front_delts", "triceps"],
    secondaryMuscles: ["upper_back"],
    equipment: ["barbell", "bench"],
    safety: "recommended",
    safetyNote: "Feet down, slight arch, bar to lower chest, elbows ~45–70°. Scapulae set. Not a behind-the-neck movement.",
    substitutes: ["db-bench", "pushup", "machine-chest-press"],
    restSeconds: 180,
    priority: 1,
    avoidIf: ["shoulder"],
  },
  {
    id: "pause-bench",
    name: "Paused bench press",
    pattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps", "front_delts"],
    secondaryMuscles: [],
    equipment: ["barbell", "bench"],
    safety: "recommended",
    safetyNote: "Dead pause on the chest without relaxing the upper back.",
    substitutes: ["bench-press", "close-grip-bench"],
    restSeconds: 180,
    priority: 1,
    avoidIf: ["shoulder"],
  },
  {
    id: "close-grip-bench",
    name: "Close-grip bench press",
    pattern: "horizontal_push",
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["front_delts"],
    equipment: ["barbell", "bench"],
    safety: "recommended",
    safetyNote: "Grip just inside shoulder width — not a suicide grip stacked together. Safer triceps loader than bench dips.",
    substitutes: ["cable-pushdown", "jm-press", "narrow-pushup"],
    restSeconds: 150,
    priority: 2,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "db-bench",
    name: "Dumbbell bench press",
    pattern: "horizontal_push",
    primaryMuscles: ["chest", "front_delts", "triceps"],
    secondaryMuscles: [],
    equipment: ["dumbbell", "bench"],
    safety: "recommended",
    safetyNote: "Neutral-ish grip is often friendlier than a barbell for cranky shoulders.",
    substitutes: ["bench-press", "machine-chest-press", "pushup"],
    restSeconds: 120,
    priority: 2,
    avoidIf: ["shoulder"],
  },
  {
    id: "incline-db-press",
    name: "Incline dumbbell press (30°)",
    pattern: "horizontal_push",
    primaryMuscles: ["chest", "front_delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell", "bench"],
    safety: "recommended",
    safetyNote: "Keep the incline around 20–35°. Steeper benches become a shoulder press.",
    substitutes: ["db-bench", "landmine-press"],
    restSeconds: 120,
    priority: 2,
    avoidIf: ["shoulder"],
  },
  {
    id: "machine-chest-press",
    name: "Machine chest press",
    pattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["front_delts"],
    equipment: ["machine"],
    safety: "recommended",
    safetyNote: "Set handles at mid-chest. Do not overstretch the pec at the bottom if the shoulder feels unstable.",
    substitutes: ["db-bench", "pushup"],
    restSeconds: 90,
    priority: 3,
    avoidIf: ["shoulder"],
  },
  {
    id: "pushup",
    name: "Push-up",
    pattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps", "front_delts"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Body in one line. Elevate the hands to regress; add a vest or deficit to progress.",
    substitutes: ["narrow-pushup", "db-bench"],
    restSeconds: 75,
    priority: 2,
    avoidIf: ["wrist"],
  },
  {
    id: "narrow-pushup",
    name: "Narrow-grip push-up",
    pattern: "horizontal_push",
    primaryMuscles: ["triceps", "chest"],
    secondaryMuscles: ["abs"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Hands under the shoulders, elbows track along the ribs. Preferred triceps alternative to bench dips.",
    substitutes: ["cable-pushdown", "close-grip-bench"],
    restSeconds: 75,
    priority: 3,
    avoidIf: ["wrist"],
  },
  {
    id: "ohp",
    name: "Overhead press (front)",
    pattern: "vertical_push",
    primaryMuscles: ["front_delts", "triceps"],
    secondaryMuscles: ["side_delts", "abs"],
    equipment: ["barbell"],
    safety: "recommended",
    safetyNote: "Bar starts on the front delts and finishes over the mid-foot. Never behind the neck.",
    substitutes: ["db-shoulder-press", "landmine-press"],
    restSeconds: 150,
    priority: 1,
    avoidIf: ["shoulder"],
  },
  {
    id: "db-shoulder-press",
    name: "Seated dumbbell shoulder press",
    pattern: "vertical_push",
    primaryMuscles: ["front_delts", "side_delts"],
    secondaryMuscles: ["triceps"],
    equipment: ["dumbbell", "bench"],
    safety: "recommended",
    safetyNote: "Neutral start position is usually kinder than a barbell. Do not drop into a behind-the-neck path.",
    substitutes: ["ohp", "landmine-press"],
    restSeconds: 120,
    priority: 2,
    avoidIf: ["shoulder"],
  },
  {
    id: "landmine-press",
    name: "Landmine press",
    pattern: "vertical_push",
    primaryMuscles: ["front_delts", "chest"],
    secondaryMuscles: ["triceps"],
    equipment: ["landmine", "barbell"],
    safety: "recommended",
    safetyNote: "A more scapular-friendly overhead angle. Excellent for pole athletes and irritated shoulders.",
    substitutes: ["db-shoulder-press", "pushup"],
    restSeconds: 90,
    priority: 2,
    avoidIf: ["shoulder"],
  },
  {
    id: "db-lateral-raise",
    name: "Dumbbell lateral raise (thumbs slightly up)",
    pattern: "isolation",
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    safety: "recommended",
    safetyNote: "Raise in the scapular plane (~30° forward). Stop around shoulder height. Soft elbows. Not an upright row.",
    substitutes: ["cable-lateral-raise"],
    restSeconds: 60,
    priority: 4,
    avoidIf: ["shoulder"],
  },
  {
    id: "cable-lateral-raise",
    name: "Cable lateral raise",
    pattern: "isolation",
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    equipment: ["cable"],
    safety: "recommended",
    safetyNote: "Constant tension. Same scapular-plane rule as dumbbells.",
    substitutes: ["db-lateral-raise"],
    restSeconds: 60,
    priority: 4,
    avoidIf: ["shoulder"],
  },
  {
    id: "face-pull",
    name: "Face pull",
    pattern: "horizontal_pull",
    primaryMuscles: ["rear_delts", "rotator_cuff", "upper_back"],
    secondaryMuscles: [],
    equipment: ["cable"],
    safety: "recommended",
    safetyNote: "Externally rotate at the end (thumbs back). Light enough to feel the rear delts, not the low back.",
    substitutes: ["rear-delt-fly", "banded-pull-apart"],
    restSeconds: 60,
    priority: 3,
  },
  {
    id: "rear-delt-fly",
    name: "Rear delt fly (chest-supported)",
    pattern: "isolation",
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["upper_back"],
    equipment: ["dumbbell", "bench"],
    safety: "recommended",
    safetyNote: "Support the chest so the lumbar spine does not take over.",
    substitutes: ["face-pull"],
    restSeconds: 60,
    priority: 4,
  },
  {
    id: "banded-pull-apart",
    name: "Band pull-apart",
    pattern: "isolation",
    primaryMuscles: ["rear_delts", "upper_back"],
    secondaryMuscles: ["rotator_cuff"],
    equipment: ["bands"],
    safety: "recommended",
    safetyNote: "Keep ribs down. Great warm-up and pole-shoulder hygiene.",
    substitutes: ["face-pull"],
    restSeconds: 45,
    priority: 5,
  },
  {
    id: "cable-pushdown",
    name: "Cable triceps pushdown",
    pattern: "isolation",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable"],
    safety: "recommended",
    safetyNote: "Elbows pinned. Straight bar, rope, or V-bar. Default triceps lift instead of bench dips.",
    substitutes: ["overhead-cable-extension", "close-grip-bench", "narrow-pushup"],
    restSeconds: 60,
    priority: 4,
    avoidIf: ["elbow"],
  },
  {
    id: "overhead-cable-extension",
    name: "Overhead cable triceps extension",
    pattern: "isolation",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    equipment: ["cable"],
    safety: "recommended",
    safetyNote: "Long-head bias. Only go as far as the shoulder allows without flaring pain.",
    substitutes: ["cable-pushdown", "jm-press"],
    restSeconds: 75,
    priority: 4,
    avoidIf: ["elbow", "shoulder"],
  },
  {
    id: "jm-press",
    name: "JM press",
    pattern: "isolation",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest"],
    equipment: ["barbell", "bench"],
    safety: "recommended",
    safetyNote: "A hybrid of close-grip bench and skull crusher that keeps the elbows healthier for most lifters.",
    substitutes: ["close-grip-bench", "cable-pushdown"],
    restSeconds: 90,
    priority: 3,
    avoidIf: ["elbow"],
  },

  // --- Upper pull ---
  {
    id: "pullup",
    name: "Pull-up (strict)",
    pattern: "vertical_pull",
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["forearms", "abs"],
    equipment: ["pullup_bar"],
    safety: "recommended",
    safetyNote: "Dead hang to chin over bar, no kip. Assist with a band or machine until you own 5 clean reps.",
    substitutes: ["assisted-pullup", "lat-pulldown", "inverted-row"],
    restSeconds: 150,
    priority: 1,
    avoidIf: ["shoulder"],
  },
  {
    id: "assisted-pullup",
    name: "Assisted pull-up",
    pattern: "vertical_pull",
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["machine", "bands", "pullup_bar"],
    safety: "recommended",
    safetyNote: "Use the least assistance that lets you own the top and the lowering.",
    substitutes: ["lat-pulldown", "inverted-row"],
    restSeconds: 120,
    priority: 1,
  },
  {
    id: "lat-pulldown",
    name: "Lat pulldown (to chest)",
    pattern: "vertical_pull",
    primaryMuscles: ["lats", "biceps"],
    secondaryMuscles: ["upper_back"],
    equipment: ["cable"],
    safety: "recommended",
    safetyNote: "Pull the bar to the upper chest, slight lean, never behind the neck.",
    substitutes: ["pullup", "assisted-pullup"],
    restSeconds: 120,
    priority: 2,
    avoidIf: ["shoulder"],
  },
  {
    id: "chest-supported-row",
    name: "Chest-supported row",
    pattern: "horizontal_pull",
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "rear_delts"],
    equipment: ["dumbbell", "machine", "bench"],
    safety: "recommended",
    safetyNote: "Best row when the low back is tired from hinges. Squeeze the shoulder blades, do not shrug.",
    substitutes: ["db-row", "cable-row"],
    restSeconds: 90,
    priority: 2,
    avoidIf: ["shoulder"],
  },
  {
    id: "db-row",
    name: "Single-arm dumbbell row",
    pattern: "horizontal_pull",
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbell", "bench"],
    safety: "recommended",
    safetyNote: "Support the bench. Neutral spine. Split-stance version transfers well to pole.",
    substitutes: ["chest-supported-row", "cable-row"],
    restSeconds: 75,
    priority: 2,
  },
  {
    id: "cable-row",
    name: "Seated cable row",
    pattern: "horizontal_pull",
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps"],
    equipment: ["cable"],
    safety: "recommended",
    safetyNote: "Do not swing the torso. Neutral grip is usually friendliest.",
    substitutes: ["chest-supported-row", "db-row"],
    restSeconds: 90,
    priority: 2,
  },
  {
    id: "inverted-row",
    name: "Inverted row",
    pattern: "horizontal_pull",
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "abs"],
    equipment: ["barbell", "bodyweight"],
    safety: "recommended",
    safetyNote: "Raise the feet to progress. A key invert-prep pulling angle for pole.",
    substitutes: ["chest-supported-row", "assisted-pullup"],
    restSeconds: 75,
    priority: 2,
  },
  {
    id: "towel-row",
    name: "Towel or fat-grip row",
    pattern: "horizontal_pull",
    primaryMuscles: ["lats", "forearms", "grip"],
    secondaryMuscles: ["biceps"],
    equipment: ["dumbbell", "cable"],
    safety: "recommended",
    safetyNote: "Builds the grip that fails first on the pole. Stop if the elbow tendon is angry.",
    substitutes: ["db-row", "dead-hang"],
    restSeconds: 75,
    priority: 3,
    avoidIf: ["elbow", "wrist"],
  },
  {
    id: "dead-hang",
    name: "Dead hang",
    pattern: "carry",
    primaryMuscles: ["grip", "forearms"],
    secondaryMuscles: ["lats"],
    equipment: ["pullup_bar"],
    safety: "recommended",
    safetyNote: "Active shoulders (not a full dump). Build time slowly. The first limiter for most new pole athletes.",
    substitutes: ["towel-row", "farmer-carry"],
    restSeconds: 60,
    priority: 3,
    avoidIf: ["shoulder"],
  },
  {
    id: "farmer-carry",
    name: "Farmer carry",
    pattern: "carry",
    primaryMuscles: ["grip", "traps", "abs"],
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbell", "kettlebell"],
    safety: "recommended",
    safetyNote: "Tall posture, even steps. Walk 20–40 m per set.",
    substitutes: ["dead-hang"],
    restSeconds: 75,
    priority: 3,
  },
  {
    id: "barbell-row",
    name: "Pendlay / bent-over row",
    pattern: "horizontal_pull",
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["spinal_erectors", "biceps"],
    equipment: ["barbell"],
    safety: "caution",
    safetyNote: "High spinal demand after deadlifts. Prefer chest-supported rows if the back is smoked.",
    substitutes: ["chest-supported-row", "cable-row"],
    restSeconds: 120,
    priority: 2,
    avoidIf: ["low_back"],
  },
  {
    id: "ez-curl",
    name: "EZ-bar or dumbbell curl",
    pattern: "isolation",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    equipment: ["dumbbell", "barbell"],
    safety: "recommended",
    safetyNote: "EZ-bar or neutral hammer curls if the wrist or elbow complains.",
    substitutes: ["hammer-curl"],
    restSeconds: 60,
    priority: 4,
    avoidIf: ["elbow"],
  },
  {
    id: "hammer-curl",
    name: "Hammer curl",
    pattern: "isolation",
    primaryMuscles: ["biceps", "forearms"],
    secondaryMuscles: [],
    equipment: ["dumbbell"],
    safety: "recommended",
    safetyNote: "Neutral grip. Useful for pole grip and elbow-friendly biceps work.",
    substitutes: ["ez-curl"],
    restSeconds: 60,
    priority: 4,
  },

  // --- Core / mobility / pole ---
  {
    id: "hollow-hold",
    name: "Hollow body hold",
    pattern: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["hip_flexors"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "The single best off-pole tension drill. Low back glued down. Bend the knees to regress.",
    substitutes: ["dead-bug", "plank"],
    restSeconds: 45,
    priority: 3,
  },
  {
    id: "dead-bug",
    name: "Dead bug",
    pattern: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Exhale as the leg reaches. Ribs down.",
    substitutes: ["hollow-hold"],
    restSeconds: 45,
    priority: 4,
  },
  {
    id: "plank",
    name: "Front plank",
    pattern: "core",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Quality over time. Stop when the hips sag.",
    substitutes: ["hollow-hold", "side-plank"],
    restSeconds: 45,
    priority: 4,
  },
  {
    id: "side-plank",
    name: "Side plank",
    pattern: "core",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["glutes"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Stack the shoulders. Drop to the knee to regress.",
    substitutes: ["pallof-press", "plank"],
    restSeconds: 45,
    priority: 4,
  },
  {
    id: "hanging-knee-raise",
    name: "Hanging knee / leg raise",
    pattern: "core",
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: ["grip"],
    equipment: ["pullup_bar"],
    safety: "recommended",
    safetyNote: "Posterior tilt at the top. Invert-prep for pole. Do not swing.",
    substitutes: ["hollow-hold", "captains-chair-raise"],
    restSeconds: 60,
    priority: 3,
    avoidIf: ["shoulder"],
  },
  {
    id: "captains-chair-raise",
    name: "Captain's chair knee raise",
    pattern: "core",
    primaryMuscles: ["abs", "hip_flexors"],
    secondaryMuscles: [],
    equipment: ["machine"],
    safety: "recommended",
    safetyNote: "Use this if hanging irritates the shoulders or grip fails first.",
    substitutes: ["hanging-knee-raise", "hollow-hold"],
    restSeconds: 60,
    priority: 4,
  },
  {
    id: "pallof-press",
    name: "Pallof press",
    pattern: "core",
    primaryMuscles: ["obliques", "abs"],
    secondaryMuscles: [],
    equipment: ["cable", "bands"],
    safety: "recommended",
    safetyNote: "Anti-rotation for spins and landings. Press out, pause, do not let the cable twist you.",
    substitutes: ["side-plank"],
    restSeconds: 45,
    priority: 3,
  },
  {
    id: "turkish-getup",
    name: "Turkish get-up (light)",
    pattern: "core",
    primaryMuscles: ["abs", "obliques", "front_delts"],
    secondaryMuscles: ["glutes"],
    equipment: ["kettlebell", "dumbbell"],
    safety: "caution",
    safetyNote: "Learn unloaded first. Light load. Excellent unilateral stability for pole; skip if the shoulder is unhappy.",
    substitutes: ["pallof-press", "landmine-press"],
    restSeconds: 75,
    priority: 3,
    avoidIf: ["shoulder", "wrist"],
  },
  {
    id: "wrist-prep",
    name: "Wrist rocks and prayer stretches",
    pattern: "mobility",
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Pole and floor work load the wrists. Move slowly through flexion and extension.",
    substitutes: [],
    restSeconds: 20,
    priority: 5,
    avoidIf: ["wrist"],
  },
  {
    id: "shoulder-cares",
    name: "Shoulder CARs + wall slides",
    pattern: "mobility",
    primaryMuscles: ["rotator_cuff"],
    secondaryMuscles: ["upper_back"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Daily hygiene for overhead and invert work. Pain-free range only.",
    substitutes: ["face-pull", "banded-pull-apart"],
    restSeconds: 20,
    priority: 5,
  },
  {
    id: "hip-90-90",
    name: "90/90 hip switches + pigeon",
    pattern: "mobility",
    primaryMuscles: ["glutes", "hip_flexors"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Needed for lines, splits, and deep squats. Do not force the knee.",
    substitutes: [],
    restSeconds: 20,
    priority: 5,
    avoidIf: ["knee", "hip"],
  },
  {
    id: "thoracic-opener",
    name: "Thoracic open books + cat-cow",
    pattern: "mobility",
    primaryMuscles: ["upper_back"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "Rotation and extension for overhead and back-bending shapes.",
    substitutes: ["shoulder-cares"],
    restSeconds: 20,
    priority: 5,
  },
  {
    id: "hanging-tuck",
    name: "Hanging tuck hold",
    pattern: "core",
    primaryMuscles: ["abs", "grip", "lats"],
    secondaryMuscles: ["hip_flexors"],
    equipment: ["pullup_bar"],
    safety: "recommended",
    safetyNote: "Invert-readiness: knees to chest, posterior tilt, hold. Progress toward an inverted hang with a spotter or spotter-band — never kip.",
    substitutes: ["hanging-knee-raise", "hollow-hold"],
    restSeconds: 60,
    priority: 3,
    avoidIf: ["shoulder"],
  },

  // --- Cardio ---
  {
    id: "zone2-bike",
    name: "Zone 2 bike or rower",
    pattern: "cardio",
    primaryMuscles: ["quads", "hamstrings"],
    secondaryMuscles: [],
    equipment: ["cardio_machine"],
    safety: "recommended",
    safetyNote: "Conversational pace, roughly 60–70% max heart rate. Prefer bike if running plus squats bothers the knees. Separate from lifting by 3+ hours when you can (Schumann 2022).",
    substitutes: ["zone2-walk", "easy-incline-walk"],
    restSeconds: 0,
    priority: 1,
    isCardio: true,
  },
  {
    id: "zone2-walk",
    name: "Zone 2 walk / easy jog",
    pattern: "cardio",
    primaryMuscles: ["quads", "calves"],
    secondaryMuscles: [],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "If you run the same day as squats, lift first or split by 3 hours.",
    substitutes: ["zone2-bike", "easy-incline-walk"],
    restSeconds: 0,
    priority: 1,
    isCardio: true,
  },
  {
    id: "easy-incline-walk",
    name: "Incline treadmill walk",
    pattern: "cardio",
    primaryMuscles: ["glutes", "calves"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["cardio_machine"],
    safety: "recommended",
    safetyNote: "Low-impact Zone 2 that also loads the posterior chain.",
    substitutes: ["zone2-walk", "zone2-bike"],
    restSeconds: 0,
    priority: 1,
    isCardio: true,
  },
  {
    id: "intervals",
    name: "Intervals (bike / rower / hill)",
    pattern: "cardio",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    equipment: ["cardio_machine"],
    safety: "recommended",
    safetyNote: "Example: 6–10 x 60s hard / 90s easy. Do not pair with a max-effort lower day in the same session.",
    substitutes: ["stage-circuit", "zone2-bike"],
    restSeconds: 90,
    priority: 1,
    isCardio: true,
  },
  {
    id: "stage-circuit",
    name: "Stage / set-endurance circuit",
    pattern: "cardio",
    primaryMuscles: ["abs", "glutes", "grip"],
    secondaryMuscles: ["front_delts", "lats"],
    equipment: ["bodyweight"],
    safety: "recommended",
    safetyNote: "3–5 rounds: 40s work / 20s transition of squat, push-up, hollow, and a carry. Mimics long performance sets without kipping.",
    substitutes: ["intervals", "zone2-bike"],
    restSeconds: 60,
    priority: 2,
    isCardio: true,
  },
];

export const EXERCISES: Exercise[] = [...CORE_EXERCISES, ...MOVEMENT_EXERCISES];

const byId = new Map(EXERCISES.map((e) => [e.id, e]));

export function getExercise(id: string): Exercise | undefined {
  return byId.get(id);
}

export function recommendedExercises() {
  return EXERCISES.filter((e) => e.safety !== "banned");
}

export function bannedExercises() {
  return EXERCISES.filter((e) => e.safety === "banned");
}

export function allowedSubstitutes(exerciseId: string, injuries: string[] = []) {
  const ex = getExercise(exerciseId);
  if (!ex) return [];
  return ex.substitutes
    .map((id) => getExercise(id))
    .filter((candidate): candidate is Exercise => {
      if (!candidate) return false;
      if (candidate.safety === "banned") return false;
      if (candidate.avoidIf?.some((i) => injuries.includes(i))) return false;
      return true;
    });
}

export function isExerciseAllowed(exercise: Exercise, injuries: string[] = []) {
  if (exercise.safety === "banned") return false;
  if (exercise.avoidIf?.some((i) => injuries.includes(i))) return false;
  return true;
}