export const STARTER_FOODS = [
  { id: "food-eggs", name: "Eggs (2 large)", calories: 144, protein: 12.6, carbs: 0.8, fat: 9.5, serving: "2 eggs" },
  { id: "food-chicken", name: "Chicken breast, cooked", calories: 165, protein: 31, carbs: 0, fat: 3.6, serving: "100 g" },
  { id: "food-salmon", name: "Salmon, cooked", calories: 208, protein: 20, carbs: 0, fat: 13, serving: "100 g" },
  { id: "food-greek-yogurt", name: "Greek yogurt, plain 2%", calories: 73, protein: 10, carbs: 3.9, fat: 1.9, serving: "100 g" },
  { id: "food-whey", name: "Whey protein shake", calories: 120, protein: 24, carbs: 3, fat: 1.5, serving: "1 scoop" },
  { id: "food-cottage", name: "Cottage cheese 2%", calories: 81, protein: 11, carbs: 5, fat: 2.3, serving: "100 g" },
  { id: "food-beef", name: "Lean ground beef 93%", calories: 152, protein: 21, carbs: 0, fat: 7, serving: "100 g cooked" },
  { id: "food-tofu", name: "Firm tofu", calories: 144, protein: 17, carbs: 3, fat: 9, serving: "100 g" },
  { id: "food-rice", name: "White rice, cooked", calories: 130, protein: 2.7, carbs: 28, fat: 0.3, serving: "100 g" },
  { id: "food-oats", name: "Oats, dry", calories: 150, protein: 5, carbs: 27, fat: 3, serving: "40 g" },
  { id: "food-banana", name: "Banana", calories: 105, protein: 1.3, carbs: 27, fat: 0.4, serving: "1 medium" },
  { id: "food-berries", name: "Mixed berries", calories: 57, protein: 0.7, carbs: 14, fat: 0.3, serving: "100 g" },
  { id: "food-apple", name: "Apple", calories: 95, protein: 0.5, carbs: 25, fat: 0.3, serving: "1 medium" },
  { id: "food-potato", name: "Potato, baked", calories: 93, protein: 2.5, carbs: 21, fat: 0.1, serving: "100 g" },
  { id: "food-bread", name: "Sourdough slice", calories: 90, protein: 3, carbs: 17, fat: 1, serving: "1 slice" },
  { id: "food-olive-oil", name: "Olive oil", calories: 119, protein: 0, carbs: 0, fat: 13.5, serving: "1 tbsp" },
  { id: "food-avocado", name: "Avocado", calories: 160, protein: 2, carbs: 9, fat: 15, serving: "100 g" },
  { id: "food-almonds", name: "Almonds", calories: 170, protein: 6, carbs: 6, fat: 15, serving: "28 g" },
  { id: "food-broccoli", name: "Broccoli", calories: 35, protein: 2.4, carbs: 7, fat: 0.4, serving: "100 g" },
  { id: "food-spinach", name: "Spinach", calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4, serving: "100 g" },
  { id: "food-milk", name: "Milk 2%", calories: 122, protein: 8, carbs: 12, fat: 5, serving: "240 ml" },
  { id: "food-cheese", name: "Cheddar", calories: 113, protein: 7, carbs: 0.4, fat: 9, serving: "28 g" },
  { id: "food-pasta", name: "Pasta, cooked", calories: 131, protein: 5, carbs: 25, fat: 1.1, serving: "100 g" },
  { id: "food-beans", name: "Black beans, cooked", calories: 132, protein: 8.9, carbs: 24, fat: 0.5, serving: "100 g" },
  { id: "food-peanut-butter", name: "Peanut butter", calories: 188, protein: 8, carbs: 6, fat: 16, serving: "2 tbsp" },
  { id: "food-coffee", name: "Black coffee", calories: 2, protein: 0.3, carbs: 0, fat: 0, serving: "240 ml" },
  { id: "food-latte", name: "Caffe latte", calories: 150, protein: 8, carbs: 12, fat: 6, serving: "240 ml" },
  { id: "food-bagel", name: "Bagel", calories: 277, protein: 11, carbs: 55, fat: 1.4, serving: "1 bagel" },
  { id: "food-protein-bar", name: "Protein bar", calories: 200, protein: 20, carbs: 22, fat: 6, serving: "1 bar" },
  { id: "food-pizza-slice", name: "Pizza slice", calories: 285, protein: 12, carbs: 36, fat: 10, serving: "1 slice" },
  { id: "food-overnight-oats", name: "Overnight oats", calories: 320, protein: 18, carbs: 42, fat: 8, serving: "1 bowl" },
];