import { makeSkill as skill } from "./skill-factory";
import type { Skill } from "./types";

/** Commercial exotic / stripper set vocabulary — amateur-night and club-style, adult. */
export const EXOTIC_CLUB_SKILLS: Skill[] = [
  skill({
    id: "heels",
    exerciseId: "heel-walk",
    name: "Heel walk",
    module: "Presence",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "10 min",
    why: "Heels change the walk. They do not replace it. If the sneaker walk is rushed, heels will look drunk.",
    safety: "Only after the trainer walk is quiet. Ankle rolls, pinching, or numbness is a stop. Practice on a clean floor. No new tricks in heels.",
    cue: "Shorter step. Tall ankle. Same slow.",
    steps: [
      "Put the trainers away. One stable pair of heels you can stand still in.",
      "Stand. Soft knees. Weight through the whole foot, not jammed in the toe box.",
      "Shorter steps than sneakers. Heel, then ball. Hips over the feet.",
      "Walk eight steps. Pause in a pose you can hold.",
      "Turn. Walk back. Same speed. Sit down and take them off before anything else.",
    ],
    watchFor: ["Long steps that roll the ankle", "Locking the knees", "Looking at the feet", "Adding spins"],
    voiceScript:
      "Heels are a costume, not a personality. Shorter steps. Soft knees. The same slow walk you already own. Pause in a pose you can breathe in. If the ankle rolls, we go back to trainers. Nobody tips a limp. We stay intact.",
    diagram: "heels",
    practice: "Two lengths of the room in heels. Sit. Take them off. One length in trainers to remind the ankle.",
    passWhen: "You can walk eight steps, pause, and turn without looking at your feet.",
    firstThen: { first: "Quiet trainer walk", then: "Short heel walk" },
  }),
  skill({
    id: "hands",
    exerciseId: "money-hands",
    name: "Hand styling",
    module: "Presence",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "6 min",
    why: "Fists and floppy wrists make a set look unfinished. Soft hands frame the body and the tip rail.",
    safety: "Wrists stay in a comfortable range. No behind-the-head ports. Shoulders down.",
    cue: "Soft hands. Frame, don’t flap.",
    steps: [
      "Shake the hands out. Fingers long, not splayed.",
      "Trace the body without grabbing: thigh, waist, hair, then away.",
      "At the ‘rail’ mark on the wall, present an open palm at hip height — receiving, not grabbing.",
      "Return the hands to a shape you can walk in.",
    ],
    watchFor: ["Claw fingers", "Hiding the hands behind the back the whole phrase", "Shrugging"],
    voiceScript:
      "Hands next. Long fingers. Trace — thigh, waist, hair — then away. At the rail, an open palm. You are receiving, not snatching. Soft. If you do not know what to do with them, frame your face and walk. Floppy is free. We are not free.",
    diagram: "hands",
    practice: "One 8-count walk with a hand pathway. One 8-count with an open palm at the wall mark.",
    passWhen: "Hands have a job on every count. No dead fists.",
    firstThen: { first: "Walk you own", then: "Give the hands a path" },
  }),
  skill({
    id: "stage-map",
    exerciseId: "stage-map",
    name: "Own the rectangle",
    module: "Presence",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "A club stage is a box: upstage pole, downstage rail, two corners. Dancing in one spot reads as scared.",
    safety: "Mark the floor with tape. No running. Heels optional. Leave a crash-mat zone if the pole is in play.",
    cue: "Corner. Center. Rail. Home.",
    steps: [
      "Tape a rectangle. Pole or a chair is upstage center.",
      "Walk to downstage center — the rail. Pause. Look at the wall.",
      "Walk to a downstage corner. Pose two counts.",
      "Cross to the other corner. Same slow.",
      "Return upstage to the pole or chair. That is one map.",
    ],
    watchFor: ["Hugging the pole the whole song", "Racing the corners", "Eyes on the floor in transit"],
    voiceScript:
      "Tape a box. The pole is home. The front edge is the rail. Walk front. Pause. Corner. Other corner. Home. Same slow walk. If you live on the pole all night, the room cannot see you. Make them wait while you travel.",
    diagram: "walk",
    practice: "Three maps. Rest. One map with a pose in each corner.",
    passWhen: "You can hit rail, both corners, and home without rushing.",
    firstThen: { first: "Walk on a line", then: "Walk the whole box" },
  }),
  skill({
    id: "shimmy",
    exerciseId: "shoulder-shimmy",
    name: "Shoulder shimmy",
    module: "Body",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "6 min",
    why: "A small shoulder shimmy sells a chorus without leaving your feet. A neck shimmy is a headache.",
    safety: "Shoulders, not the neck. Small range. Stop if you get dizzy or the neck complains.",
    cue: "Shoulders. Not the neck.",
    steps: [
      "Soft knees. Jaw unclenched.",
      "Alternate the shoulders forward a tiny amount, fast enough to read, small enough to last.",
      "Keep the head still on a spot.",
      "Eight counts. Rest eight. Repeat.",
    ],
    watchFor: ["Neck wagging", "Breath holding", "Making it bigger until it is ugly"],
    voiceScript:
      "Shoulders only. Head stays. Tiny. Musical. If your neck joins in, we stopped being expensive. Eight counts. Rest eight. This is a chorus you can do in heels later — not a seizure.",
    diagram: "wave",
    practice: "Two phrases of eight. Water. One more if the neck is quiet.",
    passWhen: "Head stays. Shoulders read. You can talk while you do it.",
    firstThen: { first: "Still head", then: "Small shoulder tick" },
  }),
  skill({
    id: "grind",
    exerciseId: "standing-grind",
    name: "Standing grind",
    module: "Body",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "This is the commercial hip engine of a lap phrase — trained on air or a chair back, never on a person at home.",
    safety: "Soft knees. Glutes and hips, not a lumbar crank. Chair is furniture. No partner required.",
    cue: "Hips draw. Ribs quiet.",
    steps: [
      "Face a sturdy chair back or the pole. Hands light on it for balance.",
      "Soft knees. Draw a slow circle or figure-8 with the hips.",
      "Keep a hand-width of air between you and the furniture.",
      "Eight slow. Reverse. Stand tall and walk off.",
    ],
    watchFor: ["Dumping the low back", "Collapsing the chest onto the chair", "Speed"],
    voiceScript:
      "Hands on the chair back. Air between you and the furniture — this is a stand-in, not a person. Hips draw a slow circle. Ribs quiet. If you need a huge backbend, you are in the wrong joint. Walk off like you meant the last count.",
    diagram: "grind",
    practice: "One eight each direction. Walk away. Repeat once.",
    passWhen: "The circle is even both ways and you can breathe through it.",
    firstThen: { first: "Standing figure-8", then: "Same hips at a chair back" },
  }),
  skill({
    id: "crawl",
    exerciseId: "cat-crawl",
    name: "Cat crawl",
    module: "Floor",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "A slow crawl downstage is a whole verse. It photographs. It does not need a split.",
    safety: "Pads under knees. Fists or forearms if wrists complain. No neck-loaded drop.",
    cue: "Opposite hand, opposite knee. Slow.",
    steps: [
      "Tabletop on pads. Eyes on the rail mark, not the floor forever.",
      "Right hand and left knee. Then left hand and right knee.",
      "Hips stay level. Hair can follow last.",
      "Crawl four steps. Pause in tabletop. Crawl back or sit to a mermaid.",
    ],
    watchFor: ["Same-side crawling that wriggles", "Collapsed wrists", "Racing"],
    voiceScript:
      "Tabletop. Opposite hand, opposite knee. Slow enough that I could count it. Eyes on the rail. If the wrists talk, fists or forearms. This is a verse. Treat it like one. No splits required.",
    diagram: "crawl",
    practice: "Four crawls down. Pause. Four back. Rest.",
    passWhen: "Hips stay level and you can pause without collapsing.",
    firstThen: { first: "Quiet tabletop", then: "Opposite crawl" },
  }),
  skill({
    id: "mermaid",
    exerciseId: "mermaid-sit",
    name: "Mermaid sit",
    module: "Floor",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "6 min",
    why: "A hip sit is a rest pose that still reads as a show. Both sides. It is not a pancake contest.",
    safety: "Sit to the hip, not onto a painful knee. Both sides. Skip if the hip or knee barks.",
    bothSides: true,
    cue: "Hip down. Chest tall. Switch.",
    steps: [
      "From kneeling, sit the hips beside the heels to one side.",
      "Chest tall. Hands can dress the legs or the floor.",
      "Pause two breaths.",
      "Come through kneeling and sit the other side. Same time.",
    ],
    watchFor: ["Only the pretty side", "Rounding into a painful low back", "Forcing a pancake"],
    voiceScript:
      "Sit to the hip. Tall chest. Two breaths. Other side. Same time. I do not care which side photographs better. A mermaid is a rest that still looks like a set. If the knee yells, we stay kneeling.",
    diagram: "floor",
    practice: "Three sits each side. Stand. Shake the legs.",
    passWhen: "Equal time both hips. You can breathe in the pose.",
    firstThen: { first: "Tall kneeling", then: "Hip sit both sides" },
  }),
  skill({
    id: "ladder",
    exerciseId: "level-ladder",
    name: "Level ladder",
    module: "Floor",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "10 min",
    why: "Commercial sets change level: stand, kneel, sit, back, kneel, stand. The ladder is the skill. Tricks are optional.",
    safety: "Pad knees. Use a hand. No dropping. Reverse is as slow as the way down.",
    cue: "Stand. Kneel. Sit. Back. Up the same way.",
    steps: [
      "Stand. Walk two steps.",
      "Lower to kneeling on pads.",
      "Sit to a mermaid or hip sit.",
      "Optional: come to the back for two breaths — no neck bridge.",
      "Reverse: sit, kneel, stand. Walk two steps.",
    ],
    watchFor: ["Dropping a level", "Skipping the reverse", "Neck-loaded back work"],
    voiceScript:
      "This is the ladder. Stand. Kneel. Sit. Maybe the back — no neck. Then up the same way. If you drop a level, we do it again. Getting up is how you leave the stage. Practice the up as much as the down.",
    diagram: "floor",
    practice: "Three full ladders. Rest between. No extra tricks inside.",
    passWhen: "Down and up take the same slow tempo. No thud.",
    firstThen: { first: "Floor descent you own", then: "Full ladder with a reverse" },
  }),
  skill({
    id: "floor-grind",
    exerciseId: "floor-grind",
    name: "Floor hip work",
    module: "Floor",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "Hips on the floor fill a chorus. This is contact-free. The floor is the partner.",
    safety: "Pads. Forearms if wrists complain. No neck bridges. Small range if the back is cranky.",
    cue: "Hips draw on the floor. Neck free.",
    steps: [
      "Tabletop or forearm support on pads.",
      "Circle or pulse the hips. Both directions.",
      "Keep the neck long. Eyes can find the rail.",
      "Return to tabletop. That is one chorus.",
    ],
    watchFor: ["Neck taking load", "Making it a flexibility contest", "Breath holding"],
    voiceScript:
      "On the pads. Hips draw. Both ways. Neck stays free — no bridges. Eyes on the rail if you can. Come back to tabletop. That is a chorus. Leave the circus for someone else's night.",
    diagram: "grind",
    practice: "Two choruses each direction. Rest on your side.",
    passWhen: "You can reverse direction without losing the pads or the breath.",
    firstThen: { first: "Tabletop home base", then: "Hip circle on the floor" },
  }),
  skill({
    id: "reverse-chair",
    exerciseId: "reverse-chair-sit",
    name: "Reverse chair sit",
    module: "Chair",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "Facing away from the rail is half of a commercial chair phrase. The back still has to read.",
    safety: "Sturdy chair. Sit to the edge. No neck-loaded drop off the back. Stand without yanking the knees.",
    cue: "Turn. Sit facing away. Tall back.",
    steps: [
      "Walk in. Turn so the chair is behind you.",
      "Sit to the edge. Hands on the seat or thighs.",
      "Tall back. A small hip circle. Two breaths.",
      "Stand. Turn to the rail. Walk off.",
    ],
    watchFor: ["Dropping into the chair", "Collapsing the chest", "A wobbly chair"],
    voiceScript:
      "Turn. Sit facing away. The chair is still furniture. Tall back — they can see you from behind. Small circle. Stand. Face the rail. Walk off. If you disappear into the seat, we lost the verse.",
    diagram: "chair",
    practice: "Four reverse sits. Same slow stand every time.",
    passWhen: "Sit and stand are quiet. The back stays long.",
    firstThen: { first: "Front-edge sit you own", then: "Same sit facing away" },
  }),
  skill({
    id: "lap-phrase",
    exerciseId: "lap-phrase",
    name: "Three-part chair set",
    module: "Chair",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "12 min",
    why: "A club chair set has a beginning, a middle, and a close. Train it on furniture so you are not inventing on a person.",
    safety: "Chair is a stand-in, not a person. No partner at home. Consent and house rules exist in a real club — this drill does not replace them. Sturdy chair only.",
    cue: "Approach. Body. Close.",
    steps: [
      "Approach: walk in, eye-line, sit to the edge.",
      "Body: seated hips or a chair roll. Stay on the sit bones. Air or light contact with the chair only.",
      "Close: still, then stand, then walk off on the same slow tempo.",
      "Rest a full 8. Repeat. Do not add a new trick in the middle.",
    ],
    watchFor: ["Skipping the close", "Rushing the approach", "Treating a person as a prop"],
    voiceScript:
      "Three parts. Walk in. Sit. That is the approach. Then the body — hips or a roll, on the chair, not on a person. Then the close: still, stand, walk off. If you skip the close, it reads as panic. Furniture only at home. In a club, consent and the house rules are the real choreography.",
    diagram: "chair",
    practice: "Three full phrases. Rest an 8 between. No extra tricks.",
    passWhen: "A stranger could name approach, body, and close from the timing.",
    firstThen: { first: "Chair approach you own", then: "Approach, body, close" },
  }),
  skill({
    id: "skirt",
    exerciseId: "skirt-work",
    name: "Skirt and dress work",
    module: "Costume",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "Fabric is a prop. If it fights the hips, the set looks busy. Practice the garment until it is boring.",
    safety: "Practice in the actual skirt or a similar length. No neck-loaded floor tricks while dressing. Heels only if the walk is already quiet.",
    cue: "Hips move the cloth. Hands help, not panic.",
    steps: [
      "Stand. Let a hip figure-8 move the skirt. Hands stay soft.",
      "On four, use one hand to lift or sweep the hem, then release.",
      "Walk. The cloth follows. Do not stare at it.",
      "If it catches, simplify the garment. The show is not a sewing class.",
    ],
    watchFor: ["Fighting the zipper mid-phrase", "Looking down the whole 8", "A hem you trip on"],
    voiceScript:
      "The hips move the cloth. Hands help once, then they go back to framing. If the skirt fights you, wear a simpler one tonight. Eyes up. Fabric is a prop. Props that pick fights get cut.",
    diagram: "layer",
    practice: "Two 8-counts in the real garment. Change nothing else.",
    passWhen: "You can walk and figure-8 without looking at the hem.",
    firstThen: { first: "Hip figure-8", then: "Same 8 in the skirt" },
  }),
  skill({
    id: "peel",
    exerciseId: "top-peel",
    name: "Top layer peel",
    module: "Costume",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "A peel is a counted transition. Wrestling a top is not a reveal.",
    safety: "Stay on your feet or kneeling. No new floor tricks during the peel. Practice the actual layer. Adult, unhurried.",
    cue: "Phrase. Peel on the count. Phrase.",
    steps: [
      "Do an 8-count you already own.",
      "On the next 8, take one top layer off without rushing. Eyes up as much as you can.",
      "Place it on the chair or the floor on purpose — do not throw blindly.",
      "Do the next 8-count in what is left. Breathe.",
    ],
    watchFor: ["Rushing", "A garment you cannot undo with one calm motion", "Apologizing"],
    voiceScript:
      "Phrase. Peel. Phrase. On the count, not in a panic. Put the layer somewhere you chose. Eyes up. If the top fights you, we change the top, not the music. This is adult set-craft. Unhurried is the point.",
    diagram: "layer",
    practice: "Three peels with the real layer. Full rest between.",
    passWhen: "The peel fits inside one 8 and you still know where you are on stage.",
    firstThen: { first: "8-count you own", then: "Same 8 plus one layer" },
  }),
  skill({
    id: "heel-floor",
    exerciseId: "heel-floor",
    name: "Heels on the floor",
    module: "Costume",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "Decide before the song: keep the heels for a kneeling phrase, or take them off as a counted layer. Do not invent mid-descent.",
    safety: "Pads. Practice the take-off as its own 8. Never run in heels. Ankle roll is a stop.",
    cue: "Decide. Count it. Or keep them.",
    steps: [
      "From standing in heels, lower to kneeling on pads with a hand if you need it.",
      "Option A: keep the heels on. Weight through the knees, not twisted in the ankle.",
      "Option B: on an 8, take them off and set them upstage on purpose.",
      "Stand the way you planned. Do not switch plans mid-rep.",
    ],
    watchFor: ["Changing the plan on the way down", "Twisting the ankle", "Kicking shoes into the room"],
    voiceScript:
      "Pick a plan. Keep the heels, or take them off on an eight and park them upstage. Do not invent on the way down. Pads. Hand if you need it. Intact ankles are the aesthetic.",
    diagram: "heels",
    practice: "Two descents keeping heels. Two with a counted take-off.",
    passWhen: "You can name the plan out loud and then do it.",
    firstThen: { first: "Floor descent in trainers", then: "Same descent with a heel plan" },
  }),
  skill({
    id: "rail",
    exerciseId: "rail-approach",
    name: "Rail approach",
    module: "Club craft",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "Downstage is where the set gets paid attention. Hovering upstage the whole song is a rehearsal.",
    safety: "Tape a rail line. No grabbing a real person. Open palm, eye-line, then leave. House rules in a club override this drill.",
    cue: "Walk front. Look. Offer. Leave.",
    steps: [
      "From upstage, walk the slow walk to the tape line.",
      "Pause. Eye-line on the wall. Soft hands.",
      "Open palm at hip height for two counts — receiving, not snatching.",
      "Back up or turn and walk to a corner. Do not camp.",
    ],
    watchFor: ["Staying at the rail the whole song", "Looking at the floor", "Grabbing"],
    voiceScript:
      "Walk to the rail. Look. Open palm. Two counts. Then you leave — a corner, or home. Camping the rail is needy. Visiting the rail is expensive. In a real club the house rules win. At home, the wall is your audience.",
    diagram: "hands",
    practice: "Five approaches. Different exits: corner, home, kneel.",
    passWhen: "You can arrive, pause, and leave without speeding up.",
    firstThen: { first: "Own the rectangle", then: "Visit the rail and leave" },
  }),
  skill({
    id: "two-song",
    exerciseId: "two-song-map",
    name: "Two-song club map",
    module: "Club craft",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "14 min",
    why: "Classic club structure: song one is the walk, the tease, the costume; song two is the body, the floor, the close. Amateur night is often one song — still map it.",
    safety: "Only skills you already own. Full rest between songs. No new inverts. Crash mat if the pole is in either song.",
    cue: "Song one: arrive. Song two: body. Then stop.",
    steps: [
      "Song one map: walk on, own the box, one layer or none, pole or chair as prop, stay mostly standing.",
      "Rest a full song or two minutes.",
      "Song two map: chair or floor phrase, one owned spin or sit if you have a pole, close and walk off.",
      "If something fails, keep the walk. Do not invent.",
    ],
    watchFor: ["Dumping all the tricks in song one", "No rest", "A new invert in song two"],
    voiceScript:
      "Two songs. First song you arrive — walk, box, maybe a layer, pole as a prop. Rest. Second song is the body — chair, floor, one skill you already own, then you close. Amateur night might only give you one song. Then we compress: arrive, body, close, stop. Never a new invert. Never a panic trick.",
    diagram: "song",
    practice: "Talk the map out loud. Then run song one. Rest. Run song two. Sit.",
    passWhen: "You can say the map without moving, then dance it without adding.",
    firstThen: { first: "One 8-count", then: "Two-song map of owned skills" },
  }),
  skill({
    id: "close",
    exerciseId: "closing-exit",
    name: "Closing walk-off",
    module: "Club craft",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "6 min",
    why: "The last eight counts are what people remember. A shrug-off reads as sorry. A still pose and a slow walk off reads as a show.",
    safety: "No new tricks in the close. Heels only if the walk is already quiet. Leave the mat clear.",
    cue: "Still. Look. Walk off.",
    steps: [
      "Finish whatever phrase you are in.",
      "Still for two counts. Eye-line.",
      "One pose you can hold.",
      "Walk off on the same slow tempo. Do not jog. Do not apologize.",
    ],
    watchFor: ["Jogging off", "Looking at the floor", "Adding a trick because the song has bars left"],
    voiceScript:
      "Still. Look. Pose. Walk off. Same slow. If the song has bars left, you hold. You do not invent. Jogging off is how a set unravels. We leave like we arrived.",
    diagram: "exit",
    practice: "Five closes from different phrases: walk, kneel, chair.",
    passWhen: "The last eight are slower than the middle of the set, not faster.",
    firstThen: { first: "Pause pose you own", then: "Pose plus walk off" },
  }),
  skill({
    id: "recovery",
    exerciseId: "slip-recovery",
    name: "Slip recovery",
    module: "Club craft",
    courseId: "exotic_amateur_night",
    level: "foundation",
    durationLabel: "6 min",
    why: "Amateur night includes a miss. The recovery is the skill: pause, smile or breathe, walk, continue the map.",
    safety: "Practice a fake miss, not a real fall. If you actually slip, check the ankle and the wrist. Pain is a stop.",
    cue: "Pause. Breathe. Walk. Continue.",
    steps: [
      "Pick a spot in an 8-count and freeze as if something failed.",
      "Two counts of stillness. Do not apologize out loud.",
      "Walk two steps on the slow tempo.",
      "Pick up the next thing on your map. End with a close.",
    ],
    watchFor: ["Laughing it off into a rush", "Inventing a trick to ‘make up for it’", "Leaving the stage"],
    voiceScript:
      "Something will miss. Pause. Two counts. Walk. Continue the map. Do not invent a save. Do not apologize to the wall. A recovery that stays slow looks like choreography. A recovery that speeds up looks like a mistake.",
    diagram: "exit",
    practice: "Three fake misses in three different phrases. Close after each.",
    passWhen: "A miss does not change your tempo.",
    firstThen: { first: "8-count you own", then: "Same 8 with a planned freeze" },
  }),
  skill({
    id: "ankle-prep",
    exerciseId: "ankle-prep",
    name: "Ankle and heel prep",
    module: "Presence",
    courseId: "exotic_amateur_night",
    level: "foundation",
    durationLabel: "6 min",
    why: "Heels fail at the ankle, not at the attitude. Prep the foot before the costume.",
    safety: "Short-foot, calf wall, slow heel stands. Pinch, numbness, or a roll is a stop. No new tricks in this block.",
    cue: "Wake the foot. Then the heel.",
    steps: [
      "Short-foot: lift the arch without clawing the toes. Eight each side.",
      "Calf wall, straight then bent knee. Thirty seconds each.",
      "Slow heel stands in trainers. Soft knees.",
      "Only then put the heels on, or keep trainers today.",
    ],
    watchFor: ["Skipping this and going straight to a heel spin", "Jamming the toe box", "Ignoring numbness"],
    voiceScript:
      "The ankle first. Short-foot. Calf on the wall. Slow heel stands in trainers. If that is not quiet, we do not put the heels on. A limp is not a look. Intact is the aesthetic.",
    diagram: "heels",
    practice: "One round of the prep. Then decide: heels or trainers for the rest of the session.",
    passWhen: "You can name the stop signs — pinch, numb, roll — and you actually stop.",
    firstThen: { first: "Quiet trainer walk", then: "Ankle prep, then heels if they earn it" },
  }),
  skill({
    id: "table-edge",
    exerciseId: "table-edge",
    name: "Table / podium",
    module: "Floor",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "10 min",
    why: "A club podium or a sturdy table is a second stage. Sit, stand, and a seated phrase without a person.",
    safety: "Table against a wall. Pads on the floor. Do not drop off the edge. Furniture, not a person.",
    cue: "Sit. Phrase. Stand. Down on purpose.",
    steps: [
      "Check the table. It does not wobble. Pads under the landing.",
      "Sit to the edge. Hands on the table. Tall back.",
      "Seated hips or a small roll. Two breaths.",
      "Stand on the table if it is low and stable, or stay seated. Step down with a hand. Do not hop off.",
    ],
    watchFor: ["A wobbly table", "Dropping off the back", "Treating a person as the table"],
    voiceScript:
      "The table is furniture. Against the wall. Pads. Sit the edge. Phrase. Stand or stay. Step down with a hand. We do not drop off a podium to look brave. Brave is intact.",
    diagram: "floor",
    practice: "Four sit-phrase-down cycles. Same slow every time.",
    passWhen: "Up and down are quiet. The table never moves.",
    firstThen: { first: "Chair sit you own", then: "Same phrase on a sturdy table" },
  }),
  skill({
    id: "fan-kick",
    exerciseId: "fan-kick",
    name: "Controlled fan kick",
    module: "Body",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "A slow fan reads as expensive. A whipped kick reads as a hamstring story.",
    safety: "Low. Slow. Hand on a chair or pole. Both sides. No ballistic. Skip if the hamstring or back barks.",
    bothSides: true,
    cue: "Hand on. Low fan. Both sides.",
    steps: [
      "Hold a chair back or the pole. Standing leg soft.",
      "Sweep the free leg in a low arc. Hip stays stacked.",
      "Return. Same height other side. Same number.",
      "Only raise the arc if the low one is boring.",
    ],
    watchFor: ["Whipping", "Only the pretty side", "A standing knee that locks"],
    voiceScript:
      "Hand on the chair. Low fan. I said low. Other side, same number. If you need a whip to get height, you do not own the kick. We stay expensive, not ballistic.",
    diagram: "walk",
    practice: "Six fans each side. Rest. Six more lower than you want.",
    passWhen: "Both sides match height and you can breathe at the top of the arc.",
    firstThen: { first: "Attitude lift you own", then: "Same standing leg into a low fan" },
  }),
  skill({
    id: "jacket-peel",
    exerciseId: "jacket-peel",
    name: "Jacket or cape peel",
    module: "Costume",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "A jacket is a counted layer. Wrestling sleeves mid-song is not a reveal.",
    safety: "Stay on your feet. Place the garment. Do not throw it at anyone. Practice the actual jacket or a robe.",
    cue: "Phrase. Sleeves. Place it. Phrase.",
    steps: [
      "Walk an 8 you already own in the jacket.",
      "On the next 8, slide one sleeve, then the other, without rushing.",
      "Place it on the chair or upstage on purpose.",
      "Walk the next 8 without it. Eyes up.",
    ],
    watchFor: ["Throwing", "Stuck in a sleeve and panicking", "Looking at the floor the whole peel"],
    voiceScript:
      "Jacket is a layer. Phrase. One sleeve. Other sleeve. Place it where you chose. Walk. If the jacket fights you, we wear a different jacket. We do not throw costume at the room.",
    diagram: "layer",
    practice: "Three peels with the real jacket or a robe. Full rest between.",
    passWhen: "The peel fits in one 8 and the garment has a home.",
    firstThen: { first: "Top peel you own", then: "Same count with sleeves" },
  }),
  skill({
    id: "pirouette",
    exerciseId: "pirouette",
    name: "Commercial pirouette",
    module: "Body",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "One clean turn both ways is a transition. Thirty-two fouettés are someone else's class.",
    safety: "Trainers first. Spot the wall. One turn. Both directions. Ankle roll is a stop. Heels only after the trainer version is quiet.",
    bothSides: true,
    cue: "Spot. One turn. Other way.",
    steps: [
      "Soft knees. Eyes on a wall spot.",
      "One slow turn. Land on two feet you can stand on.",
      "Other direction. Same number. No extra pretty-side turns.",
      "If it wobbles, make it a half turn until it does not.",
    ],
    watchFor: ["Chaining turns you do not own", "Only one direction", "Heels before the trainer turn is quiet"],
    voiceScript:
      "One turn. Spot the wall. Land. Other way. Same number. This is a transition, not a ballet exam. If you need heels to feel like a turn, you do not own the turn. Trainers first.",
    diagram: "phrase",
    practice: "Five turns each way. Rest. Five more slower.",
    passWhen: "You land on two quiet feet both directions.",
    firstThen: { first: "Passé balance", then: "Same passé into one turn" },
  }),
  skill({
    id: "tip-tray",
    exerciseId: "tip-tray",
    name: "Tip-tray phrase",
    module: "Club craft",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "The rail is a visit with an open palm, not a camp. A tray shape makes the invitation readable.",
    safety: "Tape line. Wall is the audience. Do not grab a person. House rules in a club override this drill.",
    cue: "Walk. Tray. Look. Leave.",
    steps: [
      "Walk the slow walk to the tape.",
      "Pause. Both hands or one as an open tray at hip height.",
      "Eye-line. Two counts. Receive, do not snatch.",
      "Leave to a corner or home. Do not camp.",
    ],
    watchFor: ["Camping the rail", "Grabbing", "Looking at the floor"],
    voiceScript:
      "Walk to the rail. Tray. Open palm. Look. Two counts. Leave. Visiting is expensive. Camping is needy. In a club the house rules win. At home the wall is your audience.",
    diagram: "hands",
    practice: "Six visits. Different exits each time.",
    passWhen: "Arrive, tray, leave — without speeding up.",
    firstThen: { first: "Rail approach", then: "Same visit with a tray shape" },
  }),
];
