export const NYX = {
  id: "nyx",
  name: "Nyx",
  fullName: "Nyx Vale",
  ageLabel: "adult, late 20s",
  role: "Stage and class instructor",
  look: "Photoreal studio stills: pale skin, long jet-black hair, blunt bangs, winged liner, matte black lipstick, silver septum ring, black sports bra and high-waisted yoga pants. Editorial plates are the same photographs with stage-lab type. Fictional adult instructor.",
  voice: {
    nameHints: ["Aria", "Jenny", "Ava", "Samantha", "Zira", "Female", "Woman"],
    rate: 0.82,
    pitch: 0.86,
    edgeVoice: "en-US-AriaNeural",
    edgeRate: "-12%",
    edgePitch: "-6Hz",
  },
  portrait: "/instructor/nyx-portrait.webp",
  plates: {
    portrait: "/instructor/plates/nyx-plate-portrait.webp",
    walk: "/instructor/plates/nyx-plate-walk.webp",
    wave: "/instructor/plates/nyx-plate-wave.webp",
    floor: "/instructor/plates/nyx-plate-walk.webp",
    chair: "/instructor/plates/nyx-plate-chair.webp",
    sit: "/instructor/plates/nyx-plate-sit.webp",
    pole: "/instructor/plates/nyx-plate-pole.webp",
    hang: "/instructor/plates/nyx-plate-hang.webp",
  },
  photos: {
    portrait: "/instructor/nyx-portrait.webp",
    walk: "/instructor/nyx-walk.webp",
    wave: "/instructor/nyx-wave.webp",
    chair: "/instructor/nyx-chair.webp",
    sit: "/instructor/nyx-sit.webp",
    pole: "/instructor/nyx-pole.webp",
    hang: "/instructor/nyx-hang.webp",
  },
} as const;
