export const NYX = {
  id: "nyx",
  name: "Nyx",
  fullName: "Nyx Vale",
  ageLabel: "adult, late 20s",
  role: "Stage and class instructor",
  look: "Photoreal 85mm studio stills of the same adult woman: porcelain skin, long jet-black hair, blunt bangs, heavy smoky eyes, winged liner, matte black lipstick, silver septum. Alluring, sexy, body-conscious posing in high-waisted black yoga pants. Editorial plates are those photographs with stage-lab type. Fictional adult instructor, late 20s.",
    voice: {
      nameHints: ["Aria", "Jenny", "Ava", "Samantha", "Zira", "Female", "Woman"],
      rate: 0.82,
      pitch: 0.86,
      edgeVoice: "en-US-AriaNeural",
      edgeRate: "-12%",
      edgePitch: "-6Hz",
    },
    portrait: "/instructor/nyx-portrait.webp?v=6",
    plates: {
      portrait: "/instructor/plates/nyx-plate-portrait.webp?v=6",
      walk: "/instructor/plates/nyx-plate-walk.webp?v=6",
      wave: "/instructor/plates/nyx-plate-wave.webp?v=6",
      floor: "/instructor/plates/nyx-plate-floor.webp?v=6",
      chair: "/instructor/plates/nyx-plate-chair.webp?v=6",
      sit: "/instructor/plates/nyx-plate-sit.webp?v=6",
      pole: "/instructor/plates/nyx-plate-pole.webp?v=6",
      hang: "/instructor/plates/nyx-plate-hang.webp?v=6",
      climb: "/instructor/plates/nyx-plate-climb.webp?v=6",
    },
    photos: {
      portrait: "/instructor/nyx-portrait.webp?v=6",
      walk: "/instructor/nyx-walk.webp?v=6",
      wave: "/instructor/nyx-wave.webp?v=6",
      chair: "/instructor/nyx-chair.webp?v=6",
      sit: "/instructor/nyx-sit.webp?v=6",
      pole: "/instructor/nyx-pole.webp?v=6",
      hang: "/instructor/nyx-hang.webp?v=6",
      floor: "/instructor/nyx-floor.webp?v=6",
      climb: "/instructor/nyx-climb.webp?v=6",
    },
} as const;
