import { NYX } from "./instructor";
import { makeSkill as skill } from "./skill-factory";
import type { Skill } from "./types";

/** Intermediate pole-class skills that the Pole class prep days actually program. */
export const POLE_CLASS_SKILLS: Skill[] = [
  skill({
    id: "pullup",
    exerciseId: "pullup",
    name: "Strict pull-up",
    module: "Class engine",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "12 min",
    why: "A strict chin-over-bar is the off-pole version of a climb. Kipping will not save you in class and it will cook the shoulder.",
    safety: "Dead hang to chin over the bar. No kip. Band or machine assist until you own five clean reps. Stop if the shoulder pinches.",
    cue: "Pack. Pull. Chin over. Down slow.",
    steps: [
      "Hang with shoulders packed — not a dump.",
      "Pull the elbows down. Chest toward the bar.",
      "Chin clears. Pause a count.",
      "Lower in 2–3 seconds to a hang you still own.",
      "If five strict reps are not there yet, keep the assist. That is the work.",
    ],
    watchFor: ["Kipping", "Half reps", "Shrugging into the ears", "Pain in the front of the shoulder"],
    voiceScript:
      "Strict pull-up. Pack the shoulders. Pull the elbows down. Chin over. Pause. Down slow. No kip. If you need a band, you need a band. Intermediate class does not grade your ego. It grades whether you can pull and then hang again.",
    diagram: "hang",
    photo: NYX.photos.hang,
    plate: NYX.plates.hang,
    practice: "Five quality reps or five assisted reps. Full rest. Repeat for the programmed sets.",
    passWhen: "Every rep starts from a packed hang and finishes with the chin clearly over.",
    firstThen: { first: "Active hang you own", then: "Same hang into a pull" },
  }),
  skill({
    id: "inverted-row",
    exerciseId: "inverted-row",
    name: "Inverted row",
    module: "Class engine",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "10 min",
    why: "The row is invert-prep at a friendlier angle. You learn to pull the chest through without leaving the floor.",
    safety: "Bar or rings at about hip height. Body long. Raise the feet to progress. Stop if the shoulder or low back dumps.",
    cue: "Long body. Chest to the bar.",
    steps: [
      "Set a bar or a sturdy table edge. Hang underneath, body long.",
      "Pack the shoulders. Squeeze the glutes so the hips do not sag.",
      "Pull the chest to the bar. Pause.",
      "Lower. Keep the same line.",
      "Feet farther out when this is easy. Feet closer or bent knees if it is not.",
    ],
    watchFor: ["Hips sagging", "Leading with the chin only", "Shrugging", "A bar that can roll"],
    voiceScript:
      "Inverted row. Long body. Hips stay. Chest to the bar — not just the chin. Pause. Lower. This is invert-prep you can do at home. If the bar can roll, pick a different bar. We do not practice on junk.",
    diagram: "hang",
    photo: NYX.photos.hang,
    plate: NYX.plates.hang,
    practice: "Two sets of six to ten clean reps. Rest. One more set if the shoulders are quiet.",
    passWhen: "The body stays a line and the chest actually arrives.",
    firstThen: { first: "Packed hang", then: "Same pack, pull the chest through" },
  }),
  skill({
    id: "repeat-hang",
    exerciseId: "active-hang-repeat",
    name: "Repeat active hangs",
    module: "Class engine",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "10 min",
    why: "Class is hang, spin, hang again. One hero hang that cooks the tendon is the wrong homework.",
    safety: "Active shoulders. Full rest between hangs. Stop if the elbow tendon is angry. Farmer carries if you need a swap.",
    cue: "Short hang. Full rest. Repeat.",
    steps: [
      "Pack the shoulders. Hang 10–25 seconds.",
      "Come down. Shake out. Full rest.",
      "Hang again. Same quality. Do not chase a personal-best time today.",
      "That is the class pattern: grip, skill, grip.",
    ],
    watchFor: ["Dumped shoulders", "Grinding to failure", "Skipping rest", "Elbow pain"],
    voiceScript:
      "Short hang. Full rest. Again. Intermediate class will ask you to hang, spin, and hang. One hero hang that fries the tendon helps no one. Pack the shoulders. Stop while it is still pretty. If the elbow talks, we carry instead.",
    diagram: "hang",
    photo: NYX.photos.hang,
    plate: NYX.plates.hang,
    practice: "Four short hangs with full rest. Same packed shape every time.",
    passWhen: "You can repeat a hang without the last one turning into a dump.",
    firstThen: { first: "One packed hang", then: "The same hang, four times, with rest" },
  }),
  skill({
    id: "hanging-tuck",
    exerciseId: "hanging-tuck",
    name: "Hanging tuck hold",
    module: "Invert-ready",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "8 min",
    why: "Knees to chest on a bar is invert-readiness. A handspring from a phone is how people get hurt.",
    safety: "No kip. No swing. Crash mat if you are over a hard floor. Skip if the shoulder or neck complains. Studio for anything off the floor that still scares you.",
    cue: "Knees up. Posterior tilt. Breathe.",
    steps: [
      "Pack the hang first.",
      "Knees to chest. Posterior tilt — tailbone under, not a banana back.",
      "Hold a range you can breathe in. Ten to twenty seconds is plenty.",
      "Lower the legs with control. This is not the invert yet.",
    ],
    watchFor: ["Kipping", "Swinging", "Neck cranking to 'see the ceiling'", "Pain in the shoulder"],
    voiceScript:
      "Hanging tuck. Pack first. Knees to chest. Tailbone under. Breathe. No kip. Ever. If you need to swing to get the knees up, the hold is not yours yet. We do not learn inverts from a phone on a carpet. Own this boring tuck.",
    diagram: "hang",
    photo: NYX.photos.hang,
    plate: NYX.plates.hang,
    practice: "Four holds. Full rest. Same packed hang every time.",
    passWhen: "You can hold a quiet tuck without a swing to get there.",
    firstThen: { first: "Packed dead hang", then: "Knees to chest in that hang" },
  }),
  skill({
    id: "pole-squat",
    exerciseId: "pole-squat-hold",
    name: "Pole squat hold",
    module: "Spins both sides",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "8 min",
    why: "Sitting the hips back with the pole in front is invert-prep that never leaves the floor. Class uses this shape constantly.",
    safety: "Pole in front. Hips back. Elbows pull down. Stop if the shoulder pinches. Both sides if you offset the feet.",
    bothSides: true,
    cue: "Hips back. Elbows down. Pole in front.",
    steps: [
      "Stand facing the pole. Hands high enough that the shoulders can pack.",
      "Sit the hips back as if a chair is behind you. Knees track the toes.",
      "Pull the elbows down the pole. Chest stays proud, not collapsed.",
      "Breathe. Stand. Switch the offset if your studio uses one.",
    ],
    watchFor: ["Shoulders in the ears", "Knees caving", "Turning it into a backbend", "Only one foot pattern"],
    voiceScript:
      "Pole squat. Hips back. Elbows down. The pole stays in front of you. This is invert-prep that never leaves the floor, which is why we like it. Breathe in the hold. If the shoulder pinches, we stop. Both offsets. Class will use this shape whether you like it or not.",
    diagram: "sit",
    photo: NYX.photos.pole,
    plate: NYX.plates.pole,
    practice: "Three holds of twenty to forty seconds. Rest. Other offset.",
    passWhen: "You can breathe in the bottom and stand without yanking the shoulders.",
    firstThen: { first: "Around-the-pole walk", then: "Same hands, sit the hips back" },
  }),
];
