import { EXOTIC_CLUB_SKILLS } from "./exotic-club-skills";
import { NYX } from "./instructor";
import { makeSkill as skill } from "./skill-factory";
import type { CourseId, Skill } from "./types";

const SKILLS_CORE: Skill[] = [
  skill({
    id: "walk",
    exerciseId: "performance-walk",
    name: "Performance walk",
    module: "Presence",
    courseId: "exotic_amateur_night",
    level: "foundation",
    durationLabel: "8–12 min",
    why: "Amateur night is won or lost in the first eight steps. A slow walk reads as expensive. A rushed walk reads as nervous.",
    safety: "Trainers first. Heels only after this walk is quiet in sneakers. Skip heels if the ankle rolls.",
    cue: "Slow. Tall. Pause.",
    steps: [
      "Stand with feet under the hips. Soft knees.",
      "Pick a spot on the far wall. That is your audience.",
      "Step. Heel then toe. Hips stay over the feet.",
      "Ribs over the pelvis. Do not lean the chest back.",
      "On four, pause in a pose you can hold and breathe.",
      "Turn. Walk back. Same speed.",
    ],
    watchFor: ["Rushing", "Ribs flaring", "Looking at the floor", "Collapsing the low back in the pose"],
    voiceScript:
      "Come here. We start with the walk. Soften your knees. Find a spot on the far wall — that is your audience. Step. Heel, then toe. Stay tall. Ribs over your pelvis. Do not rush me. On four, pause. Hold a pose you can breathe in. Then turn, and walk back just as slow. If you only own one thing tonight, own this.",
    diagram: "walk",
    photo: NYX.photos.walk,
    plate: NYX.plates.walk,
  }),
  skill({
    id: "eyeline",
    exerciseId: "hair-toss-eyeline",
    name: "Hair toss and eye-line",
    module: "Presence",
    courseId: "exotic_amateur_night",
    level: "foundation",
    durationLabel: "6–8 min",
    why: "A set without an eye-line is a rehearsal. The hair follows the torso. The neck does not whip.",
    safety: "Turn the head with the chest. No high-speed neck circles. Stop if you get dizzy.",
    cue: "Look. Then hair.",
    steps: [
      "Find your still spot on the wall.",
      "Turn the chest toward a second spot.",
      "Let the head follow the chest.",
      "Let the hair follow the head. Soft.",
      "Return to the first spot and hold two counts.",
    ],
    watchFor: ["Whipping the neck", "Eyes on the floor", "Hair covering the face the whole phrase"],
    voiceScript:
      "Look at me. Not the floor. Pick a still spot. Turn your chest first. Head follows. Hair follows last — soft, not a whip. Come back to that first spot and hold. Two counts. That is how a room believes you.",
    diagram: "walk",
    photo: NYX.photos.portrait,
    plate: NYX.plates.portrait,
  }),
  skill({
    id: "arms",
    exerciseId: "port-de-bras",
    name: "Arm pathways",
    module: "Presence",
    courseId: "exotic_amateur_night",
    level: "foundation",
    durationLabel: "6 min",
    why: "Arms frame the walk. Shrugged shoulders make the set look smaller.",
    safety: "Soft elbows. No behind-the-neck ports. Shoulders down.",
    cue: "Soft elbows. Quiet shoulders.",
    steps: [
      "Arms low, slightly in front of the body.",
      "Lift through the side without shrugging.",
      "Curve the path as if moving through water.",
      "Finish in a shape you can hold while you walk.",
    ],
    watchFor: ["Shrugging", "Locked elbows", "Arms behind the head"],
    voiceScript:
      "Arms next. Keep them in front of your body. Soft elbows. Lift without shrugging into your ears. Move as if the air is thick. Finish in a shape you can walk in. Pretty is optional. Quiet shoulders are not.",
    diagram: "walk",
    photo: NYX.photos.portrait,
    plate: NYX.plates.portrait,
  }),
  skill({
    id: "wave",
    exerciseId: "body-wave",
    name: "Standing body wave",
    module: "Body",
    courseId: "exotic_amateur_night",
    level: "foundation",
    durationLabel: "8 min",
    why: "The wave is the commercial body. Knees, hips, then chest — not a dumped low back.",
    safety: "Small range if the back is cranky. No neck rolls stacked on the wave.",
    cue: "Knees. Hips. Chest.",
    steps: [
      "Soft knees. Hands on a wall if you need the balance.",
      "Bend the knees a little.",
      "Send the hips forward, then back.",
      "Let the chest follow. Head stays long.",
      "Reverse. Slow.",
    ],
    watchFor: ["Hinging only at the low back", "Throwing the head", "Holding the breath"],
    voiceScript:
      "Body wave. Soften the knees. Hips first — forward, then back. Chest follows. Head stays long. Do not dump into your low back. Slow enough that I could count it. If it is ugly and controlled, we keep it. If it is pretty and painful, we throw it out.",
    diagram: "wave",
    photo: NYX.photos.wave,
    plate: NYX.plates.wave,
  }),
  skill({
    id: "hip8",
    exerciseId: "hip-figure-8",
    name: "Hip figure-8",
    module: "Body",
    courseId: "exotic_amateur_night",
    level: "foundation",
    durationLabel: "8 min",
    why: "Figure-eights are the floor-set and chair-set engine. The belt line draws the 8. The ribs stay quiet.",
    safety: "Soft knees. Stop if the SI joint or low back nags.",
    cue: "Belt draws the 8.",
    steps: [
      "Feet under the hips. Soft knees.",
      "Hands on the waist so you can feel the belt line.",
      "Draw a slow 8. One direction.",
      "Stop. Reverse.",
      "Keep the ribs stacked. The 8 is small.",
    ],
    watchFor: ["Ribs swaying", "Locked knees", "Going faster when it gets boring"],
    voiceScript:
      "Hands on your waist. The belt draws a slow eight. Ribs stay quiet. One direction. Stop. Other direction. Small is expensive. Big and sloppy is free, and we are not doing free.",
    diagram: "hip8",
    photo: NYX.photos.walk,
    plate: NYX.plates.wave,
  }),
  skill({
    id: "pulse",
    exerciseId: "hip-pulse",
    name: "Hip pulse",
    module: "Body",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "5 min",
    why: "A tiny glute pulse reads on stage. A lumbar pop does not last the week.",
    safety: "Posterior pulse from the glutes. Do not crank a backbend.",
    cue: "Tiny. From the glutes.",
    steps: [
      "Soft knees. Ribs down.",
      "Squeeze the glutes for a small pulse.",
      "Return. Do not bounce the spine.",
      "Try it standing, then kneeling on pads.",
    ],
    watchFor: ["Lumbar cranking", "Breath holding", "Making it bigger every rep"],
    voiceScript:
      "Tiny pulse. From the glutes, not the low back. Ribs down. Squeeze. Return. If you need a big backbend to feel it, you are in the wrong joint. Small. Musical. Stop while it is still pretty.",
    diagram: "hip8",
    photo: NYX.photos.walk,
    plate: NYX.plates.wave,
  }),
  skill({
    id: "chest",
    exerciseId: "chest-isolation",
    name: "Rib isolation",
    module: "Body",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "5 min",
    why: "Chest isolations sell a chorus without leaving your feet.",
    safety: "Slide the ribs. The neck does not drive. Stop if the neck complains.",
    cue: "Ribs slide. Neck quiet.",
    steps: [
      "Pelvis still. Hands on the ribs.",
      "Slide the cage left, then right.",
      "Then a small forward and back.",
      "Keep the chin long, not poked.",
    ],
    watchFor: ["Neck driving", "Pelvis joining in", "Holding the breath"],
    voiceScript:
      "Hands on your ribs. Pelvis stays. Slide the cage — left, right, a little forward, a little back. Your neck does not get to drive. This is a chorus you can do in heels later. Not today. Today we own the ribs.",
    diagram: "wave",
    photo: NYX.photos.portrait,
    plate: NYX.plates.portrait,
  }),
  skill({
    id: "seated-hips",
    exerciseId: "seated-hip-isolation",
    name: "Seated hip isolation",
    module: "Chair",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "Seated work is most of a commercial chair phrase. The pelvis moves. The torso stays invited, not collapsed.",
    safety: "Sit on the sit bones. No rounding into a painful low back.",
    cue: "Pelvis circles. Chest tall.",
    steps: [
      "Sit on the front edge of a sturdy chair.",
      "Tall chest. Hands on thighs or the seat.",
      "Circle the pelvis slowly. Both directions.",
      "Keep the feet on the floor unless a later drill says otherwise.",
    ],
    watchFor: ["Collapsing the chest", "Using the knees to fake the circle", "A wobbly chair"],
    voiceScript:
      "Sit on the front edge. Tall. The chair is furniture, not a person. Circle the pelvis. Slow. Both ways. Chest stays invited. If the chair wobbles, pick a heavier one. We do not perform on junk.",
    diagram: "chair",
    photo: NYX.photos.chair,
    plate: NYX.plates.chair,
  }),
  skill({
    id: "chair-approach",
    exerciseId: "chair-approach-straddle",
    name: "Chair approach and straddle",
    module: "Chair",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "10 min",
    why: "Approach, sit, open, close, stand — that is a whole verse with zero tricks.",
    safety: "Open the knees only as far as the hips stay stacked. Stand without yanking the knees.",
    cue: "Walk in. Sit. Open. Stand.",
    steps: [
      "Walk to the chair as if it is a mark on stage.",
      "Turn. Sit to the edge.",
      "Open the knees a comfortable amount. Hips stacked.",
      "Hands on thighs or the seat. One breath.",
      "Close. Stand. Walk off on the same slow tempo.",
    ],
    watchFor: ["Dropping into the chair", "Knees caving", "Rushing the stand-up"],
    voiceScript:
      "Walk to the chair like it is a mark. Turn. Sit to the edge — do not drop. Open the knees only as far as you stay stacked. One breath. Close. Stand. Walk off on the same slow tempo. This is a verse. Treat it like one.",
    diagram: "chair",
    photo: NYX.photos.chair,
    plate: NYX.plates.chair,
  }),
  skill({
    id: "chair-roll",
    exerciseId: "chair-body-roll",
    name: "Chair body roll",
    module: "Chair",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "A seated wave links the straddle to the stand without looking lost.",
    safety: "Sit bones stay on the seat. No neck-loaded drop off the back of the chair.",
    cue: "Roll through. Return tall.",
    steps: [
      "Sit on the edge. Hands on the seat or thighs.",
      "Tuck, then roll the spine through a small wave.",
      "Stack tall again.",
      "Repeat four times. Then stand.",
    ],
    watchFor: ["Sliding off the chair", "Throwing the head back", "Using momentum"],
    voiceScript:
      "Sit bones on the seat. Tuck. Roll through a small wave. Stack tall. Do not throw your head off the back of the chair. Four times. Then stand like you meant it.",
    diagram: "chair",
    photo: NYX.photos.chair,
    plate: NYX.plates.chair,
  }),
  skill({
    id: "descent",
    exerciseId: "floor-descent",
    name: "Floor descent",
    module: "Floor",
    courseId: "exotic_amateur_night",
    level: "foundation",
    durationLabel: "8 min",
    why: "Getting to the floor without a thud is commercial. Getting up the same way is how you leave.",
    safety: "Pad the knees. Use a hand. No dropping.",
    cue: "Lower. Do not drop.",
    steps: [
      "Stand. Touch a chair or the floor with one hand if you need it.",
      "Bend. Lower one knee, then the other, onto pads.",
      "Pause tall on the knees.",
      "Reverse: hand down, one foot, the other, stand.",
    ],
    watchFor: ["Dropping the last six inches", "Unpadded knees", "Rushing the stand"],
    voiceScript:
      "We go to the floor like we have time. Hand down if you need it. One knee. Other knee. Pads, please. Pause tall. Then reverse — one foot, the other, stand. If you drop, we do it again until you do not.",
    diagram: "floor",
    photo: NYX.photos.walk,
    plate: NYX.plates.floor,
  }),
  skill({
    id: "tabletop",
    exerciseId: "tabletop-pose",
    name: "Tabletop home base",
    module: "Floor",
    courseId: "exotic_amateur_night",
    level: "foundation",
    durationLabel: "6 min",
    why: "Tabletop is the floor phrase's home base. You leave it and you come back.",
    safety: "Fists or forearms if wrists complain. Knees padded.",
    cue: "Hands under. Knees under. Long spine.",
    steps: [
      "Hands under the shoulders, or forearms down.",
      "Knees under the hips, on pads.",
      "Long spine. Eyes on a spot, not the floor forever.",
      "Breathe. This is a hold, then a place to move from.",
    ],
    watchFor: ["Sinking in the shoulders", "Sitting back onto painful knees", "Collapsed wrists"],
    voiceScript:
      "Tabletop. Hands under shoulders — fists or forearms if the wrists talk. Knees under hips, on pads. Long spine. This is home base. You will leave it. You will come back. Do not sink into your shoulders.",
    diagram: "tabletop",
    photo: NYX.photos.walk,
    plate: NYX.plates.floor,
  }),
  skill({
    id: "knee-circle",
    exerciseId: "knee-walk-circle",
    name: "Knee walk",
    module: "Floor",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "6 min",
    why: "A slow knee circle is a chorus on the floor without a single trick.",
    safety: "Thick pads. Skip if the knees bark. Hips over the knees.",
    cue: "Pads. Slow circle. Both ways.",
    steps: [
      "Thick pads. Tabletop or upright kneeling.",
      "Walk the knees in a small circle.",
      "Reverse.",
      "Stop if anything sharp shows up in the knee.",
    ],
    watchFor: ["Sitting back into the knees", "Thin carpet as 'pads'", "Speed"],
    voiceScript:
      "Pads. I mean it. Walk the knees in a slow circle. Hips over the knees. Other way. If the knee is sharp, we skip this and keep the walk on your feet. Hero knees do not make a better set.",
    diagram: "knee",
    photo: NYX.photos.walk,
    plate: NYX.plates.floor,
  }),
  skill({
    id: "floor-roll",
    exerciseId: "floor-body-roll",
    name: "Floor roll and hip circle",
    module: "Floor",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "Floor rolls fill a verse. They do not need a neck bridge.",
    safety: "Pad knees. Forearms if wrists complain. No neck-loaded bridges.",
    cue: "Pad. Circle. No neck.",
    steps: [
      "Tabletop or forearm plank-lite on pads.",
      "Circle the hips slowly. Both ways.",
      "Add a body roll through the spine if the shoulders stay quiet.",
      "Return to tabletop. That is one phrase.",
    ],
    watchFor: ["Neck taking load", "Wrists collapsing", "Making it a flexibility contest"],
    voiceScript:
      "On the pads. Circle the hips. Both ways. If you add a roll, the neck does not load. No bridges. Come back to tabletop. That is a verse. Leave the circus for someone else's amateur night.",
    diagram: "floor",
    photo: NYX.photos.walk,
    plate: NYX.plates.floor,
  }),
  skill({
    id: "layers",
    exerciseId: "layer-change-flow",
    name: "Layer change",
    module: "Set craft",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "8 min",
    why: "Costume changes are transitions, not a panic. Practice one easy layer between phrases.",
    safety: "Stay on your feet or kneeling. No neck-loaded floor tricks while undressing.",
    cue: "Phrase. Layer. Phrase.",
    steps: [
      "Do an 8-count you already own.",
      "Take one easy layer off without rushing. Keep breathing.",
      "Do the next 8-count.",
      "If the layer fights you, simplify the garment. The show is not a costume tutorial.",
    ],
    watchFor: ["Rushing", "Looking at the garment the whole time", "New tricks during the change"],
    voiceScript:
      "Phrase. Then one layer. Then phrase. Do not rush the garment. If it fights you, wear something simpler. Eyes up. This is set craft, not a tutorial in how to wrestle a zipper. Breathe through it.",
    diagram: "layer",
    photo: NYX.photos.portrait,
    plate: NYX.plates.portrait,
  }),
  skill({
    id: "eight-count",
    exerciseId: "eight-count-phrase",
    name: "8-count phrase",
    module: "Set craft",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "10 min",
    why: "Commercial sets are counted. One 8 you own is worth more than ten tricks you almost own.",
    safety: "Only skills you already own. No new tricks inside the count.",
    cue: "Walk two. Wave two. Pose two. Turn two.",
    steps: [
      "Count out loud: 1 through 8.",
      "Walk for two. Wave for two. Pose for two. Turn for two.",
      "Rest a full 8.",
      "Repeat. Swap one piece only when the first version is boring.",
    ],
    watchFor: ["Going mute", "Stuffing extra moves", "Skipping the rest 8"],
    voiceScript:
      "Count out loud. Walk two. Wave two. Pose two. Turn two. That is your eight. Rest a full eight. If you stuff extra tricks in, you are not practicing a set. You are panicking. Own this phrase until it is boring. Boring is when we add.",
    diagram: "phrase",
    photo: NYX.photos.walk,
    plate: NYX.plates.walk,
  }),
  skill({
    id: "show-run",
    exerciseId: "show-set-run",
    name: "Song-length run-through",
    module: "Set craft",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "12–16 min",
    why: "Amateur night is a show, not a max-effort test. One song of skills you already own.",
    safety: "No new tricks in the run-through. Full rest between songs. Crash mat if the pole is in the set.",
    cue: "One song. Owned skills. Then stop.",
    steps: [
      "Pick a song you can finish.",
      "Map: walk on, one pole or chair skill, floor phrase, walk off.",
      "Run it. If something fails, keep the walk. Do not invent.",
      "Sit down a full song. Then one more run, or stop if week 12 is dress rehearsal.",
    ],
    watchFor: ["Adding a new invert", "Skipping rest", "Apologizing mid-set"],
    voiceScript:
      "One song. Skills you already own. Walk on. One skill on the pole or the chair. Floor phrase. Walk off. If something fails, keep walking. Do not invent. Rest a full song. Amateur night is a show, not a test. Then we stop while it is still clean.",
    diagram: "phrase",
    photo: NYX.photos.walk,
    plate: NYX.plates.walk,
  }),
  skill({
    id: "pole-walk",
    exerciseId: "pole-walk",
    name: "Around-the-pole walk",
    module: "Pole as prop",
    courseId: "exotic_amateur_night",
    level: "class",
    durationLabel: "8 min",
    why: "The pole is a partner and a prop. Walking it both ways is the first class skill and the first stage skill.",
    safety: "Shoulders active. Both directions. Studio or home pole. Static pole first.",
    bothSides: true,
    cue: "Inside high. Walk the circle. Switch.",
    steps: [
      "Inside hand high, outside hand at the chest.",
      "Walk a full circle. Shoulders not in the ears.",
      "Stop. Switch hands. Other direction.",
      "Keep the same slow walk you already own.",
    ],
    watchFor: ["Only one direction", "Shrugged shoulders", "Running the circle"],
    voiceScript:
      "Inside hand high. Outside hand at your chest. Walk the circle. Both ways. Do not shrug. Do not run. The pole is a prop tonight, not a gymnastics bar. Equal work. That is how you stay in class and on stage.",
    diagram: "polewalk",
    photo: NYX.photos.walk,
    plate: NYX.plates.walk,
  }),
  skill({
    id: "back-to-pole",
    exerciseId: "back-to-pole-pose",
    name: "Back-to-pole pose",
    module: "Pole as prop",
    courseId: "exotic_amateur_night",
    level: "show",
    durationLabel: "6 min",
    why: "A back-to-pole hold is a chorus you can breathe in. It photographs. It rests the grip.",
    safety: "Not a backbend contest. Both sides if the feet are offset.",
    cue: "Spine on the pole. Breathe.",
    steps: [
      "Stand with the spine along the pole.",
      "Stagger the feet. One or both hands on the pole at chest height.",
      "Soften the knees. Breathe.",
      "Step out and walk. Repeat on the other offset.",
    ],
    watchFor: ["Cranking a backbend", "Holding the breath", "Only one foot pattern"],
    voiceScript:
      "Spine along the pole. Feet staggered. Hands at the chest. Soften. Breathe. This is a hold, not a backbend contest. Step out. Walk. Other offset. Pretty is the breath, not the arch.",
    diagram: "polewalk",
    photo: NYX.photos.sit,
    plate: NYX.plates.sit,
  }),
  skill({
    id: "fireman",
    exerciseId: "fireman-spin",
    name: "Fireman spin",
    module: "Class spins",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "12 min",
    why: "Fireman both sides is the intermediate class gate. One-sided volume is an injury pattern.",
    safety: "Knee contact, not the ankle. Equal sets. Spot the landing. Static pole first.",
    bothSides: true,
    cue: "Knee on the pole. Equal sides.",
    steps: [
      "Inside arm high, outside arm at the chest.",
      "Contact the pole at the knees, not the ankle.",
      "Spin. Land on your feet.",
      "Same number on the other side. No extra 'good side' bonus sets.",
    ],
    watchFor: ["Ankle contact", "Only the good side", "Kipping into the spin"],
    voiceScript:
      "Fireman. Inside arm high. Knees on the pole — not the ankle. Land on your feet. Now the other side. Same number. I do not care which side is prettier. Intermediate class will use both. If you kip, we are done for the day.",
    diagram: "fireman",
    photo: NYX.photos.sit,
    plate: NYX.plates.sit,
  }),
  skill({
    id: "hook",
    exerciseId: "chair-spin",
    name: "Chair / hook spin",
    module: "Class spins",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "10 min",
    why: "Hook spins show up in every intermediate combo. Front-hook and back-hook both count. Both sides.",
    safety: "Hooked knee at mid-thigh, not jammed in the joint. Static first.",
    bothSides: true,
    cue: "Mid-thigh hook. Both sides.",
    steps: [
      "Find the hook at mid-thigh.",
      "Spin on a static pole.",
      "Land. Switch sides.",
      "Do not add spin-pole until the static version is quiet.",
    ],
    watchFor: ["Hook jammed in the knee joint", "Spin pole too early", "Skipping a side"],
    voiceScript:
      "Hook at mid-thigh, not stuffed in the joint. Static pole. Spin. Land. Other side. Spin pole is a later privilege. If the knee yells, we stop. Class is not a dare.",
    diagram: "fireman",
    photo: NYX.photos.sit,
    plate: NYX.plates.sit,
  }),
  skill({
    id: "sit",
    exerciseId: "pole-sit",
    name: "Pole sit",
    module: "Sit and climb",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "10 min",
    why: "A sit you can hover the hands from is class-ready. A sit you drop into from height is an ER story.",
    safety: "Crash mat. Thigh squeeze. Climb down. Do not drop from height to 'find' it.",
    bothSides: true,
    cue: "Squeeze. Lean. Climb down.",
    steps: [
      "Mat down.",
      "Squeeze the pole with the thighs. Lean back a little.",
      "Hands can hover when you own it — not on day one.",
      "Climb or hand-walk down. Then the other side if your studio uses a dominant sit.",
    ],
    watchFor: ["Dropping from height", "No mat", "Only the good side"],
    voiceScript:
      "Mat. Squeeze the pole with your thighs. Lean back a little. Hands stay until you own it. Then climb down. We do not drop from height to find a sit. That is not bravery. That is a bruise with a story you will not like.",
    diagram: "sit",
    photo: NYX.photos.sit,
    plate: NYX.plates.sit,
  }),
  skill({
    id: "climb",
    exerciseId: "basic-climb",
    name: "Basic climb",
    module: "Sit and climb",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "12 min",
    why: "Three controlled climbs off the floor is a common intermediate milestone. Height is vanity. Control is the class.",
    safety: "Knee clamp, stand, reach. Climb down. Crash mat. No sliding the full pole.",
    bothSides: true,
    cue: "Clamp. Stand. Reach. Down.",
    steps: [
      "Mat. Knee clamp.",
      "Stand on that clamp.",
      "Reach. Repeat. Quality over height.",
      "Climb down under control. Other side if your studio trains it.",
    ],
    watchFor: ["Sliding down", "Kipping", "Only one side", "Chasing height on tired grip"],
    voiceScript:
      "Clamp. Stand. Reach. That is a climb. Three controlled ones off the floor is the class target — not the ceiling. Climb down. If you slide, we lost the point. Mat stays. Both sides if your studio uses a dominant climb.",
    diagram: "climb",
    photo: NYX.photos.sit,
    plate: NYX.plates.sit,
  }),
  skill({
    id: "descent-pole",
    exerciseId: "controlled-descent",
    name: "Controlled descent",
    module: "Sit and climb",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "8 min",
    why: "Intermediate combos fail on the way down. Skin burns and dumped shoulders live here.",
    safety: "Hand-over-hand or a controlled thigh slide. Mat. Both sides.",
    bothSides: true,
    cue: "Down like you mean to stay intact.",
    steps: [
      "From a low sit or one climb.",
      "Lower hand-over-hand, or a short controlled slide you chose.",
      "Feet on the floor. Shake out.",
      "Other side.",
    ],
    watchFor: ["Uncontrolled full-pole slide", "No mat", "Fatigue reps"],
    voiceScript:
      "Down is a skill. Hand over hand, or a short slide you chose. Mat. If you torch your skin or dump the shoulder, we are not advancing. Other side. Intact is the aesthetic.",
    diagram: "climb",
    photo: NYX.photos.sit,
    plate: NYX.plates.sit,
  }),
  skill({
    id: "tuck",
    exerciseId: "pole-tuck-prep",
    name: "Invert prep tuck",
    module: "Invert-ready",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "8 min",
    why: "A hanging tuck is invert-readiness. A handspring from a phone is how people get hurt.",
    safety: "No kip. Studio spot. Skip if the shoulder or neck complains. Crash mat.",
    cue: "Knees up. No kip.",
    steps: [
      "Hanging tuck on a bar first if you have one: knees to chest, 10 seconds.",
      "On the pole: knees to chest, hips behind the pole, posterior tilt.",
      "Hold a range you can breathe in.",
      "Come down. This is not the invert yet.",
    ],
    watchFor: ["Kipping", "No spot", "Pain in the shoulder or neck", "Phone-learning a handspring"],
    voiceScript:
      "Tuck. Knees to chest. No kip. Ever. If you have a bar, own a ten second hanging tuck first. On the pole, hips stay behind. Pain in the shoulder or neck is a stop, not a badge. A spotted invert is studio-only. We do not learn that from a phone on a carpet.",
    diagram: "hang",
    photo: NYX.photos.sit,
    plate: NYX.plates.sit,
  }),
  skill({
    id: "hang",
    exerciseId: "dead-hang",
    name: "Active hang",
    module: "Class engine",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "8 min",
    why: "Grip is the first limiter in intermediate class. Repeat hangs beat one hero hang.",
    safety: "Active shoulders, not a full dump. Stop if the elbow tendon is angry.",
    cue: "Pack the shoulders. Repeat, don't hero.",
    steps: [
      "Hang with shoulders packed.",
      "Build time slowly. Several short hangs beat one grind.",
      "Full rest between.",
      "If the tendon nags, switch to farmer carries today.",
    ],
    watchFor: ["Dumped shoulders", "Grinding to failure every set", "Elbow pain"],
    voiceScript:
      "Active hang. Shoulders packed — not a dead dump. Short hangs. Full rest. Repeat. Intermediate class will ask you to hang, spin, and hang again. One hero hang that cooks the tendon helps no one. If the elbow talks, we carry instead.",
    diagram: "hang",
    photo: NYX.photos.portrait,
    plate: NYX.plates.portrait,
  }),
  skill({
    id: "capacity",
    exerciseId: "class-capacity-circuit",
    name: "Class capacity circuit",
    module: "Class engine",
    courseId: "pole_class_intermediate",
    level: "class",
    durationLabel: "20–30 min",
    why: "Intermediate classes last. Lungs and repeatability keep you in the combo when grip is tired.",
    safety: "This is work capacity, not invert-day smash intervals. Keep room to hang tomorrow.",
    cue: "Forty on. Twenty change. Repeat.",
    steps: [
      "40 seconds of squats, 20 seconds change.",
      "40 seconds of push-ups or incline push-ups.",
      "40 seconds of hollow or dead bug.",
      "40 seconds of a carry.",
      "Four to six rounds. Conversational as you can. Stop if form dumps.",
    ],
    watchFor: ["Turning it into a max metcon", "Pairing this with a heavy invert day", "No rest between rounds"],
    voiceScript:
      "Forty seconds on, twenty to change. Squats. Push-ups. Hollow. Carry. Four to six rounds. This is class lungs, not a punishment. If you cannot hang tomorrow, it was too hard. We are here to keep up with intermediate — not to win a garage Games.",
    diagram: "circuit",
    photo: NYX.photos.walk,
    plate: NYX.plates.walk,
  }),
];

export const SKILLS: Skill[] = [...SKILLS_CORE, ...EXOTIC_CLUB_SKILLS];

export function skillById(id: string) {
  return SKILLS.find((s) => s.id === id);
}

export function skillByExerciseId(exerciseId: string) {
  return SKILLS.filter((s) => s.exerciseId === exerciseId);
}

export function skillsForCourse(courseId: CourseId) {
  return SKILLS.filter((s) => s.courseId === courseId);
}
