import type { NyxStill } from "./instructor";

/** One still per skill so photo and plate never drift. */
export const SKILL_STILL = {
  walk: "walk",
  eyeline: "portrait",
  arms: "hands",
  wave: "wave",
  hip8: "grind",
  pulse: "grind",
  chest: "grind",
  "seated-hips": "chair",
  "chair-approach": "chair",
  "chair-roll": "chair",
  descent: "crawl",
  tabletop: "crawl",
  "knee-circle": "floor",
  "floor-roll": "floor",
  layers: "peel",
  "eight-count": "walk",
  "show-run": "walk",
  "pole-walk": "pole",
  "back-to-pole": "sit",
  fireman: "fireman",
  hook: "fireman",
  sit: "sit",
  climb: "climb",
  "descent-pole": "climb",
  tuck: "sit",
  hang: "hang",
  capacity: "walk",
  heels: "heels",
  hands: "hands",
  "stage-map": "heels",
  shimmy: "grind",
  grind: "grind",
  crawl: "crawl",
  mermaid: "mermaid",
  ladder: "crawl",
  "floor-grind": "grind",
  "reverse-chair": "chair",
  "lap-phrase": "chair",
  skirt: "peel",
  peel: "peel",
  "heel-floor": "mermaid",
  rail: "heels",
  "two-song": "heels",
  close: "walk",
  recovery: "portrait",
  "ankle-prep": "heels",
  "table-edge": "floor",
  "fan-kick": "kick",
  "jacket-peel": "peel",
  pirouette: "turn",
  "tip-tray": "hands",
  pullup: "hang",
  "inverted-row": "hang",
  "repeat-hang": "hang",
  "hanging-tuck": "hang",
  "pole-squat": "pole",
  olh: "hang",
  carousel: "pole",
  "climb-to-sit": "climb",
  "back-hook": "fireman",
} as const satisfies Record<string, NyxStill>;

export type SkillStillId = keyof typeof SKILL_STILL;

export function stillForSkill(id: string): NyxStill {
  return (SKILL_STILL as Record<string, NyxStill>)[id] ?? "portrait";
}
