import type { NyxStill } from "./instructor";

/** One still per skill so photo and plate never drift. */
export const SKILL_STILL = {
  walk: "nudb",
  eyeline: "nuda",
  arms: "hands",
  wave: "nudc",
  hip8: "nuda",
  pulse: "nuda",
  chest: "ntpb",
  "seated-hips": "ncha",
  "chair-approach": "ncha",
  "chair-roll": "nchb",
  descent: "nrec",
  tabletop: "nrec",
  "knee-circle": "nrea",
  "floor-roll": "nrea",
  layers: "ntpb",
  "eight-count": "nudb",
  "show-run": "nudb",
  "pole-walk": "pole",
  "back-to-pole": "npla",
  fireman: "fireman",
  hook: "fireman",
  sit: "sit",
  climb: "climb",
  "descent-pole": "climb",
  tuck: "sit",
  hang: "hang",
  capacity: "walk",
  heels: "nhea",
  hands: "hands",
  "stage-map": "nheb",
  shimmy: "ntpc",
  grind: "nuda",
  crawl: "nrec",
  mermaid: "nreb",
  ladder: "nrec",
  "floor-grind": "nrea",
  "reverse-chair": "nchb",
  "lap-phrase": "ncha",
  skirt: "ntpb",
  peel: "ntpb",
  "heel-floor": "nhea",
  rail: "nhea",
  "two-song": "nheb",
  close: "nudb",
  recovery: "nuda",
  "ankle-prep": "nhea",
  "table-edge": "nrea",
  "fan-kick": "kick",
  "jacket-peel": "ntpc",
  pirouette: "nheb",
  "tip-tray": "hands",
  pullup: "hang",
  "inverted-row": "hang",
  "repeat-hang": "hang",
  "hanging-tuck": "hang",
  "pole-squat": "pole",
  olh: "hang",
  carousel: "pole",
  "climb-to-sit": "climb",
  "back-hook": "fireman",
} as const satisfies Record<string, NyxStill>;

export type SkillStillId = keyof typeof SKILL_STILL;

export function stillForSkill(id: string): NyxStill {
  return (SKILL_STILL as Record<string, NyxStill>)[id] ?? "portrait";
}
