import type { Program } from "@/lib/types";
import { MOVEMENT_PROGRAMS } from "./movement";

const strengthPhases = [
  {
    weeks: [1, 2, 3, 4],
    name: "Accumulation",
    rpeAdjust: 0,
    setAdjust: 0,
    note: "Build volume at RPE 7. Learn the RIR scale. Leave 3 reps in the tank on main lifts.",
  },
  {
    weeks: [5, 6, 7, 8],
    name: "Intensification",
    rpeAdjust: 0.5,
    setAdjust: 0,
    note: "Same lifts, a bit closer to failure. RPE 7.5–8.5 on mains.",
  },
  {
    weeks: [9, 10, 11],
    name: "Peak",
    rpeAdjust: 1,
    setAdjust: -1,
    note: "Heavier, fewer sets. Practice heavy singles/doubles without grinding to failure every week.",
  },
  {
    weeks: [12],
    name: "Deload",
    rpeAdjust: -1.5,
    setAdjust: -1,
    note: "Cut load and sets. You should finish feeling springy, not destroyed.",
  },
];

const hypertrophyPhases = [
  {
    weeks: [1, 2, 3],
    name: "Wave 1",
    rpeAdjust: 0,
    setAdjust: 0,
    note: "Own the technique. Most working sets at RPE 7–8 (2–3 RIR).",
  },
  {
    weeks: [4],
    name: "Deload",
    rpeAdjust: -1,
    setAdjust: -1,
    note: "Drop a set and keep RPE ~6–7. Recover so the next wave grows.",
  },
  {
    weeks: [5, 6, 7],
    name: "Wave 2",
    rpeAdjust: 0.5,
    setAdjust: 0,
    note: "Nudge load or reps. Same movements so you can actually see progress.",
  },
  {
    weeks: [8],
    name: "Deload / test",
    rpeAdjust: -1,
    setAdjust: -1,
    note: "Optional easy PR on a top set, then back off. Do not junk-volume your way into a bad week.",
  },
];

export const PROGRAMS: Program[] = [
  {
    id: "powerlifting",
    name: "Powerlifting",
    tagline: "Squat, bench, deadlift — get stronger at the things that matter.",
    category: "Strength",
    daysPerWeek: 4,
    durationWeeks: 12,
    description:
      "A 12-week, four-day strength block. Competition lifts get weekly practice. Accessories stay joint-friendly. Progression is RPE-based, not a fixed percentage chart that ignores how you slept.",
    evidenceNote:
      "Strength is specific: you get better at the lifts you practice. Volume still grows muscle (Schoenfeld; Pelland 2024). Autoregulating load with RIR-RPE matches daily readiness (Helms, Zourdos).",
    recommendedFor: ["powerlifting", "general"],
    phases: strengthPhases,
    days: [
      {
        id: "pl-squat",
        name: "Squat day",
        focus: "Squat strength + posterior chain",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "back-squat", sets: 4, reps: "4-6", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "pause-squat", sets: 2, reps: "3-5", targetRpe: 7, priority: 2, role: "secondary", notes: "2-count pause. Teach position, not grind." },
          { exerciseId: "rdl", sets: 3, reps: "6-8", targetRpe: 7.5, priority: 2, role: "secondary" },
          { exerciseId: "walking-lunge", sets: 2, reps: "8/leg", targetRpe: 7, priority: 3, role: "accessory" },
          { exerciseId: "hanging-knee-raise", sets: 3, reps: "8-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "pl-bench",
        name: "Bench day",
        focus: "Horizontal press + upper back",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "bench-press", sets: 4, reps: "4-6", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "pause-bench", sets: 2, reps: "3-5", targetRpe: 7, priority: 2, role: "secondary" },
          { exerciseId: "chest-supported-row", sets: 4, reps: "8-10", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "db-shoulder-press", sets: 3, reps: "8-10", targetRpe: 7.5, priority: 3, role: "accessory" },
          { exerciseId: "cable-pushdown", sets: 3, reps: "10-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "pl-dead",
        name: "Deadlift day",
        focus: "Pull strength + hinges",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "conventional-deadlift", sets: 3, reps: "3-5", targetRpe: 7.5, priority: 1, role: "main", notes: "Trap-bar is a first-class substitute if your back prefers it." },
          { exerciseId: "front-squat", sets: 3, reps: "5-6", targetRpe: 7, priority: 2, role: "secondary" },
          { exerciseId: "leg-curl", sets: 3, reps: "8-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "lat-pulldown", sets: 3, reps: "8-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "pallof-press", sets: 3, reps: "8/side", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "pl-ohp",
        name: "Overhead + volume bench",
        focus: "Pressing volume and arms",
        kind: "lift",
        estimatedMinutes: 70,
        exercises: [
          { exerciseId: "ohp", sets: 4, reps: "5-6", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "close-grip-bench", sets: 3, reps: "6-8", targetRpe: 7.5, priority: 2, role: "secondary" },
          { exerciseId: "pullup", sets: 3, reps: "5-8", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "face-pull", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "prehab" },
          { exerciseId: "ez-curl", sets: 2, reps: "10-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
    ],
  },
  {
    id: "conjugate",
    name: "Westside-inspired conjugate",
    tagline: "Max effort + speed + repetition work. Four days. Rotate the main lift.",
    category: "Strength",
    daysPerWeek: 4,
    durationWeeks: 8,
    description:
      "Household-safe conjugate: one max-effort lower, one max-effort upper, one dynamic/rep lower, one dynamic/rep upper. The max-effort lift rotates each week so you are not grinding the same 1RM every Monday. Dynamic days use 50–70% moved fast — bands and specialty bars are optional, not required.",
    evidenceNote:
      "Zatsiorsky’s three methods (max, dynamic, repeated effort) are the spine. Frequent near-max work develops coordination; rotating the lift reduces accommodation. This is not a raw Westside circus of 28-inch boxes and reverse-hyper museums.",
    recommendedFor: ["powerlifting", "general"],
    phases: [
      { weeks: [1, 2, 3], name: "Wave A", rpeAdjust: 0, setAdjust: 0, note: "Learn the rotation. ME work is a hard single or triple at RPE 9, not a missed lift." },
      { weeks: [4], name: "Deload", rpeAdjust: -1.5, setAdjust: -1, note: "No true maxes. Speed work stays snappy." },
      { weeks: [5, 6, 7], name: "Wave B", rpeAdjust: 0.5, setAdjust: 0, note: "Same template, heavier accessories if recovery allows." },
      { weeks: [8], name: "Deload", rpeAdjust: -1, setAdjust: -1, note: "Reload before you start the next block." },
    ],
    days: [
      {
        id: "conj-me-lower",
        name: "Max effort lower",
        focus: "Rotating squat/pull max + posterior accessories",
        kind: "lift",
        estimatedMinutes: 80,
        exercises: [
          { exerciseId: "box-squat", sets: 1, reps: "1-3", targetRpe: 9, priority: 1, role: "main", notes: "Week rotation: box squat → pause squat → trap-bar deadlift → paused deadlift. Work up to a top set, then stop." },
          { exerciseId: "rdl", sets: 4, reps: "6-8", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "leg-curl", sets: 3, reps: "10-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "45-back-extension", sets: 3, reps: "10-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "hanging-knee-raise", sets: 3, reps: "8-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "conj-me-upper",
        name: "Max effort upper",
        focus: "Rotating press max + triceps / back",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "pause-bench", sets: 1, reps: "1-3", targetRpe: 9, priority: 1, role: "main", notes: "Week rotation: paused bench → close-grip bench → overhead press → incline DB press." },
          { exerciseId: "chest-supported-row", sets: 4, reps: "8-10", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "jm-press", sets: 3, reps: "6-8", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "db-lateral-raise", sets: 3, reps: "12-15", targetRpe: 8, priority: 4, role: "accessory" },
          { exerciseId: "face-pull", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "prehab" },
        ],
      },
      {
        id: "conj-de-lower",
        name: "Dynamic / rep lower",
        focus: "Speed squat + hypertrophy",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "back-squat", sets: 8, reps: "3", targetRpe: 6, priority: 1, role: "main", notes: "About 55–65% of a recent top set, moved FAST. Rest 45–60s. This is speed, not a grind." },
          { exerciseId: "bulgarian-split-squat", sets: 3, reps: "8/leg", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "hip-thrust", sets: 3, reps: "8-10", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "hip-abduction", sets: 2, reps: "12-15", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "conj-de-upper",
        name: "Dynamic / rep upper",
        focus: "Speed bench + repetition effort",
        kind: "lift",
        estimatedMinutes: 70,
        exercises: [
          { exerciseId: "bench-press", sets: 9, reps: "3", targetRpe: 6, priority: 1, role: "main", notes: "Comp grip, 55–65%, bar speed is the point. 9x3 is classic DE upper." },
          { exerciseId: "lat-pulldown", sets: 4, reps: "10-12", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "db-bench", sets: 3, reps: "10-12", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "cable-pushdown", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "hammer-curl", sets: 2, reps: "10-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
    ],
  },
  {
    id: "bro_split",
    name: "Classic bodybuilding split",
    tagline: "Chest, back, legs, shoulders, arms — old-school days, modern volumes.",
    category: "Hypertrophy",
    daysPerWeek: 5,
    durationWeeks: 8,
    description:
      "A five-day body-part split. Each muscle is trained hard once, so per-session volume is high enough to still land near 10+ weekly sets for the big groups.",
    evidenceNote:
      "When weekly sets are equated, frequency does not meaningfully change hypertrophy (Schoenfeld 2019). A bro split can grow muscle. It is just less forgiving if you miss a day — that muscle waits a week.",
    honestNote:
      "Upper/Lower or PPL usually recovers better and is less catastrophic if life steals a session. This split is here because you asked for it, and because some people just like a chest day.",
    recommendedFor: ["bodybuilding"],
    phases: hypertrophyPhases,
    days: [
      {
        id: "bro-chest",
        name: "Chest",
        focus: "Pecs + triceps press-through",
        kind: "lift",
        estimatedMinutes: 70,
        exercises: [
          { exerciseId: "bench-press", sets: 4, reps: "6-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "incline-db-press", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "machine-chest-press", sets: 3, reps: "10-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "cable-pushdown", sets: 3, reps: "10-15", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "overhead-cable-extension", sets: 2, reps: "10-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "bro-back",
        name: "Back",
        focus: "Lats and upper back",
        kind: "lift",
        estimatedMinutes: 70,
        exercises: [
          { exerciseId: "pullup", sets: 4, reps: "6-10", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "chest-supported-row", sets: 4, reps: "8-12", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "lat-pulldown", sets: 3, reps: "10-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "face-pull", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "prehab" },
          { exerciseId: "ez-curl", sets: 2, reps: "10-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "bro-legs",
        name: "Legs",
        focus: "Quads, glutes, hamstrings",
        kind: "lift",
        estimatedMinutes: 80,
        exercises: [
          { exerciseId: "back-squat", sets: 4, reps: "6-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "rdl", sets: 3, reps: "8-10", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "bulgarian-split-squat", sets: 3, reps: "8/leg", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "leg-curl", sets: 3, reps: "10-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "leg-extension", sets: 2, reps: "10-15", targetRpe: 8, priority: 4, role: "accessory" },
          { exerciseId: "calf-raise", sets: 3, reps: "10-15", targetRpe: 8, priority: 5, role: "accessory" },
        ],
      },
      {
        id: "bro-shoulders",
        name: "Shoulders",
        focus: "Delts without wrecking the joint",
        kind: "lift",
        estimatedMinutes: 65,
        exercises: [
          { exerciseId: "ohp", sets: 4, reps: "6-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "landmine-press", sets: 3, reps: "8-10", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "cable-lateral-raise", sets: 4, reps: "12-15", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "rear-delt-fly", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "face-pull", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "prehab" },
        ],
      },
      {
        id: "bro-arms",
        name: "Arms",
        focus: "Biceps and triceps — no bench dips",
        kind: "lift",
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "close-grip-bench", sets: 3, reps: "6-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "ez-curl", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "cable-pushdown", sets: 3, reps: "10-15", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "hammer-curl", sets: 3, reps: "10-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "overhead-cable-extension", sets: 2, reps: "10-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
    ],
  },
  {
    id: "ppl",
    name: "Push / Pull / Legs",
    tagline: "Hit each muscle twice a week without living in the gym.",
    category: "Hypertrophy",
    daysPerWeek: 6,
    durationWeeks: 8,
    description:
      "Six days that repeat as Push A, Pull A, Legs A, Push B, Pull B, Legs B. Higher frequency, moderate per-session volume. Also works as a 3-day repeating week if that is all the time you have.",
    evidenceNote:
      "Twice-weekly exposure makes it easier to accumulate 10–20 hard sets without 20-set death days. Frequency itself is not magic once volume is matched.",
    recommendedFor: ["bodybuilding", "general"],
    phases: hypertrophyPhases,
    days: [
      {
        id: "ppl-push-a",
        name: "Push A",
        focus: "Chest-primary push",
        kind: "lift",
        estimatedMinutes: 70,
        exercises: [
          { exerciseId: "bench-press", sets: 4, reps: "6-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "ohp", sets: 3, reps: "6-8", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "incline-db-press", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "cable-lateral-raise", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "cable-pushdown", sets: 3, reps: "10-15", targetRpe: 8, priority: 3, role: "accessory" },
        ],
      },
      {
        id: "ppl-pull-a",
        name: "Pull A",
        focus: "Vertical pull + biceps",
        kind: "lift",
        estimatedMinutes: 70,
        exercises: [
          { exerciseId: "pullup", sets: 4, reps: "5-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "chest-supported-row", sets: 4, reps: "8-10", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "face-pull", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "prehab" },
          { exerciseId: "ez-curl", sets: 3, reps: "8-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "dead-hang", sets: 3, reps: "20-40s", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "ppl-legs-a",
        name: "Legs A",
        focus: "Squat pattern + quads",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "back-squat", sets: 4, reps: "5-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "rdl", sets: 3, reps: "6-8", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "bulgarian-split-squat", sets: 3, reps: "8/leg", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "leg-extension", sets: 2, reps: "10-15", targetRpe: 8, priority: 4, role: "accessory" },
          { exerciseId: "calf-raise", sets: 3, reps: "10-15", targetRpe: 8, priority: 5, role: "accessory" },
        ],
      },
      {
        id: "ppl-push-b",
        name: "Push B",
        focus: "Shoulder-primary push",
        kind: "lift",
        estimatedMinutes: 65,
        exercises: [
          { exerciseId: "ohp", sets: 4, reps: "5-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "db-bench", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "landmine-press", sets: 3, reps: "8-10", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "db-lateral-raise", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "overhead-cable-extension", sets: 3, reps: "10-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "ppl-pull-b",
        name: "Pull B",
        focus: "Horizontal pull + rear delts",
        kind: "lift",
        estimatedMinutes: 70,
        exercises: [
          { exerciseId: "chest-supported-row", sets: 4, reps: "6-10", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "lat-pulldown", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "db-row", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "rear-delt-fly", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "hammer-curl", sets: 3, reps: "10-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "ppl-legs-b",
        name: "Legs B",
        focus: "Hinge + glutes",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "trap-bar-deadlift", sets: 3, reps: "5-6", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "hip-thrust", sets: 4, reps: "8-10", targetRpe: 8, priority: 1, role: "secondary" },
          { exerciseId: "leg-curl", sets: 3, reps: "8-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "walking-lunge", sets: 2, reps: "10/leg", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "hip-abduction", sets: 3, reps: "12-15", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
    ],
  },
  {
    id: "upper_lower",
    name: "Upper / Lower",
    tagline: "The best default for most humans with a job.",
    category: "General",
    daysPerWeek: 4,
    durationWeeks: 8,
    description:
      "Four days: Upper A, Lower A, Upper B, Lower B. Enough frequency for strength and hypertrophy, enough rest to recover. Start here if you are not sure.",
    evidenceNote:
      "Weekly volume drives hypertrophy more than split choice. Four days is enough to hit ~10+ sets per muscle with room for life.",
    recommendedFor: ["general", "bodybuilding", "powerlifting"],
    phases: hypertrophyPhases,
    days: [
      {
        id: "ul-upper-a",
        name: "Upper A",
        focus: "Horizontal push/pull",
        kind: "lift",
        estimatedMinutes: 70,
        exercises: [
          { exerciseId: "bench-press", sets: 4, reps: "5-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "chest-supported-row", sets: 4, reps: "6-10", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "db-shoulder-press", sets: 3, reps: "8-10", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "lat-pulldown", sets: 3, reps: "8-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "cable-pushdown", sets: 2, reps: "10-15", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "ul-lower-a",
        name: "Lower A",
        focus: "Squat + hinge",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "back-squat", sets: 4, reps: "5-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "rdl", sets: 3, reps: "6-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "bulgarian-split-squat", sets: 3, reps: "8/leg", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "leg-curl", sets: 2, reps: "10-12", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "pallof-press", sets: 3, reps: "8/side", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "ul-upper-b",
        name: "Upper B",
        focus: "Vertical push/pull",
        kind: "lift",
        estimatedMinutes: 70,
        exercises: [
          { exerciseId: "ohp", sets: 4, reps: "5-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "pullup", sets: 4, reps: "5-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "db-bench", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "db-row", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "face-pull", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "prehab" },
          { exerciseId: "ez-curl", sets: 2, reps: "10-12", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "ul-lower-b",
        name: "Lower B",
        focus: "Hinge + glutes",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "trap-bar-deadlift", sets: 3, reps: "4-6", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "hip-thrust", sets: 3, reps: "8-10", targetRpe: 8, priority: 1, role: "secondary" },
          { exerciseId: "leg-press", sets: 3, reps: "10-12", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "hip-abduction", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "calf-raise", sets: 3, reps: "10-15", targetRpe: 8, priority: 5, role: "accessory" },
        ],
      },
    ],
  },
  {
    id: "strength_endurance",
    name: "Strength + endurance",
    tagline: "Get strong and still be able to climb stairs without bargaining.",
    category: "Concurrent",
    daysPerWeek: 5,
    durationWeeks: 8,
    description:
      "Three lift days and two to three cardio days. Lift first if they ever share a day. Prefer a 3-hour gap. Explosive work is the quality most likely to suffer if you smash them together.",
    evidenceNote:
      "Schumann et al. 2022: concurrent aerobic + strength does not meaningfully blunt max strength or hypertrophy. Explosive strength is reduced, especially in the same session. Separate by ≥3 hours when you can.",
    recommendedFor: ["strength_endurance", "general"],
    phases: hypertrophyPhases,
    days: [
      {
        id: "se-lift-a",
        name: "Full-body lift A",
        focus: "Squat + press",
        kind: "lift",
        estimatedMinutes: 60,
        exercises: [
          { exerciseId: "back-squat", sets: 4, reps: "5-6", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "bench-press", sets: 4, reps: "5-6", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "chest-supported-row", sets: 3, reps: "8-10", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "pallof-press", sets: 3, reps: "8/side", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "se-z2-a",
        name: "Zone 2 A",
        focus: "Aerobic base",
        kind: "cardio",
        estimatedMinutes: 40,
        exercises: [
          { exerciseId: "zone2-bike", sets: 1, reps: "30-45 min", targetRpe: 5, priority: 1, role: "conditioning", notes: "Conversational. If this is the same day as lifting, lift first or wait 3 hours." },
        ],
      },
      {
        id: "se-lift-b",
        name: "Full-body lift B",
        focus: "Hinge + pull",
        kind: "lift",
        estimatedMinutes: 60,
        exercises: [
          { exerciseId: "trap-bar-deadlift", sets: 3, reps: "4-6", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "ohp", sets: 3, reps: "5-6", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "pullup", sets: 3, reps: "5-8", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "hip-thrust", sets: 3, reps: "8-10", targetRpe: 8, priority: 2, role: "accessory" },
        ],
      },
      {
        id: "se-intervals",
        name: "Intervals",
        focus: "VO2 / repeatability",
        kind: "cardio",
        estimatedMinutes: 35,
        exercises: [
          { exerciseId: "intervals", sets: 8, reps: "60s hard / 90s easy", targetRpe: 8, priority: 1, role: "conditioning", notes: "Do not stack this after a max lower-body day. Bike or rower preferred." },
        ],
      },
      {
        id: "se-lift-c",
        name: "Full-body lift C",
        focus: "Volume and accessories",
        kind: "lift",
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "goblet-squat", sets: 3, reps: "8-10", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "db-bench", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "db-row", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "farmer-carry", sets: 4, reps: "30-40 m", targetRpe: 7, priority: 3, role: "accessory" },
          { exerciseId: "easy-incline-walk", sets: 1, reps: "15-20 min", targetRpe: 4, priority: 5, role: "conditioning", notes: "Easy finish. Keep it. Shorten only if the feet are already cooked." },
        ],
      },
    ],
  },
  ...MOVEMENT_PROGRAMS,
  {
    id: "big_ass",
    name: "Big Ass Program",
    tagline: "Large, round, athletic glutes — built with more than one trendy lift.",
    category: "Specialization",
    daysPerWeek: 4,
    durationWeeks: 8,
    description:
      "Glute-priority training: squat or split-squat pattern, hip-extension hinge, horizontal thrust, abduction, and 45° extension. Upper body stays on maintenance so you can recover the work that actually grows the goal.",
    evidenceNote:
      "Plotkin 2023 (MRI): hip thrust ≈ squat for glute growth; squat wins for quads and adductors. Kassiano 2024: adding barbell hip thrusts on top of leg press + stiff-leg deadlift grew glute max more than those two alone. Variety beats hunting a single 'best' exercise. Target ~12–20 fractional hard sets/week for glutes.",
    recommendedFor: ["glute_specialization", "bodybuilding"],
    phases: hypertrophyPhases,
    days: [
      {
        id: "bap-lower-a",
        name: "Glute lower A",
        focus: "Thrust + squat",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "hip-thrust", sets: 4, reps: "6-8", targetRpe: 8, priority: 1, role: "main", notes: "Pause 1s at lockout. Ribs down." },
          { exerciseId: "back-squat", sets: 4, reps: "5-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "rdl", sets: 3, reps: "6-8", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "hip-abduction", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "cable-kickback", sets: 2, reps: "12-15", targetRpe: 8, priority: 5, role: "accessory", notes: "Isolation finish. Stays in the session." },
        ],
      },
      {
        id: "bap-upper-a",
        name: "Upper maintenance A",
        focus: "Push/pull so you still look like an athlete",
        kind: "lift",
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "bench-press", sets: 3, reps: "6-8", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "chest-supported-row", sets: 3, reps: "8-10", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "landmine-press", sets: 2, reps: "8-10", targetRpe: 7.5, priority: 3, role: "accessory" },
          { exerciseId: "face-pull", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "prehab" },
          { exerciseId: "cable-pushdown", sets: 2, reps: "10-15", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "bap-lower-b",
        name: "Glute lower B",
        focus: "Split squat + hinge + extension",
        kind: "lift",
        estimatedMinutes: 75,
        exercises: [
          { exerciseId: "bulgarian-split-squat", sets: 4, reps: "8/leg", targetRpe: 8, priority: 1, role: "main", notes: "Long stride, torso slightly forward." },
          { exerciseId: "db-hip-thrust", sets: 3, reps: "10-12", targetRpe: 8, priority: 1, role: "secondary" },
          { exerciseId: "single-leg-rdl", sets: 3, reps: "8/leg", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "45-back-extension", sets: 3, reps: "10-12", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "step-up", sets: 3, reps: "8/leg", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "glute-bridge", sets: 2, reps: "12/leg", targetRpe: 8, priority: 5, role: "accessory" },
        ],
      },
      {
        id: "bap-upper-b",
        name: "Upper maintenance B + glute finisher",
        focus: "Vertical pull/press, then leftover glute work. Every listed drill stays.",
        kind: "lift",
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "pullup", sets: 3, reps: "5-8", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "ohp", sets: 3, reps: "6-8", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "db-row", sets: 3, reps: "8-12", targetRpe: 7.5, priority: 2, role: "accessory" },
          { exerciseId: "hip-abduction", sets: 3, reps: "15-20", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "lateral-band-walk", sets: 2, reps: "12/side", targetRpe: 8, priority: 5, role: "accessory" },
        ],
      },
    ],
  },
];

export function getProgram(id: string) {
  return PROGRAMS.find((p) => p.id === id);
}