import type { Program, WeekPhase } from "@/lib/types";

const classPrepPhases: WeekPhase[] = [
  {
    weeks: [1, 2, 3],
    name: "Foundation",
    rpeAdjust: -0.5,
    setAdjust: 0,
    note: "Learn grips, walks, and hangs. Leave lots of reps in the tank. Equal work both sides.",
  },
  {
    weeks: [4, 5, 6],
    name: "Class skills",
    rpeAdjust: 0,
    setAdjust: 0,
    note: "Fireman, chair, sit, and climb become the session. Still no kipping. Crash mat for anything off the floor.",
  },
  {
    weeks: [7],
    name: "Invert-ready",
    rpeAdjust: 0.5,
    setAdjust: 0,
    note: "Tuck holds get honest. A spotted invert is optional and studio-only. Pain is a stop, not a badge.",
  },
  {
    weeks: [8],
    name: "Deload",
    rpeAdjust: -1,
    setAdjust: -1,
    note: "Cut volume. Keep the shapes you own. Show up to class less cooked.",
  },
];

const amateurPhases: WeekPhase[] = [
  {
    weeks: [1, 2, 3, 4],
    name: "Walk and floor",
    rpeAdjust: -0.5,
    setAdjust: 0,
    note: "Own the walk, body wave, and one spin. Heels are optional and later.",
  },
  {
    weeks: [5, 6, 7, 8],
    name: "Climb, sit, phrase",
    rpeAdjust: 0,
    setAdjust: 0,
    note: "Link a climb or sit to a spin and a floor phrase. Both sides. No new invert tricks.",
  },
  {
    weeks: [9, 10, 11],
    name: "Song-length sets",
    rpeAdjust: 0.5,
    setAdjust: 0,
    note: "2–3 minute run-throughs of skills you already own. Rest a full song between attempts.",
  },
  {
    weeks: [12],
    name: "Dress rehearsal",
    rpeAdjust: -1,
    setAdjust: -1,
    note: "Easy volume. One clean set. Then stop. Amateur night is a show, not a max-effort test.",
  },
];

const mobilityPhases: WeekPhase[] = [
  {
    weeks: [1, 2, 3],
    name: "Own the positions",
    rpeAdjust: 0,
    setAdjust: 0,
    note: "Range you can breathe in. No bouncing. Stop at stretch, not nerve zing.",
  },
  {
    weeks: [4],
    name: "Easy week",
    rpeAdjust: -1,
    setAdjust: -1,
    note: "Shorter holds. Keep the habit without hunting a PR pancake.",
  },
  {
    weeks: [5, 6, 7],
    name: "A little longer",
    rpeAdjust: 0,
    setAdjust: 0,
    note: "Same shapes. 30–45s holds. Still not a pre-lift static-stretch dump.",
  },
  {
    weeks: [8],
    name: "Easy / test range",
    rpeAdjust: -1,
    setAdjust: -1,
    note: "Note what got easier. Do not force a split video.",
  },
];

const ruckPhases: WeekPhase[] = [
  {
    weeks: [1, 2, 3, 4],
    name: "Pack and posture",
    rpeAdjust: 0,
    setAdjust: 0,
    note: "10–15% bodyweight, 20–40 minutes, conversational. Learn the pack, not hero load.",
  },
  {
    weeks: [5, 6, 7],
    name: "One variable",
    rpeAdjust: 0,
    setAdjust: 0,
    note: "Add either distance or ~5 lb — never both the same week. Hills stay lighter than the flat ruck.",
  },
  {
    weeks: [8],
    name: "Easy",
    rpeAdjust: -1,
    setAdjust: 0,
    note: "Shorter, lighter. Feet and Achilles need the down week.",
  },
];

export const MOVEMENT_PROGRAMS: Program[] = [
  {
    id: "pole_stage",
    name: "Pole class prep",
    tagline: "No-skill to class-ready: grip, spins, sit, climb, invert prep — both sides.",
    category: "Performance",
    daysPerWeek: 4,
    durationWeeks: 8,
    description:
      "Beginner-to-intermediate prep for a pole-fitness class. Two days are off-pole so you arrive with pull, push, and wrist capacity. Two days are on-pole skills (walk, fireman, chair, sit, climb, tuck prep). This does not replace a teacher, a crash mat, or equal work on both sides.",
    evidenceNote:
      "Pole injuries cluster at the shoulder, then wrist and hamstring (Lee 2022 ~8.95 injuries/1000 h; Nawrocka-type amateur surveys ~27% shoulder, ~12% wrist). Loaded internal rotation and front-split shapes are common mechanisms. Train both sides; progress climbs before inverts; no kipping.",
    honestNote:
      "If you do not have a pole, keep the off-pole days and do the skill days at the studio. Do not learn inverts from a phone on a carpet.",
    recommendedFor: ["pole_stage"],
    phases: classPrepPhases,
    days: [
      {
        id: "pole-pull",
        name: "Pull, grip, hang",
        focus: "The strength class actually uses",
        kind: "lift",
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "wrist-prep", sets: 1, reps: "2 min", targetRpe: 3, priority: 5, role: "prehab" },
          { exerciseId: "shoulder-cares", sets: 1, reps: "2 min", targetRpe: 3, priority: 5, role: "prehab" },
          { exerciseId: "pullup", sets: 4, reps: "3-8", targetRpe: 8, priority: 1, role: "main", notes: "Assisted is correct until 5 strict reps. No kip." },
          { exerciseId: "inverted-row", sets: 3, reps: "6-10", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "dead-hang", sets: 4, reps: "15-40s", targetRpe: 8, priority: 2, role: "accessory", notes: "Active shoulders. First limiter for most new pole athletes." },
          { exerciseId: "hanging-tuck", sets: 3, reps: "10-20s", targetRpe: 8, priority: 2, role: "accessory", notes: "Knees to chest, no swing. Invert-readiness." },
          { exerciseId: "hollow-hold", sets: 3, reps: "20-40s", targetRpe: 8, priority: 3, role: "accessory" },
        ],
      },
      {
        id: "pole-skills",
        name: "On-pole class skills",
        focus: "Walk, fireman, chair, sit, climb",
        kind: "mixed",
        estimatedMinutes: 55,
        exercises: [
          { exerciseId: "wrist-prep", sets: 1, reps: "2 min", targetRpe: 3, priority: 5, role: "prehab" },
          { exerciseId: "pole-walk", sets: 4, reps: "2 circles/side", targetRpe: 6, priority: 1, role: "main", notes: "Both directions. Static pole." },
          { exerciseId: "pole-squat-hold", sets: 3, reps: "20-40s", targetRpe: 7, priority: 2, role: "secondary" },
          { exerciseId: "fireman-spin", sets: 4, reps: "3-5/side", targetRpe: 7, priority: 1, role: "main", notes: "Knee contact, not ankle. Equal sides." },
          { exerciseId: "chair-spin", sets: 3, reps: "3-5/side", targetRpe: 7, priority: 2, role: "secondary" },
          { exerciseId: "pole-sit", sets: 4, reps: "10-20s", targetRpe: 8, priority: 2, role: "secondary", notes: "Mat underneath. Climb down." },
          { exerciseId: "basic-climb", sets: 4, reps: "1-3 climbs", targetRpe: 8, priority: 1, role: "main", notes: "Quality over height. Intermediate target: 3 controlled climbs." },
          { exerciseId: "pole-tuck-prep", sets: 3, reps: "5-15s", targetRpe: 8, priority: 3, role: "accessory", optional: true, notes: "Weeks 6–8. Studio spot. Skip if the shoulder pinches." },
        ],
      },
      {
        id: "pole-push",
        name: "Push and shoulder balance",
        focus: "The work that keeps you in class",
        kind: "lift",
        estimatedMinutes: 50,
        exercises: [
          { exerciseId: "pushup", sets: 3, reps: "6-12", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "landmine-press", sets: 3, reps: "8-10", targetRpe: 7.5, priority: 1, role: "main", notes: "Friendlier than a steep barbell press for irritated shoulders." },
          { exerciseId: "face-pull", sets: 4, reps: "12-15", targetRpe: 8, priority: 2, role: "prehab" },
          { exerciseId: "db-lateral-raise", sets: 3, reps: "12-15", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "pallof-press", sets: 3, reps: "8/side", targetRpe: 8, priority: 3, role: "accessory", notes: "Anti-rotation for spins." },
          { exerciseId: "doorway-pec", sets: 2, reps: "30s/side", targetRpe: 3, priority: 5, role: "prehab" },
        ],
      },
      {
        id: "pole-lower",
        name: "Legs, lines, hips",
        focus: "Sits, climbs, and split-prep without forcing",
        kind: "mixed",
        estimatedMinutes: 50,
        exercises: [
          { exerciseId: "hip-90-90", sets: 1, reps: "3 min", targetRpe: 3, priority: 5, role: "prehab" },
          { exerciseId: "rdl", sets: 3, reps: "6-8", targetRpe: 7.5, priority: 1, role: "main" },
          { exerciseId: "bulgarian-split-squat", sets: 3, reps: "8/leg", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "hip-thrust", sets: 3, reps: "8-10", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "adductor-rock", sets: 2, reps: "8/side", targetRpe: 5, priority: 3, role: "prehab", notes: "Split-prep. Do not chase a painful pancake." },
          { exerciseId: "side-plank", sets: 3, reps: "20-40s/side", targetRpe: 8, priority: 4, role: "accessory" },
        ],
      },
    ],
  },
  {
    id: "pole_amateur_night",
    name: "Couch to amateur night",
    tagline: "Walk, floor, basic spins, sit, climb — a short set you can actually finish.",
    category: "Performance",
    daysPerWeek: 4,
    durationWeeks: 12,
    description:
      "From baseline to a basic amateur-night set: performance walk, body wave, floorwork, fireman and chair spins, a sit, a climb, and a 2–3 minute run-through. Costume layers are practiced as calm transitions, not a script. You still need a pole, a mat, and preferably a teacher to check climbs.",
    evidenceNote:
      "Amateur sets fail on grip, aerobic repeatability, and one-sided spinning — not on missing a handspring. Lee 2022: shoulder and hamstring injuries dominate; splits and loaded internal rotation are common mechanisms. Keep inverts out of the show until they are boring in class.",
    honestNote:
      "This is athletic set-craft for an adult club set. It will not make you a featured dancer in 12 weeks, and it will not teach inverts safely from a phone. Skip heels until the walk is quiet in trainers.",
    recommendedFor: ["pole_stage"],
    phases: amateurPhases,
    days: [
      {
        id: "am-floor",
        name: "Walk and floor",
        focus: "The part of the set that is not tricks",
        kind: "mixed",
        estimatedMinutes: 40,
        exercises: [
          { exerciseId: "wrist-prep", sets: 1, reps: "2 min", targetRpe: 3, priority: 5, role: "prehab" },
          { exerciseId: "short-foot", sets: 2, reps: "8/side", targetRpe: 4, priority: 5, role: "prehab" },
          { exerciseId: "performance-walk", sets: 4, reps: "60s", targetRpe: 5, priority: 1, role: "main", notes: "Slow. Pose you can hold. Trainers first." },
          { exerciseId: "body-wave", sets: 3, reps: "8", targetRpe: 6, priority: 2, role: "secondary" },
          { exerciseId: "floor-body-roll", sets: 3, reps: "4/side", targetRpe: 6, priority: 2, role: "secondary", notes: "Pad knees. Forearms if wrists complain." },
          { exerciseId: "port-de-bras", sets: 3, reps: "45s", targetRpe: 4, priority: 3, role: "accessory" },
          { exerciseId: "layer-change-flow", sets: 4, reps: "1 layer", targetRpe: 4, priority: 3, role: "accessory", notes: "Between phrases, not in a rush." },
        ],
      },
      {
        id: "am-spins",
        name: "Pole spins",
        focus: "Fireman and chair you can land",
        kind: "mixed",
        estimatedMinutes: 45,
        exercises: [
          { exerciseId: "pole-walk", sets: 3, reps: "2 circles/side", targetRpe: 6, priority: 1, role: "main" },
          { exerciseId: "fireman-spin", sets: 5, reps: "3-5/side", targetRpe: 7, priority: 1, role: "main", notes: "Equal sides. Static pole." },
          { exerciseId: "chair-spin", sets: 4, reps: "3-5/side", targetRpe: 7, priority: 1, role: "main" },
          { exerciseId: "pole-sit", sets: 4, reps: "8-20s", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "show-set-run", sets: 2, reps: "90s", targetRpe: 6, priority: 3, role: "conditioning", optional: true, notes: "Walk + one spin + pose. Save full songs for weeks 9–11." },
        ],
      },
      {
        id: "am-engine",
        name: "Off-pole engine",
        focus: "Grip, pull, legs so the set does not die at 0:90",
        kind: "lift",
        estimatedMinutes: 50,
        exercises: [
          { exerciseId: "pullup", sets: 3, reps: "3-8", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "dead-hang", sets: 3, reps: "15-40s", targetRpe: 8, priority: 2, role: "accessory" },
          { exerciseId: "pushup", sets: 3, reps: "6-12", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "hip-thrust", sets: 3, reps: "8-12", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "hollow-hold", sets: 3, reps: "20-40s", targetRpe: 8, priority: 3, role: "accessory" },
          { exerciseId: "farmer-carry", sets: 3, reps: "30-40 m", targetRpe: 7, priority: 3, role: "accessory" },
        ],
      },
      {
        id: "am-show",
        name: "Climb and show lab",
        focus: "Link the set, then stop",
        kind: "mixed",
        estimatedMinutes: 45,
        exercises: [
          { exerciseId: "basic-climb", sets: 4, reps: "1-3 climbs", targetRpe: 8, priority: 1, role: "main", notes: "Down under control. Mat." },
          { exerciseId: "pole-sit", sets: 3, reps: "10-20s", targetRpe: 8, priority: 2, role: "secondary" },
          { exerciseId: "fireman-spin", sets: 3, reps: "3/side", targetRpe: 7, priority: 2, role: "secondary" },
          { exerciseId: "show-set-run", sets: 3, reps: "2-3 min", targetRpe: 7, priority: 1, role: "conditioning", notes: "Only skills you already own. Full rest between songs." },
          { exerciseId: "layer-change-flow", sets: 2, reps: "1 layer", targetRpe: 4, priority: 4, role: "accessory" },
          { exerciseId: "legs-up-wall", sets: 1, reps: "3 min", targetRpe: 2, priority: 5, role: "prehab" },
        ],
      },
    ],
  },
  {
    id: "home_yoga",
    name: "Home yoga",
    tagline: "Five different at-home sessions: morning, strength, hips, restore, balance.",
    category: "Movement",
    daysPerWeek: 5,
    durationWeeks: 8,
    description:
      "A weekly rotation you can do on a mat: easy morning joints, a standing strength flow, hip and hamstring work, a restore day, and a balance/twist day. Props (wall, pillow, chair) beat forcing range. This is not a flexibility contest and not a substitute for care if pain is sharp or radiating.",
    evidenceNote:
      "Mix loading (standing poses, chair, planks) with restore. For backs, hinge from the hips and support the torso — do not yank the lumbar spine into a deep fold. Wrist-heavy poses get a wall or fist option. Static stretching here is the session, not a pre-max-lift ritual (Kay & Blazevich 2012).",
    honestNote:
      "Skip headstands, full wheels, and lotus hunting. If a pose makes the wrists, knees, or back bark, change it — that is the program working, not you failing yoga.",
    recommendedFor: ["general", "pole_stage"],
    phases: mobilityPhases,
    days: [
      {
        id: "yoga-morning",
        name: "Morning joints",
        focus: "Wake up without a workout hangover",
        kind: "mobility",
        estimatedMinutes: 25,
        exercises: [
          { exerciseId: "cat-cow-flow", sets: 2, reps: "8", targetRpe: 3, priority: 1, role: "main" },
          { exerciseId: "shoulder-cares", sets: 1, reps: "2 min", targetRpe: 3, priority: 2, role: "prehab" },
          { exerciseId: "bird-dog", sets: 2, reps: "6/side", targetRpe: 5, priority: 2, role: "secondary" },
          { exerciseId: "lunge-hip-flexor", sets: 2, reps: "30s/side", targetRpe: 4, priority: 3, role: "accessory" },
          { exerciseId: "down-dog", sets: 2, reps: "30s", targetRpe: 4, priority: 3, role: "accessory", notes: "Bent knees. Wall dog if wrists complain." },
          { exerciseId: "supported-child", sets: 1, reps: "60s", targetRpe: 2, priority: 5, role: "prehab" },
        ],
      },
      {
        id: "yoga-strength",
        name: "Standing strength flow",
        focus: "Legs and trunk you can use tomorrow",
        kind: "mixed",
        estimatedMinutes: 35,
        exercises: [
          { exerciseId: "chair-pose", sets: 3, reps: "30-45s", targetRpe: 7, priority: 1, role: "main" },
          { exerciseId: "warrior-2", sets: 3, reps: "30s/side", targetRpe: 6, priority: 1, role: "main" },
          { exerciseId: "bodyweight-squat", sets: 3, reps: "8-12", targetRpe: 7, priority: 2, role: "secondary" },
          { exerciseId: "plank", sets: 3, reps: "20-40s", targetRpe: 7, priority: 2, role: "secondary", notes: "Fists or forearms if wrists complain." },
          { exerciseId: "glute-bridge", sets: 3, reps: "8-12", targetRpe: 7, priority: 3, role: "accessory" },
          { exerciseId: "bird-dog", sets: 2, reps: "6/side", targetRpe: 5, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "yoga-hips",
        name: "Hips and hamstrings",
        focus: "Range without a rounded spine",
        kind: "mobility",
        estimatedMinutes: 30,
        exercises: [
          { exerciseId: "hip-90-90", sets: 2, reps: "45s/side", targetRpe: 4, priority: 1, role: "main" },
          { exerciseId: "half-kneeling-hamstring", sets: 3, reps: "30-45s/side", targetRpe: 4, priority: 1, role: "main" },
          { exerciseId: "lunge-hip-flexor", sets: 3, reps: "30-45s/side", targetRpe: 4, priority: 2, role: "secondary" },
          { exerciseId: "adductor-rock", sets: 2, reps: "8/side", targetRpe: 4, priority: 2, role: "secondary" },
          { exerciseId: "pancake-block", sets: 2, reps: "30s", targetRpe: 4, priority: 4, role: "accessory", optional: true, notes: "Sit on a towel. Stop at stretch, not nerve pain." },
          { exerciseId: "legs-up-wall", sets: 1, reps: "3 min", targetRpe: 2, priority: 5, role: "prehab" },
        ],
      },
      {
        id: "yoga-restore",
        name: "Restore",
        focus: "Downshift. No hero poses.",
        kind: "mobility",
        estimatedMinutes: 25,
        exercises: [
          { exerciseId: "supported-child", sets: 2, reps: "90s", targetRpe: 2, priority: 1, role: "main" },
          { exerciseId: "legs-up-wall", sets: 2, reps: "3 min", targetRpe: 2, priority: 1, role: "main" },
          { exerciseId: "thoracic-opener", sets: 2, reps: "6/side", targetRpe: 3, priority: 2, role: "secondary" },
          { exerciseId: "doorway-pec", sets: 2, reps: "30s/side", targetRpe: 3, priority: 3, role: "accessory" },
          { exerciseId: "short-foot", sets: 2, reps: "8", targetRpe: 3, priority: 4, role: "prehab" },
        ],
      },
      {
        id: "yoga-balance",
        name: "Balance and easy twist",
        focus: "Single-leg calm, not circus",
        kind: "mobility",
        estimatedMinutes: 30,
        exercises: [
          { exerciseId: "passe-balance", sets: 3, reps: "20-40s/side", targetRpe: 5, priority: 1, role: "main" },
          { exerciseId: "warrior-2", sets: 2, reps: "30s/side", targetRpe: 5, priority: 2, role: "secondary" },
          { exerciseId: "bird-dog", sets: 3, reps: "6/side", targetRpe: 5, priority: 2, role: "secondary" },
          { exerciseId: "cat-cow-flow", sets: 2, reps: "6", targetRpe: 3, priority: 3, role: "accessory", notes: "Thread-the-needle stays small." },
          { exerciseId: "down-dog", sets: 2, reps: "30s", targetRpe: 4, priority: 3, role: "accessory" },
          { exerciseId: "supported-child", sets: 1, reps: "60s", targetRpe: 2, priority: 5, role: "prehab" },
        ],
      },
    ],
  },
  {
    id: "smart_stretch",
    name: "Smart stretch",
    tagline: "ROM with ergonomics: hinge, breathe, 30–45s, no bounce, no nerve zing.",
    category: "Movement",
    daysPerWeek: 3,
    durationWeeks: 8,
    description:
      "Three stretch sessions: hips/split-prep, shoulders/thoracic, and calves/wrists/feet. Holds are 30–45 seconds, 2–4 rounds, on tissue that is already warm. This is for range of motion — do not park 60+ second static stretches immediately before a heavy or explosive lift.",
    evidenceNote:
      "Kay & Blazevich 2012: static stretch ≥60s per muscle before max strength/power is the dose most likely to reduce force; <45s is usually quiet. Behm et al. 2016: if you stretch before sport, follow with dynamic work. ACSM flexibility: 2–3 days/week, 10–30s (we use 30–45s when ROM is the goal). Much of 'gaining flexibility' is stretch tolerance (Weppler 2010), not magic longer muscles overnight.",
    honestNote:
      "Stretching is not an injury-prevention spell for a sport you under-recover. Pole splits still need hamstring capacity plus strength. Nerve pain, numbness, or sharp joint pain is a stop.",
    recommendedFor: ["general", "pole_stage"],
    phases: mobilityPhases,
    days: [
      {
        id: "stretch-hips",
        name: "Hips and split-prep",
        focus: "Hip hinge, not a rounded spine",
        kind: "mobility",
        estimatedMinutes: 30,
        exercises: [
          { exerciseId: "bodyweight-squat", sets: 2, reps: "8", targetRpe: 4, priority: 5, role: "prehab", notes: "Warm the hips first. This is not a squat PR." },
          { exerciseId: "half-kneeling-hamstring", sets: 3, reps: "30-45s/side", targetRpe: 4, priority: 1, role: "main", notes: "Long spine. Stretch in the thigh, not the low back." },
          { exerciseId: "couch-stretch", sets: 3, reps: "30-45s/side", targetRpe: 4, priority: 1, role: "main", notes: "Glute on, pelvis tucked slightly so the lumbar spine does not crank." },
          { exerciseId: "hip-90-90", sets: 3, reps: "30-45s/side", targetRpe: 4, priority: 2, role: "secondary" },
          { exerciseId: "adductor-rock", sets: 3, reps: "8/side", targetRpe: 4, priority: 2, role: "secondary" },
          { exerciseId: "pancake-block", sets: 2, reps: "30s", targetRpe: 4, priority: 4, role: "accessory", optional: true },
        ],
      },
      {
        id: "stretch-upper",
        name: "Shoulders and thoracic",
        focus: "In front of the body, never behind the neck",
        kind: "mobility",
        estimatedMinutes: 25,
        exercises: [
          { exerciseId: "shoulder-cares", sets: 2, reps: "5/side", targetRpe: 3, priority: 1, role: "main" },
          { exerciseId: "thoracic-opener", sets: 3, reps: "6/side", targetRpe: 4, priority: 1, role: "main" },
          { exerciseId: "doorway-pec", sets: 3, reps: "30s/side", targetRpe: 4, priority: 2, role: "secondary", notes: "Elbow at or below shoulder height." },
          { exerciseId: "cat-cow-flow", sets: 2, reps: "8", targetRpe: 3, priority: 3, role: "accessory" },
          { exerciseId: "wrist-prep", sets: 2, reps: "60s", targetRpe: 3, priority: 3, role: "prehab", notes: "Slow flexion/extension. Pole and yoga load these joints." },
        ],
      },
      {
        id: "stretch-lower-leg",
        name: "Calves, feet, easy restore",
        focus: "What heels, ballet, and rucks actually need",
        kind: "mobility",
        estimatedMinutes: 25,
        exercises: [
          { exerciseId: "calf-wall", sets: 3, reps: "30-45s/side", targetRpe: 4, priority: 1, role: "main", notes: "Straight knee and bent knee both." },
          { exerciseId: "short-foot", sets: 3, reps: "8/side", targetRpe: 4, priority: 2, role: "secondary" },
          { exerciseId: "half-kneeling-hamstring", sets: 2, reps: "30s/side", targetRpe: 4, priority: 3, role: "accessory" },
          { exerciseId: "legs-up-wall", sets: 1, reps: "3 min", targetRpe: 2, priority: 4, role: "prehab" },
        ],
      },
    ],
  },
  {
    id: "barre",
    name: "Barre (chair is fine)",
    tagline: "Small range, honest turnout, glutes and calves without a mirrored cult.",
    category: "Movement",
    daysPerWeek: 3,
    durationWeeks: 8,
    description:
      "Three at-home barre sessions using a chair or counter: pliés and pulses, standing glute/attitude work, and calf/balance. Turnout is whatever your hips can control — usually about 45°, not 180°. Knees track toes. This is muscle work, not a ballet exam.",
    evidenceNote:
      "IADMS turnout paper: do not force the feet and pronate to fake rotation. Knees follow the toes. Small-range pulses still add up — fatigue is when alignment usually breaks, so stop the set there.",
    recommendedFor: ["general", "pole_stage"],
    phases: mobilityPhases,
    days: [
      {
        id: "barre-lower",
        name: "Plié and pulse",
        focus: "Legs that stay stacked",
        kind: "mixed",
        estimatedMinutes: 35,
        exercises: [
          { exerciseId: "short-foot", sets: 1, reps: "8", targetRpe: 3, priority: 5, role: "prehab" },
          { exerciseId: "plie-first", sets: 4, reps: "10-12", targetRpe: 7, priority: 1, role: "main", notes: "Parallel, then a small turnout you can keep." },
          { exerciseId: "barre-pulse", sets: 3, reps: "20-30s", targetRpe: 8, priority: 1, role: "main" },
          { exerciseId: "releve-calf", sets: 3, reps: "10-15", targetRpe: 7, priority: 2, role: "secondary" },
          { exerciseId: "glute-bridge", sets: 3, reps: "10-12", targetRpe: 7, priority: 3, role: "accessory" },
        ],
      },
      {
        id: "barre-seat",
        name: "Seat and line",
        focus: "Glutes without a tucked-under spine",
        kind: "mixed",
        estimatedMinutes: 35,
        exercises: [
          { exerciseId: "attitude-lift", sets: 3, reps: "8-12/side", targetRpe: 7, priority: 1, role: "main" },
          { exerciseId: "barre-pulse", sets: 3, reps: "20-30s", targetRpe: 8, priority: 2, role: "secondary", notes: "Hinge slightly if the low back grips in upright pulses." },
          { exerciseId: "side-plank", sets: 3, reps: "20-30s/side", targetRpe: 7, priority: 2, role: "secondary" },
          { exerciseId: "port-de-bras", sets: 3, reps: "45s", targetRpe: 4, priority: 3, role: "accessory" },
          { exerciseId: "plie-first", sets: 2, reps: "8", targetRpe: 6, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "barre-balance",
        name: "Relevé and balance",
        focus: "Feet and single-leg calm",
        kind: "mixed",
        estimatedMinutes: 30,
        exercises: [
          { exerciseId: "calf-wall", sets: 2, reps: "30s/side", targetRpe: 3, priority: 5, role: "prehab" },
          { exerciseId: "releve-calf", sets: 4, reps: "8-12", targetRpe: 7, priority: 1, role: "main" },
          { exerciseId: "passe-balance", sets: 3, reps: "20-40s/side", targetRpe: 6, priority: 1, role: "main" },
          { exerciseId: "tendu-box", sets: 3, reps: "8/direction", targetRpe: 5, priority: 2, role: "secondary" },
          { exerciseId: "short-foot", sets: 2, reps: "8", targetRpe: 4, priority: 4, role: "prehab" },
        ],
      },
    ],
  },
  {
    id: "ballet_basics",
    name: "Ballet basics",
    tagline: "Plié, tendu, relevé, passé — functional balance and a smoother walk.",
    category: "Movement",
    daysPerWeek: 3,
    durationWeeks: 8,
    description:
      "Household ballet for people who want better balance and cleaner walking, including pole/stage walk. Barre (or a chair): plié, tendu, relevé. Centre: passé balance and a slow waltz walk. Turnout is hip-limited. No 180° feet, no bouncing, no behind-the-neck ports.",
    evidenceNote:
      "Plié is shock absorption and hip-controlled rotation, not a flexibility stunt. IADMS: forcing turnout through the feet loads the knee and ankle. Smooth gait work transfers to stage walking better than isolated 'core' crunches.",
    recommendedFor: ["general", "pole_stage"],
    phases: mobilityPhases,
    days: [
      {
        id: "ballet-barre",
        name: "Barre basics",
        focus: "Plié, tendu, relevé",
        kind: "mixed",
        estimatedMinutes: 35,
        exercises: [
          { exerciseId: "plie-first", sets: 4, reps: "8-12", targetRpe: 6, priority: 1, role: "main", notes: "Heels down as long as they stay honest." },
          { exerciseId: "tendu-box", sets: 3, reps: "8 front/side/back", targetRpe: 5, priority: 1, role: "main" },
          { exerciseId: "releve-calf", sets: 3, reps: "8-12", targetRpe: 6, priority: 2, role: "secondary" },
          { exerciseId: "port-de-bras", sets: 3, reps: "45s", targetRpe: 4, priority: 3, role: "accessory" },
          { exerciseId: "short-foot", sets: 2, reps: "8", targetRpe: 3, priority: 5, role: "prehab" },
        ],
      },
      {
        id: "ballet-centre",
        name: "Centre balance",
        focus: "Passé and single-leg quiet",
        kind: "mixed",
        estimatedMinutes: 30,
        exercises: [
          { exerciseId: "passe-balance", sets: 4, reps: "20-40s/side", targetRpe: 6, priority: 1, role: "main" },
          { exerciseId: "attitude-lift", sets: 3, reps: "6-10/side", targetRpe: 6, priority: 2, role: "secondary" },
          { exerciseId: "tendu-box", sets: 2, reps: "8/direction", targetRpe: 5, priority: 3, role: "accessory" },
          { exerciseId: "bird-dog", sets: 2, reps: "6/side", targetRpe: 5, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "ballet-walk",
        name: "Walk and line",
        focus: "Smooth weight transfer",
        kind: "mixed",
        estimatedMinutes: 30,
        exercises: [
          { exerciseId: "waltz-walk", sets: 4, reps: "60s", targetRpe: 4, priority: 1, role: "main" },
          { exerciseId: "performance-walk", sets: 3, reps: "45s", targetRpe: 4, priority: 1, role: "main" },
          { exerciseId: "port-de-bras", sets: 3, reps: "45s", targetRpe: 4, priority: 2, role: "secondary" },
          { exerciseId: "plie-first", sets: 2, reps: "8", targetRpe: 5, priority: 3, role: "accessory" },
          { exerciseId: "calf-wall", sets: 2, reps: "30s/side", targetRpe: 3, priority: 4, role: "prehab" },
        ],
      },
    ],
  },
  {
    id: "rucking",
    name: "Basic rucking",
    tagline: "Walk with a pack. Light, tall, one variable at a time.",
    category: "Concurrent",
    daysPerWeek: 3,
    durationWeeks: 8,
    description:
      "Two rucks and one unload-strength day. Start around 10–15% bodyweight (or 10–20 lb) for 20–40 minutes at a talking pace. Add distance or load, not both, in the same week. Stay well under ~30% bodyweight unless you have a specific event and a built base.",
    evidenceNote:
      "Military load-carriage reviews (Knapik and NSCA TSAC summaries): injury risk climbs as pack load rises, especially toward ~26–50% bodyweight. Recreational rucking does not need operator loads. Progress like running mileage — feet and Achilles adapt slower than your ego.",
    honestNote:
      "A backpack with a wrapped plate or books is fine. If you limp, the pack won. Skip rucks the day after a hard lower-body max.",
    recommendedFor: ["general", "strength_endurance"],
    phases: ruckPhases,
    days: [
      {
        id: "ruck-easy",
        name: "Easy ruck",
        focus: "Posture and minutes",
        kind: "cardio",
        estimatedMinutes: 40,
        exercises: [
          { exerciseId: "short-foot", sets: 1, reps: "8", targetRpe: 3, priority: 5, role: "prehab" },
          { exerciseId: "ruck-walk", sets: 1, reps: "20-40 min", targetRpe: 4, priority: 1, role: "conditioning", notes: "10–15% BW. Tall. Conversational. Flat ground." },
          { exerciseId: "calf-wall", sets: 2, reps: "30s/side", targetRpe: 3, priority: 4, role: "prehab" },
        ],
      },
      {
        id: "ruck-strength",
        name: "Unload strength",
        focus: "Hips, calves, trunk without the pack",
        kind: "lift",
        estimatedMinutes: 40,
        exercises: [
          { exerciseId: "rdl", sets: 3, reps: "6-8", targetRpe: 7, priority: 1, role: "main" },
          { exerciseId: "goblet-squat", sets: 3, reps: "8-10", targetRpe: 7, priority: 1, role: "main" },
          { exerciseId: "farmer-carry", sets: 3, reps: "30-40 m", targetRpe: 7, priority: 2, role: "accessory" },
          { exerciseId: "releve-calf", sets: 3, reps: "10-15", targetRpe: 7, priority: 3, role: "accessory" },
          { exerciseId: "side-plank", sets: 2, reps: "20-40s/side", targetRpe: 7, priority: 4, role: "accessory" },
        ],
      },
      {
        id: "ruck-long",
        name: "Longer or hill ruck",
        focus: "One extra variable",
        kind: "cardio",
        estimatedMinutes: 50,
        exercises: [
          { exerciseId: "ruck-hills", sets: 1, reps: "20-30 min", targetRpe: 5, priority: 1, role: "conditioning", notes: "Same or lighter pack than easy day. Walk down." },
          { exerciseId: "ruck-walk", sets: 1, reps: "10-20 min easy", targetRpe: 3, priority: 2, role: "conditioning", optional: true, notes: "Only if the hills were quiet. Do not stack a long flat ruck on a hard hill day." },
          { exerciseId: "legs-up-wall", sets: 1, reps: "3 min", targetRpe: 2, priority: 5, role: "prehab" },
        ],
      },
    ],
  },
];
